### ISSUE TITLE
Problem with "quote identifiers" option

### ISSUE THREAD

**Issue by iliaivanov** [dimitri/pgloader#679] opened 2017-11-21 22:18 UTC
Hi!

I've a problem with mysql -> postgre migration. Migration goal is to migrate data from old mysql database to the new postgre. Tables structure is already in place. I faced problem while was using the `quote identifiers` option. Here is a case:
Source mysql table columns are having camel cased column names. So it obvious to use `quote identifiers` option in order to column names be quoted with `"`. When I add this option and running pgloader with my configuration file:
```
LOAD DATABASE
    FROM mysql://root:password@123.456.78.910:3316/namehere
    INTO postgresql://user:passwd@123.456.78.910:55432/namehere

    WITH include no drop, create no tables, quote identifiers, preserve index names, no foreign keys, disable triggers
;
```
I get this error:
```
KABOOM!
FATAL error: pgloader failed to find schema "\"namehere\"" in target catalog
An unhandled error condition has been signalled:
   pgloader failed to find schema "\"namehere\"" in target catalog

What I am doing here?

pgloader failed to find schema "\"namehere\"" in target catalog
```

As you can see schema name is also surrounded by double quotes and couldn't be found. I guess it's unexpected behaviour or did I missed something here?

P.S. Mac, pgloader version is:
```
pgloader version "3.4.1d7706c"
compiled with SBCL 1.4.1
```

**Comment by dimitri** [comment] 2017-11-22 23:32
I think it got fixed in https://github.com/dimitri/pgloader/commit/6964764fb4b31cbb06c016afe6c5762ed4d9fba5 which is pretty recent, that's the following commit of where you are now. Can you try updating your sources and tell me if it works?

**Comment by iliaivanov** [comment] 2017-11-23 09:11
Probably it is actually fixed. I've installed _pgloader_ via brew, probably outdated version there?

**Comment by ipanousis** [comment] 2017-11-23 12:19
I have the same issue with:

```
pgloader version "3.4.1"
compiled with SBCL 1.2.4.debian
```

**Comment by ipanousis** [comment] 2017-11-23 16:16
@dimitri I've built the latest version on Ubuntu 14.04 and I'm getting SSL errors like it can't find where my certificates are or something similar. In the previous version of `pgloader`, e.g. 3.4.1, SSL works fine.

This is my currently built version:
```
pgloader version "3.4.d69b720"
compiled with SBCL 1.3.3
```

This is the error:
```
2017-11-23T16:13:36.021000Z NOTICE Starting pgloader, log system is ready.
KABOOM!
FATAL error: Failed to connect to pgsql at "x.x.x.x" (port 5432) as user "big_health": SSL verify error: 19 X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN
An unhandled error condition has been signalled:
   Failed to connect to pgsql at "x.x.x.x" (port 5432) as user "big_health": SSL verify error: 19 X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN
```

And my option is `sslmode=require`.

**Comment by dimitri** [comment] 2017-11-25 01:33
This looks like an SSL problem here, where you have a self signed certificate that SSL refuses to deal with?

**Comment by kirill-andr** [comment] 2018-01-24 10:23
Also have an issue with

```
KABOOM!
FATAL error: pgloader failed to find schema "backend" in target catalog
An unhandled error condition has been signalled:
   pgloader failed to find schema "backend" in target catalog

What I am doing here?

pgloader failed to find schema "backend" in target catalog

```

pgloader version "3.4.3bb128c"
compiled with SBCL 1.3.1.debian

**Comment by dimitri** [comment] 2018-01-24 10:29
Can I have a test-case to reproduce? I guess we need a MySQL backup, a PostgreSQL schema backup and a pgloader load file?

**Comment by kirill-andr** [comment] 2018-01-24 13:46
@dimitri 
I think the issue is that it is not finding the MySQL schema, but I would not be able to provide a backup since it is proprietary data. Do you have a test MySQL DB where you can test on that has a schema other than public that needs to be migrated?

**Comment by dimitri** [comment] 2018-01-24 21:53
Sure! Can you provide me with a test-case that behaves as you're showing here, with none of your sensitive data, so that I can then focus on fixing the bug? Thanks!

**Comment by dimitri** [comment] 2018-01-28 12:58
By “sure” I meant it's part of the standard set of tests I'm doing, and I'm using the f1db database from http://ergast.com/mrd/ for that, where I migrate from the MySQL database `f1db` to the PostgreSQL database `f1db` in the schema `f1db`, and it just works.

So there's something else going on here, and for me to find what it is I need your assistance. Please provide a repeatable test case.

**Comment by dimitri** [comment] 2019-05-11 23:49
Closing now.

**Closed by dimitri** 2019-05-11 23:49 UTC
Labels: Needs more testing / information
