### ISSUE TITLE
converting from mysql to pg fails on default for bigint column.

### ISSUE THREAD

**Issue by timuckun** [dimitri/pgloader#737] opened 2018-01-30 10:46 UTC
```bash
pgloader mysql://root:abc123@localhost/vc postgresql://tim@127.0.0.1/vc
2018-01-30T10:43:50.222000Z LOG Data errors in '/tmp/pgloader/'
2018-01-30T10:43:50.829000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:51.237000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:51.643000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:52.051000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:52.051000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:52.051000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:52.051000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:52.255000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:52.255000Z WARNING Failed to transform default value "NULL": byte-vector-to-bytea called on a string: "NULL"
2018-01-30T10:43:52.456000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:52.456000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:52.858000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:52.858000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:53.058000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:53.058000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:53.058000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:53.058000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:53.058000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:53.058000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:53.461000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:53.872000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:53.872000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:54.274000Z WARNING Failed to transform default value "NULL": byte-vector-to-bytea called on a string: "NULL"
2018-01-30T10:43:54.274000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:54.274000Z WARNING Failed to transform default value "NULL": The bounding indices 8 and 10 are bad for a sequence of length 4.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-30T10:43:54.481000Z ERROR Database error 42601: syntax error at or near "0"
QUERY: CREATE TABLE vc.vtiger_account
(
  accountid           bigint not null default '0',
  account_no          varchar(100) not null,
  accountname         varchar(100) not null,
  parentid            bigint default '0',
  account_type        varchar(200) default NULL,
  industry            varchar(200) default NULL,
  annualrevenue       decimal(25,8) default NULL,
  rating              varchar(200) default NULL,
  ownership           varchar(50) default NULL,
  siccode             varchar(50) default NULL,
  tickersymbol        varchar(30) default NULL,
  phone               varchar(30) default NULL,
  otherphone          varchar(30) default NULL,
  email1              varchar(100) default NULL,
  email2              varchar(100) default NULL,
  website             varchar(100) default NULL,
  fax                 varchar(30) default NULL,
  employees           bigint default '0',
  emailoptout         varchar(3) default ''0'',
  notify_owner        varchar(3) default ''0'',
  isconvertedfromlead varchar(3) default ''0''
);
2018-01-30T10:43:54.482000Z FATAL Failed to create the schema, see above.
2018-01-30T10:43:54.482000Z LOG report summary reset
       table name       read   imported     errors      total time
-----------------  ---------  ---------  ---------  --------------
  fetch meta data       1281       1281          0          0.675s
   Create Schemas          0          0          0          0.005s
 Create SQL Types          0          0          0          0.004s
    Create tables          0          0          0          0.000s
-----------------  ---------  ---------  ---------  --------------~
```

**Comment by dolzenko** [comment] 2018-01-30 16:08
I had similar issue ```
2018-01-30T15:46:23.701000Z ERROR Database error 42601: syntax error at or near "GBP"
QUERY: CREATE TABLE nexus.advertisers 
(
  id                     bigserial not null,
  name                   varchar(100) default NULL,
  created_at             timestamptz not null,
  updated_at             timestamptz not null,
  revision               bigint not null default '0',
  active                 boolean not null default 't',
  advertiser_vertical_id bigint default NULL,
  default_currency       varchar(3) not null default ''GBP'',
  timezone               varchar(30) not null default ''Europe/London'',
  domain_id              bigint default NULL,
  zzz_excluded_providers text default NULL,
  new_until              date default NULL,
  providers              text default NULL,
  atlas_client_id        numeric default NULL,
  sharp_spring_id        numeric default NULL,
  dcm_user_profile_ids   varchar(255) default NULL
);
``` 
seems to be solved by installing pgloader from Git

**Comment by timuckun** [comment] 2018-01-31 00:34
I can't build pgloader from git. It fails on mac so I tried the dockerfile that came with it and that also failed

```bash
; Fetching #<URL "http://beta.quicklisp.org/archive/yason/2016-02-08/yason-v0.7.6.tgz">
; 25.96KB
==================================================
26,582 bytes in 0.01 seconds (3244.87KB/sec)
; Loading "yason"
[package yason]......
; Loading "pgloader"
;
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     The symbol "HOST-ENT-ADDRESS-TYPE" is not external in the SB-BSD-SOCKETS package.
;
;       Line: 101, Column: 60, File-Position: 4268
;
;       Stream: #<SB-SYS:FD-STREAM
;                 for "file /opt/src/pgloader/build/quicklisp/dists/quicklisp/software/postmodern-20171227-git/cl-postgres/public.lisp"
;                 {100E6F92B3}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {10039CF4A3}>:

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "cl-postgres" "cl-postgres" "public">

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "cl-postgres" "cl-postgres" "public">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "cl-postgres" "cl-postgres" "public">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "pgloader"
  5: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  6:                                 Skip rest of --eval and --load options.
  7:                                 Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-postgres" "cl-postgres" "public">)))
0] ;
; compilation unit aborted
;   caught 3 fatal ERROR conditions
;   caught 1 ERROR condition
touch build/libs.stamp
sbcl --noinform --no-sysinit --no-userinit --load build/quicklisp/setup.lisp                \
             --eval '(ql:write-asdf-manifest-file "build/manifest.ql")'  \
             --eval '(quit)'
WARNING:
Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)
Trying to continue anyway.
mkdir -p build/bin
sbcl --noinform --no-sysinit --no-userinit --load build/quicklisp/setup.lisp               \
             --eval '(ql:quickload "buildapp")'                   \
             --eval '(buildapp:build-buildapp "build/bin/buildapp.sbcl")'              \
             --eval '(quit)'
WARNING:
Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)
Trying to continue anyway.
To load "buildapp":
  Install 1 Quicklisp release:
    buildapp
; Fetching #<URL "http://beta.quicklisp.org/archive/buildapp/2015-12-18/buildapp-1.5.6.tgz">
; 16.00KB
==================================================
16,389 bytes in 0.00 seconds (3200.98KB/sec)
; Loading "buildapp"
[package buildapp]....
WARNING:
Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)
Trying to continue anyway.
;; loading system "buildapp"
[undoing binding stack and other enclosing state... done]
[saving current Lisp image into /opt/src/pgloader/build/bin/buildapp.sbcl:
writing 5680 bytes from the read-only space at 0x20000000
writing 3120 bytes from the static space at 0x20100000
writing 65798144 bytes from the dynamic space at 0x1000000000
done]
mkdir -p build/bin
build/bin/buildapp.sbcl      --logfile /tmp/build.log                \
                         --require sb-posix --require sb-bsd-sockets --require sb-rotate-byte                        \
                         --sbcl sbcl                            \
                         --asdf-path .                           \
                         --asdf-tree build/quicklisp/local-projects     \
                         --manifest-file build/manifest.ql             \
                         --asdf-tree build/quicklisp/dists              \
                         --asdf-path .                           \
                         --load-system pgloader               \
                         --load src/hooks.lisp                   \
                         --entry pgloader:main                   \
                         --dynamic-space-size 4096         \
                         --compress-core                    \
                         --output build/bin/pgloader.tmp
WARNING:
Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)
Trying to continue anyway.
WARNING:
Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)
Trying to continue anyway.
;; loading system "pgloader"
Fatal COMPILE-FILE-ERROR:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "cl-postgres" "cl-postgres" "public">
Makefile:136: recipe for target 'build/bin/pgloader' failed
make: *** [build/bin/pgloader] Error 1
The command '/bin/sh -c make' returned a non-zero code: 2
```

**Comment by dimitri** [comment] 2018-01-31 14:39
Which version of SBCL is that?

**Comment by timuckun** [comment] 2018-01-31 20:36
I installed with brew. I tried by doing a brew install pgloader and that didn't work (the error above) then I tried installing brew install --HEAD and that's where I got the error. According to brew SBCL is
sbcl: stable 1.4.3 (bottled), HEAD

**Comment by dimitri** [comment] 2018-03-03 16:28
Building from git, from brew and from docker should all be fixed now, I think. Also it's been reported that this issue is fixed with current pgloader version from git. So I'm closing. If some of this is still a problem, consider either opening this issue again if the problem is related to default values, or finding similar issues or opening a new one if it's related to building pgloader.

**Closed by dimitri** 2018-03-03 16:28 UTC
