### ISSUE TITLE
SOS!!!    sqlite3 to postgres   error  (LENGTH PGLOADER.SQLITE::TOKENS) = 2.

### ISSUE THREAD

**Issue by xyhc** [dimitri/pgloader#548] opened 2017-05-09 09:33 UTC
linux  version
centos 6.5
sqlite3 version
3.6.20
postgresql version
9.6.2

command

     ./build/bin/pgloader    ./data.db postgresql://postgres:postgres@localhost:5432/good

error
```
2017-05-09T17:26:26.037000+08:00 LOG Main logs in '/tmp/pgloader/pgloader.log'
2017-05-09T17:26:26.045000+08:00 LOG Data errors in '/tmp/pgloader/'
2017-05-09T17:26:26.247000+08:00 FATAL An unhandled error condition has been signalled:
   The assertion (= 1 (LENGTH PGLOADER.SQLITE::TOKENS)) failed with
   (LENGTH PGLOADER.SQLITE::TOKENS) = 2.
```

**Comment by PaulMest** [comment] 2017-05-09 21:32
I've recently run into a problem with `pgloader`. I decided to use the `[sequel](https://github.com/jeremyevans/sequel)` Ruby gem.

To use that, you would do something like this:
```bash
$ sequel -C sqlite://full/path/to/data.db postgresql://postgres:postgres@localhost:5432/good
```

**Comment by xyhc** [comment] 2017-05-10 01:45
Thanks!   The sequel is a better tool than pgloader

**Comment by dimitri** [comment] 2017-05-10 08:57
The cryptic error in pgloader is because it fails to recognise the type name of one of your columns in SQLite, containing something extra other than one of "unsigned" "short", "varying" "native", "nocase", "auto_increment". To be able to do a proper job at migrating the schema, pgloader needs to understand your data types here.

For full tracking of the issue here's the part of the code responsible for failing the assert: https://github.com/dimitri/pgloader/blob/master/src/sources/sqlite/sqlite-cast-rules.lisp#L55

It happens that SQLite since version 3 accepts anything as a type name and will then behave depending on the values in each column rather than being a relational database. It comes with some challenges when migrating over to a relational database of course. Can you find the column with a _strange_ data type name so that we can fix pgloader for other users?

**Comment by dimitri** [comment] 2017-06-17 14:33
Closing because lacks information. If you have some, please consider opening again.

**Closed by dimitri** 2017-06-17 14:33 UTC

**Comment by joshuacano** [comment] 2017-11-28 01:12
I will add that I spent a few hours banging my head against this as well. Decided to go with sequel as well with no issues.

**Comment by dimitri** [comment] 2017-11-28 17:16
Thanks for the full debug trace here. It boils down to stack entry 10 where we can see that the SQLite data type is spelled `NUMERIC(20, 6)`, with an extra space in there. The `PGLOADER.SQLITE::NORMALIZE` function does not expect that. It's a manual tokeniser, not smart enough.

**Comment by dimitri** [comment] 2017-11-28 17:28
Please build from sources and try again, it should work now!

**Comment by smacedo2018** [comment] 2018-11-07 01:32
Hi, after some debugging, I got to same sort of problem:
(PGLOADER.SOURCE.SQLITE::NORMALIZE "VARCHAR ( 255 )")

 varchar ( 255 )
           ^ (Line 1, Column 9, Position 9)

pgloader version "3.5.2"
compiled with SBCL 1.4.0-1.el7

CentOS7

Thank you Dimitri!

**Comment by dimitri** [comment] 2018-11-07 10:02
Hi @smacedo2018 ; thanks for the bug report, I could reproduce and fix the problem. Please build from sources and try again.
