### ISSUE TITLE
Problems when upgrading from 3.2.1 to 3.5.1

### ISSUE THREAD

**Issue by Themanwithoutaplan** [dimitri/pgloader#823] opened 2018-08-13 12:50 UTC
Because of the challenges associated with building pgloader on MacOS with macports I've left it untouched for a couple of years. Ran a new build with a checkout and got some failures. From the error report it looks like the handling of NULLs has changed slightly but I couldn't find anything in the change log indicating what is different. 

 - [ ] pgloader --version
  
    ```
   pgloader version "3.5.34cc253"
    ```
  
  - [ ] did you test a fresh compile from the source tree?
    
yes
    
  - [ ] did you search for other similar issues?

yes
    
  - [ ] how can I reproduce the bug?

Download the linked file and pipe it with gzip -d -c into pgloader with the script.

```
LOAD CSV
    FROM stdin (
    pageid,
    createDate,
    archive,
    label,
    crawlid,
    wptid,
    wptrun,
    url,
    urlShort,
    urlhash,
    cdn [null if '\N'],
    startedDateTime,
    TTFB [null if '\N'],
    renderStart,
    onContentLoaded [null if '\N'],
    onLoad,
    fullyLoaded,
    visualComplete,
    PageSpeed [null if '\N'],
    SpeedIndex [null if '\N'],
    rank [null if '\N'],
    reqTotal,
    reqHtml,
    reqJS,
    reqCSS,
    reqImg,
    reqGif,
    reqJpg,
    reqPng,
    reqFont,
    reqFlash,
    reqJson,
    reqOther,
    bytesTotal,
    bytesHtml,
    bytesJS,
    bytesCSS,
    bytesImg,
    bytesGif,
    bytesJpg,
    bytesPng,
    bytesFont,
    bytesFlash,
    bytesJson,
    bytesOther,
    bytesHtmlDoc,
    numDomains [null if '\N'],
    maxDomainReqs,
    numRedirects,
    numHttps,
    numGlibs,
    numErrors,
    numCompressed,
    numDomElements,
    maxageNull, maxage0, maxage1, maxage30, maxage365, maxageMore,
    gzipTotal, gzipSavings,
    _connections,
    _adult_site,
    avg_dom_depth,
    document_height,
    document_width,
    localstorage_size,
    sessionstorage_size,
    num_iframes,
    num_scripts,
    doctype,
    meta_viewport,
    reqAudio,
    reqVideo,
    reqText,
    reqXml,
    reqWebp,
    reqSvg,
    bytesAudio,
    bytesVideo,
    bytesText,
    bytesXml,
    bytesWebp,
    bytesSvg
  )

    INTO postgresql://postgres@localhost/http?urls
    target columns (
    pageid, "createDate", archive, label, crawlid, wptid,
    wptrun, url, cdn, "startedDateTime", "TTFB",
    "renderStart", "onContentLoaded", "onLoad", "fullyLoaded", "visualComplete",
    "PageSpeed",
    "SpeedIndex", rank, "reqTotal", "reqHTML", "reqJS",
    "reqCSS", "reqImg", "reqGIF", "reqJPG", "reqPNG",
    "reqFont", "reqFlash", "reqJSON", "reqOther", "bytesTotal",
    "bytesHTML", "bytesJS", "bytesCSS", "bytesImg", "bytesGIF",
    "bytesJPG", "bytesPNG", "bytesFont", "bytesFlash", "bytesJSON",
    "bytesHTMLDoc", "bytesOther", "numDomains", "maxDomainReqs",
    "numRedirects", "numHTTPS", "numGlibs", "numErrors", "numCompressed",
    "numDomElements", "maxageNull", "maxage0", "maxage1", "maxage30",
    "maxage365", "maxageMore", "gzipTotal", "gzipSavings", meta_viewport,
    "reqAudio", "reqVideo", "reqText", "reqXML", "reqWebP", "reqSVG",
    "bytesAudio", "bytesVideo", "bytesText", "bytesXML", "bytesWebP", "bytesSVG"
    )

    WITH
        truncate,
        fields optionally enclosed by '"',
        fields escaped by '\',
        fields terminated by ',',
        csv escape mode following
```

  - [ ] pgloader output you obtain
  
```
2018-08-13T14:37:39.114000+02:00 WARNING Error reading pgass file: At

  :5432:*:charlieclark:MUZ
  ^ (Line 1, Column 0, Position 0)

In context PGPASS-ENTRY:

While parsing PGPASS-ENTRY. Problem:

  The production

    #\:

  does not satisfy the predicate PGLOADER.PARSER::PGPASS-CHAR-P.

Expected:

     the character * (ASTERISK)
  or the character \ (REVERSE_SOLIDUS)
  or any character satisfying PGPASS-CHAR-P
2018-08-13T14:37:39.155000+02:00 WARNING Error reading pgass file: At

  :5432:*:charlieclark:MUZ
  ^ (Line 1, Column 0, Position 0)

In context PGPASS-ENTRY:

While parsing PGPASS-ENTRY. Problem:

  The production

    #\:

  does not satisfy the predicate PGLOADER.PARSER::PGPASS-CHAR-P.

Expected:

     the character * (ASTERISK)
  or the character \ (REVERSE_SOLIDUS)
  or any character satisfying PGPASS-CHAR-P
^C2018-08-13T14:37:44.601000+02:00 FATAL Interactive interrupt at #x7FFF56B310B2.
2018-08-13T14:37:44.602000+02:00 ERROR End of file while collecting quoted item: #<CSV-READER LINE-IDX:16128 CHARACTER-LINE-IDX:576 CHARACTER-IDX:9805825 "8" {100A3C50D3}>
2018-08-13T14:37:44.602000+02:00 FATAL End of file while collecting quoted item: #<CSV-READER LINE-IDX:16128 CHARACTER-LINE-IDX:576 CHARACTER-IDX:9805825 "8" {100A3C50D3}>
2018-08-13T14:37:44.674000+02:00 LOG report summary reset
             table name     errors       rows      bytes      total time
-----------------------  ---------  ---------  ---------  --------------
                  fetch          0          0                     0.011s
-----------------------  ---------  ---------  ---------  --------------
        "public"."urls"          2          0                     5.228s
-----------------------  ---------  ---------  ---------  --------------
        Files Processed          0          1                     0.024s
COPY Threads Completion          0          2                     5.273s
             after load          0          5                     0.048s
-----------------------  ---------  ---------  ---------  --------------
      Total import time          2          0                     5.345s
Unhandled CL-POSTGRES:DATABASE-CONNECTION-LOST in thread #<SB-THREAD:THREAD "lparallel" RUNNING
                                                            {10098E26F3}>:
  Database error: Connection to database server lost.

Backtrace for: #<SB-THREAD:THREAD "lparallel" RUNNING {10098E26F3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<CL-POSTGRES:DATABASE-CONNECTION-LOST {100618A043}> #<unused argument> :QUIT NIL)
1: ((LAMBDA (SB-THREAD::C SB-THREAD::H) :IN SB-THREAD::%EXIT-OTHER-THREADS) #<CL-POSTGRES:DATABASE-CONNECTION-LOST {100618A043}> #<FUNCTION (LAMBDA (SB-THREAD::C SB-THREAD::H) :IN SB-THREAD::%EXIT-OTHER-THREADS) {21CB12AB}>)
2: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<CL-POSTGRES:DATABASE-CONNECTION-LOST {100618A043}>)
3: (INVOKE-DEBUGGER #<CL-POSTGRES:DATABASE-CONNECTION-LOST {100618A043}>)
4: (ERROR #<CL-POSTGRES:DATABASE-CONNECTION-LOST {100618A043}>)
5: (SB-KERNEL:WITH-SIMPLE-CONDITION-RESTARTS ERROR NIL CL-POSTGRES:DATABASE-CONNECTION-LOST :MESSAGE "Connection to database server lost.")
6: (CL-POSTGRES::ENSURE-CONNECTION #<CL-POSTGRES:DATABASE-CONNECTION {1012380813}>)
7: (CL-POSTGRES:CLOSE-DB-WRITER #<CL-POSTGRES::BULK-COPIER "public"."urls" ("pageid" "createDate" "archive" "label" "crawlid" "wptid" "wptrun" "url" "cdn" "startedDateTime" "TTFB" "renderStart" ...) {1005A97DA3}> :ABORT NIL)
8: ((FLET "CLEANUP-FUN-5" :IN PGLOADER.PGCOPY::COPY-PARTIAL-BATCH)) [cleanup]
9: (PGLOADER.PGCOPY::COPY-PARTIAL-BATCH "\"public\".\"urls\"" ("\"pageid\"" "\"createDate\"" "\"archive\"" "\"label\"" "\"crawlid\"" "\"wptid\"" "\"wptrun\"" "\"url\"" "\"cdn\"" "\"startedDateTime\"" "\"TTFB\"" "\"renderStart\"" ...) #S(PGLOADER.PGCOPY::BATCH :START 461 :DATA #(#(57 51 50 48 52 55 53 50 9 49 53 51 ...) #(57 51 50 48 52 55 53 51 9 49 53 51 ...) #(57 51 50 48 52 55 53 52 9 49 53 51 ...) #(57 51 50 48 52 55 53 53 9 49 53 51 ...) #(57 51 50 48 52 55 53 54 9 49 53 51 ...) #(57 51 50 48 52 55 53 55 9 49 53 51 ...) #(57 51 50 48 52 55 53 56 9 49 53 51 ...) #(57 51 50 48 52 55 53 57 9 49 53 51 ...) #(57 51 50 48 52 55 54 48 9 49 53 51 ...) #(57 51 50 48 52 55 54 49 9 49 53 51 ...) #(57 51 50 48 52 55 54 50 9 49 53 51 ...)
```

  - [ ] https://legacy.httparchive.org/downloads/httparchive_mobile_Aug_1_2018_pages.csv.gz

**Comment by dimitri** [comment] 2018-08-14 07:08
It seems that the pgloader parser for the PostgreSQL pgpass file is failing to parse lines whith en empty hostname. Reading the docs again at https://www.postgresql.org/docs/current/static/libpq-pgpass.html:

> The host name field is matched to the host connection parameter if that is specified, otherwise to the hostaddr parameter if that is specified; if neither are given then the host name localhost is searched for.

So ok, I misread it the first time, it seems that empty field for hostname is accepted and should default to "localhost".  Please consider building from fresh sources and trying again...

**Comment by Themanwithoutaplan** [comment] 2018-08-14 07:44
I just did a git fetch and git pull and build but I'm still getting errors relating to the '\n' (CSV is created by MySQL).

2018-08-14T09:42:50.396000+02:00 ERROR PostgreSQL ["\"public\".\"urls\""] Database error 22P02: invalid input syntax for integer: "N"
CONTEXT: COPY urls, line 1, column PageSpeed: "N"

**Comment by dimitri** [comment] 2018-08-14 08:08
Oh I missed the error on the actual processing of the data, will have a look at next opportunity.

**Comment by Themanwithoutaplan** [comment] 2018-08-14 08:12
That's how things usually work… ;-) In the meantime 3.2 is fine for my needs.
BTW I couldn't find the change log in the docs or anything indicating the changes, which are only to be expected over time. Is this a deliberate omission?

**Comment by dimitri** [comment] 2018-08-14 08:44
I think the change might come from the CSV library that pgloader is using, https://github.com/AccelerationNet/cl-csv, where they cleaned up their internal APIs (refactoring) and might have had some regressions because of that.

**Comment by Themanwithoutaplan** [comment] 2018-08-14 09:34
I guess that `[null if '\N']` is no longer supported. At least it's no longer mentioned in the pgloader docs but I couldn't work out what it should be replaced with.

**Comment by dimitri** [comment] 2019-05-11 23:24
It's still supported. Can you try again from recent sources? the building has been worked on too, and a simplified version of it is available with the `make save` target, worth trying. I'm now closing this issue for clean-up perspective, please re-open if you still have the problem and need something to be done about it. Then add more information to help us fix the problems.

**Closed by dimitri** 2019-05-11 23:24 UTC

**Comment by Themanwithoutaplan** [comment] 2019-05-22 15:57
So, having being able to build from a checkout, I can confirm that the problem sitll exists.

```
pgloader version "3.6.12e7880"
compiled with SBCL 1.5.2
```

With the error being `Database error 22P02: invalid input syntax for integer: "N"
CONTEXT: COPY urls, line 1, column PageSpeed: "N"`

**Comment by dimitri** [comment] 2019-05-22 20:05
With current sources and another source file from the same website (because the one you gave is now a 404 for some reasons), I managed to import the content of the file after some edits to the load file, as mentioned below.

First I had to create the target schema, and the http archive website offers MySQL schema files, so I used pgloader to create the schema with the following load file:

```
load database
  from mysql://root@localhost/httparchive
  into pgsql:///httparchive
  with quote identifiers ;
```

That's because I didn't want to edit your input file to target columns without having to quote all of them. Though it would be simpler that way. Anyway now that I had a database I could arrange your load file to good results:

```
LOAD CSV
    FROM stdin
   (
    pageid,
    createDate,
    archive,
    label,
    crawlid,
    wptid,
    wptrun,
    url,
    urlShort,
    urlhash,
    cdn [null if '\N'],
    startedDateTime,
    TTFB [null if '\N'],
    renderStart,
    onContentLoaded [null if '\N'],
    onLoad,
    fullyLoaded,
    visualComplete,
    PageSpeed [null if '\N'],
    SpeedIndex [null if '\N'],
    rank [null if '\N'],
    reqTotal,
    reqHtml,
    reqJS,
    reqCSS,
    reqImg,
    reqGif,
    reqJpg,
    reqPng,
    reqFont,
    reqFlash,
    reqJson,
    reqOther,
    bytesTotal,
    bytesHtml,
    bytesJS,
    bytesCSS,
    bytesImg,
    bytesGif,
    bytesJpg,
    bytesPng,
    bytesFont,
    bytesFlash,
    bytesJson,
    bytesOther,
    bytesHtmlDoc,
    numDomains [null if '\N'],
    maxDomainReqs,
    numRedirects,
    numHttps,
    numGlibs,
    numErrors,
    numCompressed,
    numDomElements,
    maxageNull, maxage0, maxage1, maxage30, maxage365, maxageMore,
    gzipTotal, gzipSavings,
    _connections,
    _adult_site,
    avg_dom_depth,
    document_height,
    document_width,
    localstorage_size,
    sessionstorage_size,
    num_iframes,
    num_scripts,
    doctype,
    meta_viewport,
    reqAudio,
    reqVideo,
    reqText,
    reqXml,
    reqWebp,
    reqSvg,
    bytesAudio,
    bytesVideo,
    bytesText,
    bytesXml,
    bytesWebp,
    bytesSvg
  )

    INTO postgresql:///httparchive
    target table httparchive.pages
    target columns
    (
      pageid, "createDate", archive, label, crawlid, wptid,
      wptrun, url, cdn, "startedDateTime", "TTFB",
      "renderStart", "onContentLoaded", "onLoad", "fullyLoaded", "visualComplete",
      "PageSpeed",
      "SpeedIndex", rank, "reqTotal", "reqHtml", "reqJS",
      "reqCSS", "reqImg", "reqGif", "reqJpg", "reqPng",
      "reqFont", "reqFlash", "reqJson", "reqOther", "bytesTotal",
      "bytesHtml", "bytesJS", "bytesCSS", "bytesImg", "bytesGif",
      "bytesJpg", "bytesPng", "bytesFont", "bytesFlash", "bytesJson",
      "bytesHtmlDoc", "bytesOther", "numDomains", "maxDomainReqs",
      "numRedirects", "numHttps", "numGlibs", "numErrors", "numCompressed",
      "numDomElements", "maxageNull", "maxage0", "maxage1", "maxage30",
      "maxage365", "maxageMore", "gzipTotal", "gzipSavings", meta_viewport,
      _connections, _adult_site,avg_dom_depth,
      document_height, document_width, localstorage_size, sessionstorage_size,
      num_iframes, num_scripts, doctype,
      "reqAudio", "reqVideo", "reqText", "reqXml", "reqWebp", "reqSvg",
      "bytesAudio", "bytesVideo", "bytesText", "bytesXml", "bytesWebp", "bytesSvg"
    )

    WITH
        truncate,
        fields optionally enclosed by '"',
        fields escaped by '\',
        fields terminated by ',',
        csv escape mode following,
        on error stop,
        drop indexes;
```

I added columns that are NOT NULL in the schema version I have. And it worked here, not from the first try, I had to fiddle around with the CSV options. First on a sample, which was easy to make work, and then it failed on the original file of course. Some more editing and there we go.

Here's my command output:

```
$ gunzip -c httparchive_mobile_Aug_15_2018_pages.csv.gz | ~/dev/pgloader/build/bin/pgloader -v 823.load 
2019-05-22T21:52:03.008000+02:00 NOTICE Starting pgloader, log system is ready.
2019-05-22T21:52:03.017000+02:00 LOG pgloader version "3.6.b8da7dd"
2019-05-22T21:52:03.056000+02:00 LOG Data errors in '/private/tmp/pgloader/'
2019-05-22T21:52:03.056000+02:00 LOG Parsing commands from file #P"/Users/dim/dev/temp/pgloader-issues/823/823.load"
2019-05-22T21:52:03.268000+02:00 NOTICE COPY "httparchive"."pages"
2019-05-22T21:52:03.273000+02:00 NOTICE Opening #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {100001E7D3}>
2019-05-22T21:57:03.384000+02:00 ERROR Database error 22P02: invalid input syntax for integer: "N"
CONTEXT: COPY pages, line 1, column PageSpeed: "N"
2019-05-22T21:57:03.405000+02:00 LOG report summary reset
             table name     errors       read   imported      bytes      total time       read      write
-----------------------  ---------  ---------  ---------  ---------  --------------  ---------  ---------
                  fetch          0          0          0                     0.005s    
-----------------------  ---------  ---------  ---------  ---------  --------------  ---------  ---------
  "httparchive"."pages"          1    1267278          0                   5m0.086s   5m0.085s    18.223s
-----------------------  ---------  ---------  ---------  ---------  --------------  ---------  ---------
        Files Processed          0          1          1                     0.015s    
COPY Threads Completion          0          2          2                   5m0.168s    
-----------------------  ---------  ---------  ---------  ---------  --------------  ---------  ---------
      Total import time          1    1267278          0                   5m0.183s    
```

Hope you'll have the same luck as I did?

**Comment by Themanwithoutaplan** [comment] 2019-05-23 09:49
For some reason your update isn't showing here. I know I can go from the MySQL DB, but I want to be able to cut that step out and use the CSV directly as it's a lot quicker. Also, at the moment I'm having trouble connecting to my local MySQL DB.

Unfortunately I don't see any changes you made to make the import successful. However, based on the error message I changed the condition to `[null if 'N']`, ie. simply removing the backslash and that seems to solve the problem. NB `[null if blanks]` does not. Presumably this is due to the change in the CSV library you mentioned.

Enclosing a sample line that will cause the error, which should make testing easier.
[sample.txt](https://github.com/dimitri/pgloader/files/3211439/sample.txt)

**Comment by dimitri** [comment] 2019-05-23 10:40
I deleted my last post, because I though I had figured it out, and I didn't:

```
$ gunzip -c httparchive_mobile_Aug_15_2018_pages.csv.gz | ~/dev/pgloader/build/bin/pgloader -v 823.load 
2019-05-22T21:52:03.008000+02:00 NOTICE Starting pgloader, log system is ready.
2019-05-22T21:52:03.017000+02:00 LOG pgloader version "3.6.b8da7dd"
2019-05-22T21:52:03.056000+02:00 LOG Data errors in '/private/tmp/pgloader/'
2019-05-22T21:52:03.056000+02:00 LOG Parsing commands from file #P"/Users/dim/dev/temp/pgloader-issues/823/823.load"
2019-05-22T21:52:03.268000+02:00 NOTICE COPY "httparchive"."pages"
2019-05-22T21:52:03.273000+02:00 NOTICE Opening #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {100001E7D3}>
2019-05-22T21:57:03.384000+02:00 ERROR Database error 22P02: invalid input syntax for integer: "N"
CONTEXT: COPY pages, line 1, column PageSpeed: "N"
2019-05-22T21:57:03.405000+02:00 LOG report summary reset
             table name     errors       read   imported      bytes      total time       read      write
-----------------------  ---------  ---------  ---------  ---------  --------------  ---------  ---------
                  fetch          0          0          0                     0.005s    
-----------------------  ---------  ---------  ---------  ---------  --------------  ---------  ---------
  "httparchive"."pages"          1    1267278          0                   5m0.086s   5m0.085s    18.223s
-----------------------  ---------  ---------  ---------  ---------  --------------  ---------  ---------
        Files Processed          0          1          1                     0.015s    
COPY Threads Completion          0          2          2                   5m0.168s    
-----------------------  ---------  ---------  ---------  ---------  --------------  ---------  ---------
      Total import time          1    1267278          0                   5m0.183s
```

With the following line as the suspect:

```
$ gunzip -c httparchive_mobile_Aug_15_2018_pages.csv.gz | head -n 1267278 | tail -n 1
"29998366","1535454038","All","Aug 15 2018","563","180828_E_VBV","2","https://merch.halotop.com/","https://merch.halotop.com/","48710","Cloudflare","1535449440","1660","4700","6517","71703","73915","36400",\N,"9802",\N,"153","5","11","2","129","17","2","110","6","0","0","0","70035416","28209","239190","44510","69540604","723","112563","69427318","182903","0","0","0","21110","7","127","1","0","0","153","15","1569","0","66","3","0","0","84","978650","0","16","0","14","9207","543","0","0","3","119","html","width=device-width,initial-scale=1","0","0","0","0","0","0","0","0","0","0","0","0","5","4","0"
```

**Comment by Themanwithoutaplan** [comment] 2019-05-23 10:53
The error is now in all exports because the metric has been deprecated but the schema untouched. Some of the other constraints are odd because it looks like MySQL isn't enforcing them all the time so `numDomains` also sometimes is `NULL` in the values but I don't mind such recods failing because you can't do anything with them anyway.

Now that I've figured out the workaround I wonder whether this should be documented and if so where? Also whether `[null if blanks]` needs changing.

Now I just need to fix the problem when importing from MySQL to satisfy my foreign keys!

**Comment by dimitri** [comment] 2019-05-27 17:42
I don't think I understand what you expect `[null if blanks]` to do when the input is `N`. It just does nothing which I think is per spec. What happens here, if I understand correctly, is that the parsing of the CSV file with with the needed options (both `csv escape mode following` and `fields escaped by '\'`) makes it incompatible with CSV fields that just are spelled `\N` with no quoting etc. Your workaround when the backslash has been eaten already looks good to me.

```
CL-USER> (cl-csv:read-csv-row "a,\"b\",\N,c" :separator #\, :quote #\" :escape "\\" :escape-mode :forward)
("a" "\"b\"" "N" "c")
```

That's using only bits of CL-CSV. No pgloader involved. And we see that the backslash in `\N` has been eaten by the CSV parser. Is that a bug of the CL-CSV tool? Then we should open an issue there...

**Comment by Themanwithoutaplan** [comment] 2019-05-28 09:17
The issue is really related to changes in the "bundle" since 3.2. As I had trouble with this and building pgloader I stuck with 3.2.1. Now that the build issues seem to have been completely resolved with `make save` (thanks very much for this) I'm able to run some comparisions.

Even if I comment out the `fields escaped by '\'` command the more recent version of the library still seems to struggle. It's fine with me that `[null if 'N']` works, I was just thinking about whether and how this should be documented. Presumably it should be covered for any CSV dump created by MySQL where MySQL -> Postgres isn't possible.

I've no experience with using Lisp on the command line so I really can't test the CSV library and wouldn't know how to submit a bug.

**Comment by dimitri** [comment] 2019-05-28 12:47
The CL-CSV project is on GitHub at https://github.com/AccelerationNet/cl-csv and I'm going to see about that. Your regression definitely is a CL-CSV regression and pgloader “just” happened to have been updating its build-dependency with a newer release of the lib.
