### ISSUE TITLE
CSV import fails

### ISSUE THREAD

**Issue by thorro** [dimitri/pgloader#346] opened 2016-02-27 11:07 UTC
Great utility, but I get errors when importing CSV data, which looks like:

> attribute,paper towels,...
> attribute,"paper, towels",...
> attribute,paper \" towels,...
> attribute,\"paper towels\",...

I need 2nd field in postgres database to look like after import:

> paper towels
> paper, towels
> paper " towels
> "paper towels"

But can't seem to get the right options to import the data. At best I get, for example:
\paper towels\

At worst the error "ERROR we are reading non quoted csv data and found a quote at ..."

Command
...

> ```
>  WITH truncate,
>        skip header = 0,
>        fields optionally enclosed by '"',
>        fields escaped by '\',
>        fields terminated by ','
> ```
> 
> ...

Is there a way to import data like this?

**Comment by dimitri** [comment] 2016-02-27 14:22
Here's the self-contained test file I've been using to reproduce your error:

```
LOAD CSV
     FROM inline
     INTO postgresql:///pgloader?issue346

     WITH truncate,
          fields optionally enclosed by '"',
          fields escaped by backslash-quote,
          fields terminated by ','

   BEFORE LOAD DO
    $$ drop table if exists issue346; $$,
    $$ create table issue346 (f1 text, f2 text); $$;


attribute,paper towels
attribute,"paper, towels"
attribute,paper \" towels
attribute,\"paper towels\"
```

Now here's what I get, and by varying the arguments I can't get better than what you report:

```
CL-USER> (pgloader:run-commands "/Users/dim/dev/temp/pgloader-issues/346.load" :client-min-messages :warning)
2016-02-27T14:33:25.001000+01:00 LOG Parsing commands from file #P"/Users/dim/dev/temp/pgloader-issues/346.load"
2016-02-27T14:33:25.209000+01:00 ERROR we are reading non quoted csv data and found a quote at 11
attribute,\"paper towels\"
             table name       read   imported     errors      total time       read      write
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
                  fetch          0          0          0          0.000s                     
            before load          2          2          0          0.014s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
               issue346          3          3          1          0.001s               0.001s
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
COPY Threads Completion          3          3          0          0.012s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
      Total import time          3          3          1          0.210s                     
NIL
```

I think this is a bug of the CSV parsing lib I am using, https://github.com/AccelerationNet/cl-csv :

```lisp
CL-USER> (handler-case
             (cl-csv:read-csv-row "attribute,\\\"paper towels\\\"" :separator #\, :quote #\" :escape #\\)
           (condition (c)
             (format t "~a" c)))
we are reading non quoted csv data and found a quote at 11
attribute,\"paper towels\"
NIL
CL-USER> (handler-case
             (cl-csv:read-csv-row "attribute,\\\"paper towels\\\"" :separator #\, :quote #\" :escape "\\\"")
           (condition (c)
             (format t "~a" c)))
we are reading non quoted csv data and found a quote at 11
attribute,\"paper towels\"
NIL
```

**Comment by pacificobr** [comment] 2017-06-20 19:22
Are there any fix for this? Any workaround? 

I've been using perl to fix files. But it takes a lot of time to create regexs.

**Comment by dimitri** [comment] 2017-06-21 10:56
No bug fix that I know of, no, because the CSV input data has a broken usage of the quote: it is used to protect a separator in a data field, and also is used in the middle of another field without being escaped.

It might be possible for pgloader to offer a way to pre-process input files before parsing them as CSV, but then we will end up with regexp surgery and I don't guess it will be much faster than `perl ... | pgloader - ...`.

**Comment by pacificobr** [comment] 2017-06-21 13:02
Sharing the sample code to help others with the same problem.

Works if the csv is not quoted. Otherwise must change the regex.

```
#!/bin/bash
perl -pi -e 's/"/""/g' path_to_csv/*.csv
```

**Comment by dimitri** [comment] 2017-06-21 15:44
Closing the issue now. Please consider re-opening if necessary.

**Closed by dimitri** 2017-06-21 15:44 UTC
Labels: Must Fix, Solution unclear
