### ISSUE TITLE
 Undefined alien: "SSL_get_version"

### ISSUE THREAD

**Issue by zacksiri** [dimitri/pgloader#226] opened 2015-04-30 10:58 UTC
```
load database
  FROM       mssql://blah:pass@some.ip.address/blah
  INTO  postgresql://somethig:fdsdsfsdfsdf@localhost:5432/blah_mirror

  INCLUDING ONLY TABLE NAMES LIKE 'sometable' IN SCHEMA 'dbo'

  WITH include drop, create tables, no truncate,  
       create indexes, reset sequences, foreign keys

  SET work_mem to '16MB', maintenance_work_mem to '512MB'

  BEFORE LOAD DO 
  $$ create database if not exists blah_mirror with owner somethig; $$;
```

I am getting this error when i try to run it

```
An unhandled error condition has been signalled:
   Undefined alien: "SSL_get_version"

; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
```

and this is with the --debug flag 

```
An unhandled error condition has been signalled:
   There is no applicable method for the generic function
     #<STANDARD-GENERIC-FUNCTION PGLOADER.CONNECTION:CONN-TYPE (1)>
   when called with arguments
     (NIL).

; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
```

**Comment by dimitri** [comment] 2015-05-01 19:24
Sounds strange. Can you check that you have installed the openssl lib? What platform are you running on? would you consider building from sources and trying again?

**Comment by biddrafter** [comment] 2015-05-07 22:57
I also have the same error. Ubuntu server 15.04 64 bit. Basic postgres install. Pulled pgloader via apt-get. Verified that openssl package was installed. Was trying to copy from SQL Server to postgres. 

If time permits I will try to build from source.

**Comment by biddrafter** [comment] 2015-05-07 23:22
I was able to build a git clone using make on the first try. I ran the program from the build directory. Same error.

**Comment by biddrafter** [comment] 2015-05-08 18:29
Tried again this morning with linux mint 17 and a fresh package install of pgloader 3.2.0. Same error.

**Comment by dimitri** [comment] 2015-05-08 21:39
I can't remember tonight if the exact package is `openssl` or `openssl-devel`, so you might want to try with `openssl-devel` just in case.

**Comment by biddrafter** [comment] 2015-05-08 22:16
Thanks for the reply. I added the libssl-dev and rebuilt. Same error was returned.

**Comment by DavidPerezIngeniero** [comment] 2015-07-10 07:41
I'm using Kubuntu 15.04 64 bits and same error.

**Comment by DavidPerezIngeniero** [comment] 2015-07-10 08:22
Confirmed that when building from source, I'm getting the same error.

**Comment by dimitri** [comment] 2015-07-10 08:40
I just had a doubt and launched my Cloud VM instance running MS SQL again, and ran my test case against it, and it just ran without any glitch, so it's not the mssql connection handling at fault here.

Any of you guys might have more detailed logs about the problem?

**Comment by deepy** [comment] 2015-08-30 16:33
debian jessie with pgloader 3.2.0 from testing, same issue.
mssql 2005 to pg 9.4.3

**Comment by dimitri** [comment] 2015-08-30 17:35
Full pgloader --debug logs, strace output, `ldd /usr/bin/pgloader`, anything that might help... You could also try adding `apt.postgresql.org` to your source list so that you have a pgloader binary built for jessie, too.

**Comment by deepy** [comment] 2015-08-30 19:17
Here's the full --debug logs, not sure how helpful they will be:
```
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
An unhandled error condition has been signalled:
   Undefined alien: "SSL_get_version"

Date/time: 2015-08-30-21:14An unhandled error condition has been signalled:
                              Undefined alien: "SSL_get_version"


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1008D966C3}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100932108B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100932105B}>)
3: (PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002A5A33}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002A5A33}>)
5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<SB-KERNEL:UNDEFINED-ALIEN-STYLE-WARNING {100924DDF3}> :OUTPUT #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002A5A33}> :IF-EXISTS :APPEND :VERBOSE T)
6: (SIGNAL #<SB-KERNEL:UNDEFINED-ALIEN-STYLE-WARNING {100924DDF3}>)
7: (WARN SB-KERNEL:UNDEFINED-ALIEN-STYLE-WARNING :SYMBOL "SSL_get_version")
8: (SB-SYS:ENSURE-DYNAMIC-FOREIGN-SYMBOL-ADDRESS "SSL_get_version" NIL)
9: ((FLET SB-THREAD::WITH-RECURSIVE-SYSTEM-LOCK-THUNK :IN SB-SYS:UPDATE-LINKAGE-TABLE))
10: ((FLET #:WITHOUT-INTERRUPTS-BODY-717 :IN SB-THREAD::CALL-WITH-RECURSIVE-SYSTEM-LOCK))
11: (SB-THREAD::CALL-WITH-RECURSIVE-SYSTEM-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-SYSTEM-LOCK-THUNK :IN SB-SYS:UPDATE-LINKAGE-TABLE) {7FFFF6CA6FDB}> #<SB-THREAD:MUTEX "hash-table lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {1008D966C3}>>)
12: (SB-SYS:UPDATE-LINKAGE-TABLE)
13: ((FLET #:WITHOUT-INTERRUPTS-BODY-647 :IN SB-THREAD::CALL-WITH-MUTEX))
14: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN LOAD-SHARED-OBJECT) {7FFFF6CA71CB}> #<SB-THREAD:MUTEX "shared object list lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {1008D966C3}>> NIL T NIL)
15: (LOAD-SHARED-OBJECT "libsybdb.so" :DONT-SAVE NIL)
16: (CFFI::LOAD-FOREIGN-LIBRARY-PATH MSSQL::SYBDB "libsybdb.so" NIL)
17: ((FLET CFFI::%DO-LOAD :IN CFFI::%DO-LOAD-FOREIGN-LIBRARY) #<CFFI:FOREIGN-LIBRARY SYBDB "libsybdb.so"> MSSQL::SYBDB "libsybdb.so")
18: (CFFI:LOAD-FOREIGN-LIBRARY MSSQL::SYBDB :SEARCH-PATH NIL)
19: ((LAMBDA ()))
20: (PGLOADER:RUN-COMMANDS (LAMBDA NIL (LET ((*MUFFLED-WARNINGS* (QUOTE STYLE-WARNING))) (CFFI:LOAD-FOREIGN-LIBRARY (QUOTE MSSQL::SYBDB))) (LET* ((PGLOADER.PARSER::STATE-BEFORE (PGLOADER.UTILS:MAKE-PGSTATE)) (PGLOADER.PARAMS:*STATE* (OR PGLOADER.PARAMS:*STATE* (PGLOADER.UTILS:MAKE-PGSTATE))) (PGLOADER.PARSER::STATE-IDX (PGLOADER.UTILS:MAKE-PGSTATE)) (PGLOADER.PARSER::STATE-AFTER (PGLOADER.UTILS:MAKE-PGSTATE)) (PGLOADER.SOURCES:*DEFAULT-CAST-RULES* (QUOTE ((:SOURCE (:TYPE "char") :TARGET (:TYPE #1="text" :DROP-TYPEMOD T)) (:SOURCE (:TYPE "nchar") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "varchar") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "nvarchar") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "xml") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "bit") :TARGET (:TYPE "boolean")) (:SOURCE (:TYPE "uniqueidentifier") :TARGET (:TYPE "uuid") :USING PGLOADER.TRANSFORMS::SQL-SERVER-UNIQUEIDENTIFIER-TO-UUID) (:SOURCE (:TYPE "hierarchyid") :TARGET (:TYPE #2="bytea") :USING PGLOADER.TRANSFORMS::BYTE-VECTOR-TO-BYTEA) (:SOURCE (:TYPE "geography") :TARGET (:TYPE #2#) :USING PGLOADER.TRANSFORMS::BYTE-VECTOR-TO-BYTEA) (:SOURCE (:TYPE "tinyint") :TARGET (:TYPE "smallint")) (:SOURCE (:TYPE #3="float") :TARGET (:TYPE #3#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE #4="real") :TARGET (:TYPE #4#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE "double") :TARGET (:TYPE "double precision") :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE #5="numeric") :TARGET (:TYPE #5#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE "decimal") :TARGET (:TYPE #5#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE "money") :TARGET (:TYPE #5#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE "smallmoney") :TARGET (:TYPE #5#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE "binary") :TARGET (:TYPE #2#) :USING PGLOADER.TRANSFORMS::BYTE-VECTOR-TO-BYTEA) (:SOURCE (:TYPE "varbinary") :TARGET (:TYPE #2#) :USING PGLOADER.TRANSFORMS::BYTE-VECTOR-TO-BYTEA) (:SOURCE (:TYPE "datetime") :TARGET (:TYPE #6="timestamptz")) (:SOURCE (:TYPE "datetime2") :TARGET (:TYPE #6#))))) (PGLOADER.SOURCES:*CAST-RULES* (QUOTE NIL)) (PGLOADER.PARAMS:*PG-SETTINGS* (QUOTE NIL)) (PGLOADER.PGSQL::*PGSQL-RESERVED-KEYWORDS* (PGLOADER.PGSQL:LIST-RESERVED-KEYWORDS #7=#<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://deepy@UNIX:5432/mydb {10090EBE63}>)) (PGLOADER.PARAMS:*COPY-BATCH-ROWS* (OR NIL PGLOADER.PARAMS:*COPY-BATCH-ROWS*)) (PGLOADER.PARAMS:*COPY-BATCH-SIZE* (OR NIL PGLOADER.PARAMS:*COPY-BATCH-SIZE*)) (PGLOADER.PARAMS:*CONCURRENT-BATCHES* (OR NIL PGLOADER.PARAMS:*CONCURRENT-BATCHES*)) (PGLOADER.PARAMS:*IDENTIFIER-CASE* (OR NIL PGLOADER.PARAMS:*IDENTIFIER-CASE*)) (PGLOADER.PARSER::SOURCE (MAKE-INSTANCE (QUOTE PGLOADER.MSSQL:COPY-MSSQL) :TARGET-DB #7# :SOURCE-DB #<PGLOADER.MSSQL:MSSQL-CONNECTION mssql://sa@server:1433/mydb {1008FAAB93}>))) NIL (PGLOADER.SOURCES:COPY-DATABASE PGLOADER.PARSER::SOURCE :STATE-BEFORE PGLOADER.PARSER::STATE-BEFORE :STATE-AFTER PGLOADER.PARSER::STATE-AFTER :STATE-INDEXES PGLOADER.PARSER::STATE-IDX :INCLUDING (QUOTE NIL) :EXCLUDING (QUOTE NIL)) NIL (PGLOADER.UTILS:REPORT-FULL-SUMMARY "Total import time" PGLOADER.PARAMS:*STATE* :BEFORE PGLOADER.PARSER::STATE-BEFORE :FINALLY PGLOADER.PARSER::STATE-AFTER :PARALLEL PGLOADER.PARSER::STATE-IDX))) :START-LOGGER NIL :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
21: ((FLET #:CLEANUP-FUN-281 :IN PGLOADER::MAIN)) [cleanup]
22: (PGLOADER::MAIN ("pgloader" "--debug" "mssql://sa:password@server:1433/mydb" "postgresql:///mydb"))
23: ((LAMBDA NIL :IN "/tmp/buildd/pgloader-3.2.0+dfsg/dumper-2SKVI5f7.lisp"))
24: ((FLET #:WITHOUT-INTERRUPTS-BODY-89 :IN SAVE-LISP-AND-DIE))
25: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))


debugger invoked on a SB-KERNEL:UNDEFINED-ALIEN-STYLE-WARNING in thread
#<THREAD "main thread" RUNNING {1008D966C3}>:
  Undefined alien: "SSL_get_version"

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application


debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1008D966C3}>:
  The value INVOKE-DEBUGGER is not of type SB-DI:FRAME.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application

(SB-DEBUG::FRAME-CALL INVOKE-DEBUGGER :METHOD-FRAME-STYLE :NORMAL :REPLACE-DYNAMIC-EXTENT-OBJECTS NIL)
0[2] 2015-08-30T19:14:10.030000Z NOTICE Starting pgloader, log system is ready.
2015-08-30T19:14:10.046000Z INFO Starting monitor
2015-08-30T19:14:10.051000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2015-08-30T19:14:10.051000Z LOG Data errors in '/tmp/pgloader/'
2015-08-30T19:14:10.051000Z INFO SOURCE: #<PGLOADER.MSSQL:MSSQL-CONNECTION mssql://sa@server:1433/mydb {1008FAAB93}>
2015-08-30T19:14:10.051000Z INFO TARGET: #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://deepy@UNIX:5432/mydb {10090EBE63}>
2015-08-30T19:14:10.051000Z DEBUG LOAD DATA FROM #<PGLOADER.MSSQL:MSSQL-CONNECTION mssql://sa@server:1433/mydb {1008FAAB93}>
2015-08-30T19:14:10.051000Z FATAL We have a situation here.
```

**Comment by dimitri** [comment] 2015-08-30 20:43
Can you try to `apt-get install openssl-dev` and then try again?

**Comment by deepy** [comment] 2015-08-31 06:22
Still the same issue after installing libssl-dev (can't find any openssl-dev)

**Comment by InsidiousForce** [comment] 2016-01-10 07:45
This issue still exists mssql to pgsql. Tried on an Amazon RDS mssql as a source, as well as a local lan mssql server 2012. target is pgsql 9.4 on localhost.

**Comment by InsidiousForce** [comment] 2016-01-10 07:52
As an added point of data I've turned off SSL on the postgres server and there is no change, same error

An unhandled error condition has been signalled:
   Undefined alien: "SSL_get_version"

**Comment by dimitri** [comment] 2016-01-23 19:23
Can you please try the docker image at https://hub.docker.com/r/dimitri/pgloader/ or at least follow the Dockerfile in term of build and runtime dependencies? This error usually means the libssl that was found at build-time isn't found at run-time...

**Comment by deepy** [comment] 2016-01-27 11:07
Running it in dimitri/pgloader nets me:
```
An unhandled error condition has been signalled:
   Undefined alien: "SSL_CTX_set_default_verify_dir"
```

**Comment by dimitri** [comment] 2016-01-28 10:53
Then I'm all lost. Anyone wants to implement a pure-Common-Lisp SSL layer (TLS v1.2 I guess actually)?

**Comment by kadrach** [comment] 2016-02-01 04:13
Running into the same issue, `SSL_CTX_set_default_verify_dir`, trying to move data from a SQL Server to postgresql. Seems to be related to cl-plus-ssl/cl-plus-ssl#33, dimitri/pgloader#330 and dimitri/pgloader#316.

**Comment by dimitri** [comment] 2016-03-28 22:20
I've discarded the trying to be smart hook when building the image, please try again?

**Comment by deepy** [comment] 2016-03-29 08:15
Seems to work for me now :-)
I got it to connect and start the process.

**Comment by dimitri** [comment] 2016-03-29 18:51
Yeah! Closing that issue then, please re-open if needed, as usual.

**Closed by dimitri** 2016-03-29 18:51 UTC
Labels: Build System, Solution unclear

**Comment by ivanguy** [comment] 2016-08-14 00:53
@deepy how plz?
i get 
```An unhandled error condition has been signalled:
   Undefined alien: "SSL_CTX_set_default_verify_dir"```

**Comment by ivanguy** [comment] 2016-08-14 00:59
i fugired out that SSL_CTX_set_default_verify_dir was added in OpenSSL 1.1.0
https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_load_verify_locations.html  - method included
https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_load_verify_locations.html - method absent

my system - Ubuntu 16.04, libssl-dev is 1.0.2 for me

installing openssl from master with checkinstall did not solve the problem

**Comment by ftzdomino** [comment] 2018-09-27 22:05
a workaround for this issue is forcing the older ssl libraries at runtime:
`LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0" /home/you/pgloader/build/bin/pgloader ... `
