### ISSUE TITLE
Simple loading not working

### ISSUE THREAD

**Issue by tacman** [dimitri/pgloader#889] opened 2019-01-17 15:13 UTC
Maybe I don't have everything installed properly, but I can't seem to get a super-basic import working:

```bash
# after running sudo apt install pgloader

pgloader --version
    pgloader version "3.4.1"
    compiled with SBCL 1.3.3.debian

pgloader mysql://news:password@localhost/news_test pgsql:///news@news:n4 --verbose 

KABOOM!
FATAL error: No such file or directory: "mysql://news:password@localhost/news_test"
   No such file or directory: "pgsql:///news@news:n4"
   No such file or directory: "--verbose"
An unhandled error condition has been signalled:
   No such file or directory: "mysql://news:password@localhost/news_test"
   No such file or directory: "pgsql:///news@news:n4"
   No such file or directory: "--verbose"

What I am doing here?

No such file or directory: "mysql://news:password@localhost/news_test"
   No such file or directory: "pgsql:///news@news:n4"
   No such file or directory: "--verbose"
```

I've tried adding --type mysql, putting it in a .load file, putting the parameters in quotes, etc. but nothing is working.

**Comment by dimitri** [comment] 2019-01-17 16:05
Yeah, please put the options before the arguments:

```
pgloader --verbose mysql://news:password@localhost/news_test pgsql:///news@news:n4
```

**Comment by tacman** [comment] 2019-01-17 17:18
Still not getting any useful information about why it's not loading


pgloader --verbose mysql://news:password@localhost/news_test
pgsql:///news@news:n4

2019-01-17T17:16:44.010000Z NOTICE Starting pgloader, log system is ready.

pgloader --debug mysql://news:password@localhost/news_test pgsql:///news@news:n4

tail /tmp/pgloader/pgloader.log
2019-01-17T15:16:46.010000Z NOTICE Starting pgloader, log system is ready.
2019-01-17T15:16:52.010000Z NOTICE Starting pgloader, log system is ready.
2019-01-17T15:17:31.009000Z NOTICE Starting pgloader, log system is ready.
2019-01-17T15:18:30.010000Z NOTICE Starting pgloader, log system is ready.
2019-01-17T15:18:30.018000Z INFO Starting monitor
2019-01-17T15:18:30.020000Z INFO Stopping monitor
2019-01-17T15:18:56.010000Z NOTICE Starting pgloader, log system is ready.
2019-01-17T15:18:56.017000Z INFO Starting monitor
2019-01-17T15:18:56.020000Z INFO Stopping monitor
2019-01-17T17:16:44.010000Z NOTICE Starting pgloader, log system is ready.

**Comment by dimitri** [comment] 2019-05-11 23:14
Please try a more recent pgloader, such as 3.6.1, or built from fresh sources, or the dockerhub container. Closing the issue now.

**Closed by dimitri** 2019-05-11 23:14 UTC

**Comment by pestasoft** [comment] 2019-05-23 14:02
Hello, sorry my english. 
I am the same problem in Ubuntu 18.04.2 LTS
(mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper)
(psql (PostgreSQL) 11.3 (Ubuntu 11.3-1.pgdg18.04+1)


apt version:
pgloader version "3.5.2"
compiled with SBCL 1.4.5.debian

I build latest pgloader from here:
pgloader version "3.6.2~devel"
compiled with SBCL 1.4.5.debian

pgloader --verbose mysql://user:pass@127.0.0.1/sourcedb postgresql:///user:password@127.0.0.1/destdb
2019-05-23T13:56:04.010000Z NOTICE Starting pgloader, log system is ready.
2019-05-23T13:56:04.017000Z LOG pgloader version  3.6.2 devel


tail /tmp/pgloader/pgloader.log:
2019-05-23T13:53:12.010000Z NOTICE Starting pgloader, log system is ready.
2019-05-23T13:53:12.016000Z LOG pgloader version 3.6.2 devel
2019-05-23T13:56:04.010000Z NOTICE Starting pgloader, log system is ready.
2019-05-23T13:56:04.017000Z LOG pgloader version 3.6.2 devel


ldd /usr/bin/pgloader
        linux-vdso.so.1 (0x00007fff36f3b000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2464f09000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2464cea000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2464acd000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f246472f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f246433e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f246510d000)

ldd /compiled/pgloader
        linux-vdso.so.1 (0x00007ffcc7dda000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd79d5cf000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd79d3b0000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd79d193000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd79cdf5000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd79ca04000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd79d7d3000)

**Comment by dimitri** [comment] 2019-05-24 10:07
It's strange. Can you try `--debug` rather than `--verbose` so that we maybe have more information?

**Comment by pestasoft** [comment] 2019-05-24 10:30
with --debug:

pgloader version 3.6.2~devel
compiled with SBCL 1.4.5.debian
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2019-05-24T10:29:48.008000Z NOTICE Starting pgloader, log system is ready.
2019-05-24T10:29:48.025000Z INFO Starting monitor
2019-05-24T10:29:48.027000Z LOG pgloader version "3.6.2~devel"
2019-05-24T10:29:48.027000Z INFO Stopping monitor

**Comment by hsleewis** [comment] 2019-08-19 13:21
I'm using the dockerhub version and I get exactly the same error as tacman in the opening post of this issue.

`~ $ docker run --rm --name pgloader dimitri/pgloader:latest pgloader --verbose mysql://username:password@server postgresql://username:password@server
WARNING:
Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)
Trying to continue anyway.
KABOOM!
FATAL error: No such file or directory: "mysql://username:password@server"
   No such file or directory: "postgresql://username:password@server"
An unhandled error condition has been signalled:
   No such file or directory: "mysql://username:password@server"
   No such file or directory: "postgresql://username:password@server"



2019-08-19T13:20:01.010000Z NOTICE Starting pgloader, log system is ready.
2019-08-19T13:20:01.015000Z LOG pgloader version "3.6.2~devel"

What I am doing here?

No such file or directory: "mysql://username:password@server"
   No such file or directory: "postgresql://username:password@server"
`

**Comment by CDRO** [comment] 2019-12-09 07:40
Hello, I can confirm this behaviour for the docker version, I always get the INFO and NOTICE outputs but nothing happens.

What I'm trying to do is to migrate a database from mysql in a docker instance to a Postgres database in a docker instance, maybe there is some issue?

My output:

> docker run --security-opt seccomp=unconfined \
>            --rm \
>            --name pgloader \
>            dimitri/pgloader:latest pgloader --debug mysql://typo3:typo3@127.0.0.1/typo3 postgresql://typo3:typo3@127.0.0.1/public/typo3
> mkdir -p #P"/tmp/pgloader/"
> pgloader version 3.6.2~devel
> compiled with SBCL 1.3.14.debian
> sb-impl::*default-external-format* :ANSI_X3.4-1968
> tmpdir: #P"/tmp/pgloader/"
> 2019-12-09T07:38:59.020000Z NOTICE Starting pgloader, log system is ready.
> 2019-12-09T07:38:59.029000Z INFO Starting monitor
> 2019-12-09T07:38:59.033000Z LOG pgloader version "3.6.2~devel"
> 2019-12-09T07:38:59.033000Z INFO Stopping monitor

Both users are root for this instance (and for testing), I don't know if that makes any difference.

**Comment by titoshadow** [comment] 2020-01-27 15:27
Helo, hate to do this without adding value, but +1 presenting this issue :\

**Comment by bratekarate** [comment] 2020-06-02 21:44
I'm having the same issue. Is it not possible to debug further? It used to work flawlessly before, but it now fails with this weird error message. No information whatsoever. Host is found with ping, database is running, what could be wrong?

I know that it is probably hard to trace back this error, but we really need some more information. Is the URL not found? Could it be permissions? `--debug` says the following:

```
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006385B3}>
0: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {1005CFF463}>)
1: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<PGLOADER::LOAD-FILES-NOT-FOUND-ERROR {1005CFF313}> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL)
2: ((FLET "H0" :IN PGLOADER::MAIN) #<PGLOADER::LOAD-FILES-NOT-FOUND-ERROR {1005CFF313}>)
3: (SB-KERNEL::%SIGNAL #<PGLOADER::LOAD-FILES-NOT-FOUND-ERROR {1005CFF313}>)
4: (ERROR PGLOADER::LOAD-FILES-NOT-FOUND-ERROR :FILENAME-LIST ("mysql://root:admin@mysql_propart/proPart" "pgsql://admin:admin@postgres_vertrag/vertragsservice"))
5: (PGLOADER::PROCESS-COMMAND-FILE ("mysql://root:admin@mysql_propart/proPart" "pgsql://admin:admin@postgres_vertrag/vertragsservice") :FLUSH-SUMMARY T)
6: (PGLOADER::PROCESS-SOURCE-AND-TARGET "mysql://root:admin@mysql_propart/proPart" "pgsql://admin:admin@postgres_vertrag/vertragsservice" NIL NIL NIL NIL NIL NIL NIL NIL)
7: (PGLOADER.MONITOR::CALL-WITH-MONITOR #<CLOSURE (LAMBDA NIL :IN PGLOADER::MAIN) {1005AF572B}>)
8: (PGLOADER::MAIN ("pgloader" "--debug" "mysql://root:admin@mysql_propart/proPart" "pgsql://admin:admin@postgres_vertrag/vertragsservice"))
9: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
11: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))
```
Still just talking about not finding load files, not helpful.

I mean, if it does not find the URL (or whatever the issue is), is there no way to find out why pgloader not connects? If any other application can connect to my postgres and mysql containers with the same URL, there must be something funny going on within the pgloader container.
