### ISSUE TITLE
Failed to find target table for source

### ISSUE THREAD

**Issue by denis-ivanov** [dimitri/pgloader#763] opened 2018-03-15 06:57 UTC
- [ ] pgloader --version
  
```
pgloader version "3.3.2"
compiled with SBCL 1.3.14.debian
```
  
  - [ ] did you test a fresh compile from the source tree?
    
From debian repository
    
  - [ ] did you search for other similar issues?
I didn't found similar issues.
    
  - [ ] how can I reproduce the bug?

MSSQL Server database

```sql
CREATE DATABASE Example;

CREATE TABLE dbo.Test
(
  Id INT PRIMARY KEY IDENTITY (1, 1),
  Value NVARCHAR(50) NOT NULL
);

INSERT INTO dbo.Test (Value) VALUES (N'Simple test');
```

PostgreSQL database

```sql
CREATE DATABASE "Example";

CREATE TABLE public."Test"
(
  Id SERIAL PRIMARY KEY,
  Value VARCHAR(50) NOT NULL
);
```

```
LOAD DATABASE
	FROM mssql://pgloader:123@dev/Example
	INTO postgresql://postgres:123@localhost:5432/Example

ALTER SCHEMA 'dbo' RENAME TO 'public'

WITH
	create no tables,
	create no indexes,
	create no indexes,
	include no drop,
	quote identifiers,
	data only,
	no foreign keys

including only table names like 'Test' in schema 'dbo'

SET
	work_mem             to '16MB',
	maintenance_work_mem to '512 MB'
;
```

  - [ ] pgloader output you obtain
  
```
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2018-03-15T06:55:50.037000Z NOTICE Starting pgloader, log system is ready.
2018-03-15T06:55:50.056000Z INFO Starting monitor
2018-03-15T06:55:50.061000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2018-03-15T06:55:50.062000Z LOG Data errors in '/tmp/pgloader/'
2018-03-15T06:55:50.062000Z LOG Parsing commands from file #P"/mnt/e/import.load"
2018-03-15T06:55:50.263000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@localhost:5432/Example {1005C51303}>
2018-03-15T06:55:50.264000Z DEBUG SET client_encoding TO 'utf8'
2018-03-15T06:55:50.264000Z DEBUG SET work_mem TO '16MB'
2018-03-15T06:55:50.265000Z DEBUG SET maintenance_work_mem TO '512 MB'
2018-03-15T06:55:50.265000Z DEBUG SET application_name TO 'pgloader'
Max connections reached, increase value of TDS_MAX_CONN
2018-03-15T06:55:50.666000Z DEBUG MSSQL: sending query:
  select c.table_schema,
         c.table_name,
         c.column_name,
         c.data_type,
         CASE
         WHEN c.column_default LIKE '((%' AND c.column_default LIKE '%))' THEN
             CASE
                 WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) = 'newid()' THEN 'generate_uuid_v4()'
                 WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) LIKE 'convert(%varchar%,getdate(),%)' THEN 'today'
                 WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) = 'getdate()' THEN 'now'
                 WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) LIKE '''%''' THEN SUBSTRING(c.column_default,4,len(c.column_default)-6)
                 ELSE SUBSTRING(c.column_default,3,len(c.column_default)-4)
             END
         WHEN c.column_default LIKE '(%' AND c.column_default LIKE '%)' THEN
             CASE
                 WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) = 'newid()' THEN 'generate_uuid_v4()'
                 WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) LIKE 'convert(%varchar%,getdate(),%)' THEN 'today'
                 WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) = 'getdate()' THEN 'now'
                 WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) LIKE '''%''' THEN SUBSTRING(c.column_default,3,len(c.column_default)-4)
                 ELSE SUBSTRING(c.column_default,2,len(c.column_default)-2)
             END
         ELSE c.column_default
         END,
         c.is_nullable,
         COLUMNPROPERTY(object_id(c.table_name), c.column_name, 'IsIdentity'),
         c.CHARACTER_MAXIMUM_LENGTH,
         c.NUMERIC_PRECISION,
         c.NUMERIC_PRECISION_RADIX,
         c.NUMERIC_SCALE,
         c.DATETIME_PRECISION,
         c.CHARACTER_SET_NAME,
         c.COLLATION_NAME

    from information_schema.columns c
         join information_schema.tables t
              on c.table_schema = t.table_schema
             and c.table_name = t.table_name

   where     c.table_catalog = 'Example'
         and t.table_type = 'BASE TABLE'
         and ((c.table_schema = 'dbo' and c.table_name LIKE 'Test'))


order by c.table_schema, c.table_name, c.ordinal_position
2018-03-15T06:55:50.872000Z INFO CAST Test.Id int [NIL, NOT NULL, auto_increment] TO "\"Id\" bigserial not null"
2018-03-15T06:55:50.873000Z INFO CAST Test.Value nvarchar [NIL, NOT NULL, NIL] TO "\"Value\" text not null"
2018-03-15T06:55:50.873000Z NOTICE CREATE TABLES
2018-03-15T06:55:50.873000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@localhost:5432/Example {1005C51303}>
2018-03-15T06:55:50.874000Z DEBUG SET client_encoding TO 'utf8'
2018-03-15T06:55:50.874000Z DEBUG SET work_mem TO '16MB'
2018-03-15T06:55:50.875000Z DEBUG SET maintenance_work_mem TO '512 MB'
2018-03-15T06:55:50.876000Z DEBUG SET application_name TO 'pgloader'
2018-03-15T06:55:50.876000Z DEBUG BEGIN
2018-03-15T06:55:51.077000Z DEBUG fetch-pgsql-catalog: 1 tables, 1 indexes, 0+0 fkeys
2018-03-15T06:55:51.078000Z ERROR pgloader failed to find target table for source "dbo"."Test" with name "\"Test\"" in target catalog
2018-03-15T06:55:51.078000Z LOG Skipping public."Test"
2018-03-15T06:55:51.080000Z NOTICE Reset sequences
2018-03-15T06:55:51.080000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@localhost:5432/Example {100860D163}>
2018-03-15T06:55:51.081000Z DEBUG SET client_encoding TO 'utf8'
2018-03-15T06:55:51.081000Z DEBUG SET work_mem TO '16MB'
2018-03-15T06:55:51.082000Z DEBUG SET maintenance_work_mem TO '512 MB'
2018-03-15T06:55:51.082000Z DEBUG SET application_name TO 'pgloader'
2018-03-15T06:55:51.083000Z DEBUG SET client_encoding TO 'utf8'
2018-03-15T06:55:51.083000Z DEBUG SET work_mem TO '16MB'
2018-03-15T06:55:51.084000Z DEBUG SET maintenance_work_mem TO '512 MB'
2018-03-15T06:55:51.085000Z DEBUG SET application_name TO 'pgloader'
2018-03-15T06:55:51.085000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@localhost:5432/Example {100861DC73}>
2018-03-15T06:55:51.086000Z DEBUG SET client_encoding TO 'utf8'
2018-03-15T06:55:51.086000Z DEBUG SET work_mem TO '16MB'
2018-03-15T06:55:51.092000Z DEBUG SET maintenance_work_mem TO '512 MB'
2018-03-15T06:55:51.097000Z DEBUG SET application_name TO 'pgloader'
             table name       read   imported     errors      total time       read      write
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
        fetch meta data          1          1          0          0.472s
           Drop Indexes          0          0          0          0.000s
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
COPY Threads Completion          0          0          0          0.000s
        Reset Sequences          0          1          0          0.077s
       Install Comments          0          0          0          0.000s
```

**Comment by dimitri** [comment] 2018-03-16 15:48
I believe this bug has been fixed in https://github.com/dimitri/pgloader/commit/6964764fb4b31cbb06c016afe6c5762ed4d9fba5#diff-60cee6f6d0fefab23f385dcf1560fea5 ; so please try compiling pgloader from sources, then it should just work.

**Comment by denis-ivanov** [comment] 2018-03-19 09:24
I tried to build pgloader on debian and got this error
```
KABOOM!
FATAL error: Undefined alien: "SSLv3_client_method"
An unhandled error condition has been signalled:
   Undefined alien: "SSLv3_client_method"




What I am doing here?

Undefined alien: "SSLv3_client_method"
```

**Comment by CaCTuCaTu4ECKuu** [comment] 2018-12-17 01:59
Is it OK? Error Undefined alien: SSLv3_client_method? Why did author cut SSL compability?

**Comment by grav** [comment] 2019-01-04 10:10
Any news on this issue?

**Comment by CaCTuCaTu4ECKuu** [comment] 2019-01-04 12:14
I decided not to use this project, it's not working for secured connections and while I was trying to solve issue need for transfering data became unreasonable.
Also I think this may work for local MS DB Instance without security configured.
I had this issue with old version of Xubuntu somewhen in past, but updating it was easier than updating docker image with pgloader.

**Comment by grav** [comment] 2019-01-04 21:22
@CaCTuCaTu4ECKuu It works perfectly from our production MSSQL running SSL, albeit only if we run `pgloader` from a Mac which is problematic for us.

A bit more info - I can get a working connection if I follow this recipe from another issue, which uses v3.4.1:
https://github.com/dimitri/pgloader/issues/807#issuecomment-396838106

What this tells me is that the issue is not necessarily a problem with freetds or the SSL version of the Docker image, but some kind of configuration in the pgloader application itself.

(Version 3.4.1 is not a solution for us, since, as the OP, we need the most recent version of pgloader).

**Comment by CaCTuCaTu4ECKuu** [comment] 2019-01-04 23:04
I'm using Windows and Mac is not a option. I used to intall things from comment inti container but this didnt help, Furthermore the SSL issue is only part of the problem. I tried if it works at all and I cant even make it to accept "INCLUDE" or "EXCLUDE" tables command. It always show the error that i have had to write another command or missing something no matter where i put it. I googled so hard and didnt find any info about that problem so no, no way i'm using it. I'l better write manual script and it instead...

**Comment by dimitri** [comment] 2019-01-07 19:13
Please try version 3.6.0 as in 
https://github.com/dimitri/pgloader/releases/tag/v3.6.0, I have had user reports indicating that it should work better with respect to SSL. Also, although I'm not using windows myself, pgloader should work on this OS. Feel free to try and compile it there.

**Comment by grav** [comment] 2019-01-07 20:30
@dimitri v3.6.0 is already tried on my part with no success when using it from Linux. From Mac, it works perfectly.

**Comment by dimitri** [comment] 2019-01-07 22:57
@grav : I'm no magician, there's no way I can figure out all by myself and at a distance any clue that would explain why it would work differently on different platforms. Please give details, and make sure to double check you're comparing the same versions of pgloader in both platforms.

**Comment by grav** [comment] 2019-01-08 08:40
@dimitri Sorry, didn't at all mean to imply that you should figure it out :-) I really did ask if you'd like additional information in a comment above :-)

I'll see if I can get the dirty details about the MSSQL Server that we're reading from. And I'll also see if I can reproduce the problem with Microsoft's own SQL Server docker image. I'll get back to you in this thread :-)

**Closed** 2019-05-11 23:42 UTC
