### ISSUE TITLE
Build failing on Centos6 - Ironclad - invalid number of arguments

### ISSUE THREAD

**Issue by tsproull** [dimitri/pgloader#834] opened 2018-09-14 07:23 UTC
When attempting to make pgloader, I'm encountering the following error in the build process.

Centos6 GCP deployment.
Downloading repo, running bootstrap-centos.sh, then making pgloader.

```
Loading "pgloader"
To load "ironclad":
  Load 1 ASDF system:
    asdf
  Install 2 Quicklisp releases:
    ironclad nibbles
; Fetching #<URL "http://beta.quicklisp.org/archive/nibbles/2018-08-31/nibbles-20180831-git.tgz">
; 17.23KB

17,647 bytes in 0.01 seconds (1723.34KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/ironclad/2018-08-31/ironclad-v0.42.tgz">
; 1341.43KB

1,373,627 bytes in 0.14 seconds (9380.65KB/sec)
; Loading "ironclad"
..................................................
[package nibbles].................................
[package ironclad]................................
[package ironclad-vm].............................
.....................
debugger invoked on a SB-INT:SIMPLE-PROGRAM-ERROR in thread
#<THREAD "main thread" RUNNING {100291EC23}>:
  invalid number of arguments: 5
Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "ciphers" "chacha">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "ciphers" "chacha">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "ironclad"
  5:                                 Give up on "pgloader"
  6: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  7:                                 Skip rest of --eval and --load options.
  8:                                 Skip to toplevel READ/EVAL/PRINT loop.
  9: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).
(SB-X86-64-ASM::|movzx| #<SB-ASSEM:SEGMENT :TYPE :REGULAR> #<SB-C::VOP :INFO UB32REF/LE :ARGS #<SB-C:TN-REF :TN #<SB-C:TN t1[S6]> :WRITE-P NIL :VOP UB32REF/LE> :RESULTS #<SB-C:TN-REF :TN #<SB-C:TN t2[RAX]> :WRITE-P T :VOP UB32REF/LE>> (:DWORD :QW
ORD) #<SB-C:TN t2[RAX]> #<SB-X86-64-ASM::EA :DWORD base=#<SB-C:TN t3[RAX]> disp=1>) [tl,external]
0] CLER-CONFIGURATION-AND-RETRY
```

**Comment by dimitri** [comment] 2018-10-18 17:09
I'm told that the latest available SBCL fixes the problem here (I believe that would be SBCL 1.4.12, released September 28, 2018). Didn't have try to play around with it yet. Please report success to close the issue, or failure...

**Comment by dimitri** [comment] 2018-11-10 19:52
Current versions of SBCL and Quicklisp projects don't have this problem anymore. At least I can't reproduce. If you still have the problem, please re-open the issue and we'll try to figure it out. Make sure to `make clean` before trying again with an updated version of SBCL.

**Comment by Dzzl7707** [comment] 2018-12-06 17:24
The updated SBCL version does get you past this issue

**Closed** 2018-12-07 12:49 UTC
