### ISSUE TITLE
pgloader  Index 76 out of bound error

### ISSUE THREAD

**Issue by shprabin** [dimitri/pgloader#211] opened 2015-04-19 11:44 UTC
I am trying to migrate mysql(structure and data) to pgsql in windows 32 bit. After loading sakila.load file It says

``` 
Index 76 out of bounds for (SIMPLE-ARRAY (UNSIGNED-BYTE 8)
                             (76)), should be nonnegative and <76.
```

But it creates a schema in postgres database.
Here is my sakila.load file 

```
load database --
from mysql://root@localhost/sakila --
into postgresql://postgres:test@192.168.0.5/sakila -- 
--
WITH include drop, create tables, no truncate, --  
create indexes, reset sequences, foreign keys --  
--
SET maintenance_work_mem to '128MB', work_mem to '12MB', , search_path to 'public' -- 
--
CAST type datetime to timestamptz -- 
drop default drop not null using zero-dates-to-null, --  
type date drop not null drop default using zero-dates-to-null --  
--
--MATERIALIZE VIEWS film_list, staff_list  
--
-- INCLUDING ONLY TABLE NAMES MATCHING ~/film/, 'actor' -- 
-- EXCLUDING TABLE NAMES MATCHING 'test'  --
BEFORE LOAD DO -- 
$$ create schema public; $$;
```

**Comment by dimitri** [comment] 2015-04-19 11:46
Can you give me the full debug logs obtained with the `--debug` switch on the command line? and also what `pgloader --version` is?

**Comment by shprabin** [comment] 2015-04-19 12:04
Hi dimitri, Thanks for quick response. 

pgloader version "3.1.ed853a7"
compiled with SBCL 1.2.1
and debug info is

Below is the debug trace when I removed  search path to 'public'. i still do not get what search_path is for??

C:\Program Files\PostgreSQL\9.1\bin>pgloader.exe --debug  sakila.load
sb-impl::*default-external-format* :CP1252
tmpdir: #P"C:/opscode/chef/embedded/cygwin/c/Users/vagrant/AppData/Local/Temp/pg
loader/"
2015-04-19T12:01:14.043000Z LOG Starting pgloader, log system is ready.
2015-04-19T12:01:14.065000Z INFO Starting monitor
2015-04-19T12:01:14.071000Z LOG Main logs in 'C:/opscode/chef/embedded/cygwin/c/
Users/vagrant/AppData/Local/Temp/pgloader/pgloader.log'
2015-04-19T12:01:14.071000Z LOG Data errors in 'C:/opscode/chef/embedded/cygwin/
c/Users/vagrant/AppData/Local/Temp/pgloader/'
2015-04-19T12:01:14.071000Z LOG Parsing commands from file #P"C:/Program Files/P
ostgreSQL/9.1/bin/sakila.load"
2015-04-19T12:01:14.071000Z DEBUG CONNECT
2015-04-19T12:01:14.071000Z DEBUG SET maintenance_work_mem TO '128MB'
2015-04-19T12:01:14.071000Z DEBUG SET work_mem TO '12MB'
2015-04-19T12:01:14.672000Z DEBUG BEGIN
2015-04-19T12:01:14.872000Z DEBUG CONNECT
2015-04-19T12:01:14.872000Z DEBUG SET maintenance_work_mem TO '128MB'
2015-04-19T12:01:14.872000Z DEBUG SET work_mem TO '12MB'
2015-04-19T12:01:14.872000Z DEBUG BEGIN
2015-04-19T12:01:14.873000Z NOTICE create schema public;
An unhandled error condition has been signalled:
   Index 76 out of bounds for (SIMPLE-ARRAY (UNSIGNED-BYTE 8)
                               (76)), should be nonnegative and <76.

Date/time: 2015-04-19-17:46An unhandled error condition has been signalled:
                              Index 76 out of bounds for (SIMPLE-ARRAY
                                                          (UNSIGNED-BYTE 8)
                                                          (76)), should be nonne
gative and <76.


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {26922589}>
0: (QMYND-IMPL::READ-MY-OCTET #<QMYND-IMPL::MY-PACKET-STREAM 76/76 [1]> NIL #<un
used argument>)
1: (QMYND-IMPL::READ-NULL-TERMINATED-OCTETS #<QMYND-IMPL::MY-PACKET-STREAM 76/76
 [1]> NIL)
2: (QMYND-IMPL::PARSE-INITIAL-HANDSHAKE-V10 #<QMYND-IMPL::MY-PACKET-STREAM 76/76
 [1]>)
3: (QMYND-IMPL:PROCESS-INITIAL-HANDSHAKE-V10 #<QMYND-IMPL::MY-PACKET-STREAM 76/7
6 [1]>)
4: (QMYND-IMPL::MYSQL-CONNECT-DO-HANDSHAKE #<QMYND-IMPL::MYSQL-INET-CONNECTION {
27356679}> "root" NIL "sakila" :COMPRESS NIL :SSL :UNSPECIFIED :SSL-VERIFY NIL)
5: (PGLOADER.MYSQL::FETCH-MYSQL-METADATA :STATE #S(PGLOADER.UTILS::PGSTATE :TABL
ES #<HASH-TABLE :TEST EQUAL :COUNT 2 {26B79BB1}> :TABNAMES ("fetch meta data" "b
efore load") :READ 1 :ROWS 1 :ERRS 0 :SECS 0.036) :MATERIALIZE-VIEWS NIL :ONLY-T
ABLES NIL :INCLUDING NIL :EXCLUDING NIL)
6: ((:METHOD PGLOADER.SOURCES:COPY-DATABASE (PGLOADER.MYSQL:COPY-MYSQL)) #<PGLOA
DER.MYSQL:COPY-MYSQL {27108369}> :STATE-BEFORE #S(PGLOADER.UTILS::PGSTATE :TABLE
S #<HASH-TABLE :TEST EQUAL :COUNT 2 {26B79BB1}> :TABNAMES ("fetch meta data" "be
fore load") :READ 1 :ROWS 1 :ERRS 0 :SECS 0.036) :STATE-AFTER #S(PGLOADER.UTILS:
:PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 0 {26B7A369}> :TABNAMES NIL :RE
AD 0 :ROWS 0 :ERRS 0 :SECS 0.0) :STATE-INDEXES #S(PGLOADER.UTILS::PGSTATE :TABLE
S #<HASH-TABLE :TEST EQUAL :COUNT 0 {26B7A101}> :TABNAMES NIL :READ 0 :ROWS 0 :E
RRS 0 :SECS 0.0) :TRUNCATE NIL :DATA-ONLY NIL :SCHEMA-ONLY NIL :CREATE-TABLES T
:INCLUDE-DROP T :CREATE-INDEXES T :RESET-SEQUENCES T :FOREIGN-KEYS T :IDENTIFIER
-CASE :DOWNCASE :ONLY-TABLES NIL :INCLUDING NIL :EXCLUDING NIL :DECODING-AS NIL
:MATERIALIZE-VIEWS NIL) [fast-method]
7: ((LAMBDA ()))
8: (PGLOADER.PARSER:RUN-COMMANDS #P"C:/Program Files/PostgreSQL/9.1/bin/sakila.l
oad" :START-LOGGER NIL :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLI
ENT-MIN-MESSAGES NIL)
9: ((FLET #:CLEANUP-FUN-248 :IN PGLOADER::MAIN)) [cleanup]
10: (PGLOADER::MAIN ("pgloader.exe" "--debug" "sakila.load"))
11: ((LAMBDA NIL :IN "//vboxsrv/vagrant/dumper-2SKVI5f7.lisp"))
12: ((FLET #:WITHOUT-INTERRUPTS-BODY-75 :IN SAVE-LISP-AND-DIE))
13: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))
14: ("foreign function: #x42AE90")
15: ("foreign function: #x416676")


debugger invoked on a SB-INT:INVALID-ARRAY-INDEX-ERROR in thread
#<THREAD "main thread" RUNNING {26922589}>:
  Index 76 out of bounds for (SIMPLE-ARRAY (UNSIGNED-BYTE 8)
                              (76)), should be nonnegative and <76.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application


debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {26922589}>:
  The value INVOKE-DEBUGGER is not of type SB-DI:FRAME.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application

(SB-DEBUG::FRAME-CALL INVOKE-DEBUGGER :METHOD-FRAME-STYLE :NORMAL :REPLACE-DYNAM
IC-EXTENT-OBJECTS NIL)
0[2] 2015-04-19T12:01:15.073000Z FATAL We have a situation here.

**Comment by dimitri** [comment] 2015-04-19 12:18
For the `search_path`, have a look at http://www.postgresql.org/docs/9.4/static/ddl-schemas.html#DDL-SCHEMAS-PATH.

About your error message, it looks like the MySQL driver in use in pgloader is chocking on the authentication messages, trying to read more than what's in the current buffer, apparently for failing to read the null octet supposed to terminate the message.

Can you tell me which version of MySQL you are using here?

**Comment by shprabin** [comment] 2015-04-20 04:28
Mysql version is 5.5.8

**Comment by dimitri** [comment] 2015-04-20 15:36
I'm not sure what's next. It's clearly a protocol problem... :(

**Comment by shprabin** [comment] 2015-04-21 06:45
Anyways, Thank you for trying to help me out. I appreciate. Will check for other tools.

**Comment by dimitri** [comment] 2016-08-07 13:30
Closing the issue for clean-up and lack of information, please re-open if you can reproduce and have enough details (a reproducible test case) so that we may solve it!

**Closed by dimitri** 2016-08-07 13:30 UTC
Labels: Corner case, Solution unclear
