### ISSUE TITLE
Argument --with "fields terminated by ... "  in command line

### ISSUE THREAD

**Issue by jacques-p** [dimitri/pgloader#298] opened 2015-09-21 12:45 UTC
Hello, 

Preliminary remark : the loading works with a separated command file pgloader_commands.txt  but not  with command line arguments

```
-- pgloader_commands.txt :
LOAD CSV
      FROM './donnees_a_charger.csv' (a, b, c)
      INTO postgresql://anonymous:anonymous@myMachine:5432/myBase?titi(a,b,c)
WITH fields terminated by ','
;
```
-- OK with :
pgloader pgloader_commands.txt

pgloader version "3.2.0"
compiled with SBCL 1.1.14

-- The problem :
-- with a table named titi created as following :
```
psql -h myMachine -d myBase -U anonymous -p 5432
CREATE TABLE titi(a integer, b  real, c varchar);
```

-- a data file named donnees_a_charger.csv :
```
12145001,20.1,tonton est là
12145001,205,titi
```

-- pgloader launched with command line arguments :
```
pgloader --type csv   \
--field a  --field b  --field c           \
--with "fields terminated by ','"         \
--debug --verbose                         \
./donnees_a_charger.csv                   \
postgres://anonymous:anonymous@myMachine:5432/myBase?tablename=titi
```

-- the result :
```
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
An unhandled error condition has been signalled: At

  fields terminated by ','
  ^ (Line 1, Column 0, Position 0)

Could not parse KW-NO. Expected:

     the character Space
  or the character Tab
  or the character Newline
  or the string "--"
  or the string "/*"
  or the string "no", disregarding case

Reached via

     KW-NO
  -> (AND IGNORE-WHITESPACE (~ "no") IGNORE-WHITESPACE)
2015-09-21T12:32:38.033000Z NOTICE Starting pgloader, log system is ready.
2015-09-21T12:32:38.057000Z INFO Starting monitor
2015-09-21T12:32:38.063000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2015-09-21T12:32:38.063000Z LOG Data errors in '/tmp/pgloader/'
  -> "no"

2015-09-21T12:32:38.064000Z INFO SOURCE: #<PGLOADER.CSV:CSV-CONNECTION copy://FILENAME:./donnees_a_charger.csv {1006FAC803}>
2015-09-21T12:32:38.064000Z INFO TARGET: #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://anonymous@myMachine:5432/myBase {10070CC463}>
2015-09-21T12:32:38.064000Z FATAL We have a situation here.
Could not parse WHITESPACE. Expected:

     the character Space
  or the character Tab
  or the character Newline
  or the string "--"
  or the string "/*"

Reached via

     WHITESPACE
  -> (+ (OR Space Tab Newline Newline COMMENTS))
  -> (OR Space Tab Newline Newline COMMENTS)
  -> COMMENTS
  -> (OR SINGLE-LINE-COMMENT MULTI-LINE-COMMENT)
  -> MULTI-LINE-COMMENT
  -> (AND "/*" (+ (NOT "*/")) "*/")
  -> "/*"

Could not parse COPY-OPTION. Expected:

     the string "truncate", disregarding case
  or the string "skip", disregarding case
  or the character Space
  or the character Tab
  or the character Newline
  or the string "--"
  or the string "/*"
  or the string "batch", disregarding case

Reached via

     COPY-OPTION
  -> (OR OPTION-BATCH-ROWS OPTION-BATCH-SIZE OPTION-BATCH-CONCURRENCY
         OPTION-TRUNCATE OPTION-SKIP-HEADER)
  -> OPTION-SKIP-HEADER
  -> (AND KW-SKIP KW-HEADER EQUAL-SIGN (+ (DIGIT-CHAR-P CHARACTER)))
  -> KW-SKIP
  -> (AND IGNORE-WHITESPACE (~ "skip") IGNORE-WHITESPACE)
  -> "skip"

Date/time: 2015-09-21-12:32An unhandled error condition has been signalled: At

  fields terminated by ','
  ^ (Line 1, Column 0, Position 0)

Could not parse KW-NO. Expected:

     the character Space
  or the character Tab
  or the character Newline
  or the string "--"
  or the string "/*"
  or the string "no", disregarding case

Reached via

     KW-NO
  -> (AND IGNORE-WHITESPACE (~ "no") IGNORE-WHITESPACE)
  -> "no"

Could not parse WHITESPACE. Expected:

     the character Space
  or the character Tab
  or the character Newline
  or the string "--"
  or the string "/*"

Reached via

     WHITESPACE
  -> (+ (OR Space Tab Newline Newline COMMENTS))
  -> (OR Space Tab Newline Newline COMMENTS)
  -> COMMENTS
  -> (OR SINGLE-LINE-COMMENT MULTI-LINE-COMMENT)
  -> MULTI-LINE-COMMENT
  -> (AND "/*" (+ (NOT "*/")) "*/")
  -> "/*"

Could not parse COPY-OPTION. Expected:

     the string "truncate", disregarding case
  or the string "skip", disregarding case
  or the character Space
  or the character Tab
  or the character Newline
  or the string "--"
  or the string "/*"
  or the string "batch", disregarding case

Reached via

     COPY-OPTION
  -> (OR OPTION-BATCH-ROWS OPTION-BATCH-SIZE OPTION-BATCH-CONCURRENCY
         OPTION-TRUNCATE OPTION-SKIP-HEADER)
  -> OPTION-SKIP-HEADER
  -> (AND KW-SKIP KW-HEADER EQUAL-SIGN (+ (DIGIT-CHAR-P CHARACTER)))
  -> KW-SKIP
  -> (AND IGNORE-WHITESPACE (~ "skip") IGNORE-WHITESPACE)
  -> "skip"


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1006DB39B3}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {10080CCA0B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {10080CC9DB}>)
3: (PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002CBC13}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002CBC13}>)
5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<ESRAP:ESRAP-PARSE-ERROR @0 (3) {10070DA9D3}> :OUTPUT #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002CBC13}> :IF-EXISTS :APPEND :VERBOSE T)
6: (SIGNAL #<ESRAP:ESRAP-PARSE-ERROR @0 (3) {10070DA9D3}>)
7: (ERROR ESRAP:ESRAP-PARSE-ERROR :TEXT "fields terminated by ','" :POSITION 0 :ATTEMPTS (#<ESRAP::PARSE-ATTEMPT @0 (3) {10070D9273}> #<ESRAP::PARSE-ATTEMPT @0 (8) {10070D9D13}> #<ESRAP::PARSE-ATTEMPT @0 (7) {10070DA883}>))
8: (ESRAP:ESRAP-PARSE-ERROR "fields terminated by ','" 0 (#<ESRAP::PARSE-ATTEMPT @0 (3) {10070D9273}> #<ESRAP::PARSE-ATTEMPT @0 (8) {10070D9D13}> #<ESRAP::PARSE-ATTEMPT @0 (7) {10070DA883}>))
9: (ESRAP::EXPLAIN-FAILED-PARSE #S(ESRAP::FAILED-PARSE :EXPRESSION PGLOADER.PARSER::COPY-OPTION :START 0 :POSITION 0 :DETAIL #S(ESRAP::FAILED-PARSE :EXPRESSION (OR PGLOADER.PARSER::OPTION-BATCH-ROWS PGLOADER.PARSER::OPTION-BATCH-SIZE PGLOADER.PARSER::OPTION-BATCH-CONCURRENCY PGLOADER.PARSER::OPTION-TRUNCATE PGLOADER.PARSER::OPTION-SKIP-HEADER) :START 0 :POSITION 0 :DETAIL (#S(ESRAP::FAILED-PARSE :EXPRESSION PGLOADER.PARSER::OPTION-SKIP-HEADER :START 0 :POSITION 0 :DETAIL #S(ESRAP::FAILED-PARSE :EXPRESSION (AND PGLOADER.PARSER::KW-SKIP PGLOADER.PARSER::KW-HEADER PGLOADER.PARSER::EQUAL-SIGN (+ (DIGIT-CHAR-P CHARACTER))) :START 0 :POSITION 0 :DETAIL #S(ESRAP::FAILED-PARSE :EXPRESSION PGLOADER.PARSER::KW-SKIP :START 0 :POSITION 0 :DETAIL #S(ESRAP::FAILED-PARSE :EXPRESSION (AND PGLOADER.PARSER::IGNORE-WHITESPACE (ESRAP:~ #1="skip") PGLOADER.PARSER::IGNORE-WHITESPACE) :START 0 :POSITION 0 :DETAIL #S(ESRAP::FAILED-PARSE :EXPRESSION #1# :START 0 :POSITION 0 :DETAIL NIL))))) #S(ESRAP::FAILED-PARSE :EXPRESSION PGLOADER.PARSER::OPTION-TRUNCATE :START 0 :POSITION 0 :DETAIL #S(ESRAP::FAILED-PARSE :EXPRESSION (AND (ESRAP:? PGLOADER.PARSER::KW-NO) PGLOADER.PARSER::KW-TRUNCATE) :START 0 :POSITION 0 :DETAIL #S(ESRAP::FAILED-PARSE :EXPRESSION PGLOADER.PARSER::KW-TRUNCATE :START 0 :POSITION 0 :DETAIL #S(ESRAP::FAILED-PARSE :EXPRESSION (AND PGLOADER.PARSER::IGNORE-WHITESPACE (ESRAP:~ #2="truncate") PGLOADER.PARSER::IGNORE-WHITESPACE) :START 0 :POSITION 0 :DETAIL #S(ESRAP::FAILED-PARSE :EXPRESSION #2# :START 0 :POSITION 0 :DETAIL NIL))))) #S(ESRAP::FAILED-PARSE :EXPRESSION PGLOADER.PARSER::OPTION-BATCH-CONCURRENCY :START 0 :POSITION 0 :DETAIL #S(ESRAP::FAILED-PARSE :EXPRESSION (AND PGLOADER.PARSER::KW-BATCH PGLOADER.PARSER::KW-CONCURRENCY PGLOADER.PARSER::EQUAL-SIGN #3=(+ (DIGIT-CHAR-P CHARACTER))) :START 0 :POSITION 0 :DETAIL #4=#S(ESRAP::FAILED-PARSE :EXPRESSION PGLOADER.PARSER::KW-BATCH :START 0 :POSITION 0 :DETAIL #S(ESRAP::FAILED-PARSE :EXPRESSION (AND PGLOADER.PARSER::IGNORE-WHITESPACE (ESRAP:~ #5="batch") PGLOADER.PARSER::IGNORE-WHITESPACE) :START 0 :POSITION 0 :DETAIL #S(ESRAP::FAILED-PARSE :EXPRESSION #5# :START 0 :POSITION 0 :DETAIL NIL))))) #S(ESRAP::FAILED-PARSE :EXPRESSION PGLOADER.PARSER::OPTION-BATCH-SIZE :START 0 :POSITION 0 :DETAIL #S(ESRAP::FAILED-PARSE :EXPRESSION (AND PGLOADER.PARSER::KW-BATCH PGLOADER.PARSER::KW-SIZE PGLOADER.PARSER::EQUAL-SIGN PGLOADER.PARSER::BATCH-SIZE) :START 0 :POSITION 0 :DETAIL #4#)) #S(ESRAP::FAILED-PARSE :EXPRESSION PGLOADER.PARSER::OPTION-BATCH-ROWS :START 0 :POSITION 0 :DETAIL #S(ESRAP::FAILED-PARSE :EXPRESSION (AND PGLOADER.PARSER::KW-BATCH PGLOADER.PARSER::KW-ROWS PGLOADER.PARSER::EQUAL-SIGN #3#) :START 0 :POSITION 0 :DETAIL #4#))))) "fields terminated by ','" NIL)
10: (ESRAP:PARSE PGLOADER.PARSER::COPY-OPTION "fields terminated by ','" :START 0 :END NIL :JUNK-ALLOWED NIL)
11: (PGLOADER.PARSER:PARSE-CLI-OPTIONS :COPY ("fields terminated by ','"))
12: ((FLET #:CLEANUP-FUN-281 :IN PGLOADER::MAIN)) [cleanup]
13: (PGLOADER::MAIN ("pgloader" "--type" "csv" "--field" "a" "--field" "b" "--field" "c" "--with" "fields terminated by ','" "--debug" "--verbose" "./donnees_a_charger.csv" "postgres://anonymous:anonymous@myMachine:5432/myBase?tablename=titi"))
14: ((LAMBDA NIL :IN "/home/vagrant/rpmbuild/BUILD/pgloader/dumper-2SKVI5f7.lisp"))
15: ((FLET #:WITHOUT-INTERRUPTS-BODY-54 :IN SAVE-LISP-AND-DIE))
16: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

...
```

**Comment by dimitri** [comment] 2015-09-21 13:30
With current code I can't reproduce the problem, please build from current source (git clone) and try again.

```
LANG=utf-8 ./build/bin/pgloader --type csv   \
--field a  --field b  --field c           \
--with "fields terminated by ','"         \
--debug --verbose                         \
../temp/298.csv  pgsql:///pgloader?titi
```

**Comment by ohadle** [comment] 2015-12-09 11:04
I've been seeing the same problem (running latest master 72e7c2af7024df89e743405232e8aaca9b6e2a19). This works:

```
 LOAD CSV
	FROM '/media/sf_Data/csv/1048.csv'
	INTO postgresql://myuser:mypass@1.2.3.4:5432/db?tablename=s.t
	WITH fields terminated by ',',
		 skip header = 1
;
```

But this doesn't:
```
./build/bin/pgloader -v --with "fields terminated by ','" --with "skip header = 1" /media/sf_Data/csv/1048.csv "postgresql://myuser:mypass@1.2.3.4:5432/db?tablename=s.t"
```

I also tried adding `--with "csv header" `, but in both cases I get:
```
This data source requires fields definitions.
```

I might add that I couldn't get `csv header` to work in the file either, but that may be a separate issue.

**Comment by dimitri** [comment] 2015-12-09 15:59
The CSV source type requires being given a list of field names. It may find this list in the first line of the CSV file when you use the `WITH csv header` option, but here you didn't...

**Comment by ohadle** [comment] 2015-12-10 11:36
@dimitri thanks for the quick response! And all your work of course :)

If the field names were missing, the config file option shouldn't have worked, but it did. I assumed the field names were found when I stated `fields terminated by ','`. The only difference as far as I can tell was running the commands with a config file and running the same commands as CLI args.

A different issue is that I couldn't get `csv header` to compile at all, whether via config or CLI. Here's the config file I used (should I open a separate issue?):
```
➜  csv  cat pgloader_defs.pgload              
LOAD CSV
	FROM '/media/sf_Data/csv/1048.csv'
	INTO  postgresql://myuser:mypass@1.2.3.4:5432/db?tablename=s.t
	WITH fields terminated by ',',
		 skip header = 1,
		 csv header
;
➜  csv  pgloader -v pgloader_defs.pgload
An unhandled error condition has been signalled: At

  LOAD CSV
  ^ (Line 1, Column 0, Position 0)

Could not parse subexpression ";" when parsing

 Expression PGLOADER.PARSER::COMMANDS
    Subexpression (+ PGLOADER.PARSER::COMMAND)
    Subexpression PGLOADER.PARSER::COMMAND
    Subexpression (AND
                   (OR PGLOADER.PARSER::LOAD-ARCHIVE
                       PGLOADER.PARSER::LOAD-CSV-FILE
                       PGLOADER.PARSER::LOAD-FIXED-COLS-FILE
                       PGLOADER.PARSER::LOAD-COPY-FILE
                       PGLOADER.PARSER::LOAD-DBF-FILE
                       PGLOADER.PARSER::LOAD-IXF-FILE
                       PGLOADER.PARSER::LOAD-MYSQL-DATABASE
                       PGLOADER.PARSER::LOAD-MSSQL-DATABASE
                       PGLOADER.PARSER::LOAD-SQLITE-DATABASE)
                   PGLOADER.PARSER::END-OF-COMMAND)
    Subexpression PGLOADER.PARSER::END-OF-COMMAND
    Subexpression (AND PGLOADER.PARSER::IGNORE-WHITESPACE #\;
                       PGLOADER.PARSER::IGNORE-WHITESPACE)
    Subexpression ";"

; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
```

**Comment by dimitri** [comment] 2016-01-07 18:08
Please consider upgrading, here your input file parses correctly...

**Comment by dimitri** [comment] 2016-01-07 18:19
Closing to clean-up the issue list, if still having the problem please re-open the issue!

**Closed by dimitri** 2016-01-07 18:19 UTC
