### ISSUE TITLE
inet type from mysql char(39)

### ISSUE THREAD

**Issue by Naddiseo** [dimitri/pgloader#271] opened 2015-08-08 00:14 UTC
I'm trying to do a migration of a django app which has a couple models with a `GenericIPAddressField`. On mysql these are reprsented as `char(39)` and on postgres they are `inet`. 
How would I write the config file so that they are correctly casted?

My current attempt looks like:
```
LOAD DATABASE
    FROM mysql://user:password@host/db
    INTO postgresql://user:password@host/db
CAST 
	column table1.ip_address to inet keep not null drop typemod,
	column table2.ip_address to inet keep not null drop typemod,
	column table3.ip_address to inet drop typemod
; 
```
Unfortunately, the resulting tables are using `character varying(39)`

**Comment by dimitri** [comment] 2015-08-10 17:07
It looks like it should work really, will try to reproduce locally and fix what I find. Might only be able to do that next month (holidays and all).

**Comment by dimitri** [comment] 2015-08-24 14:43
I just tested here with the following MySQL definition, and the following cast command:

    column ip.ip_address to inet keep not null drop type mod


```
show create table ip;
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                    |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ip    | CREATE TABLE `ip` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ip_address` varchar(39) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

And here's the table definition I obtain in PostgreSQL:

```
                           Table "public.ip"
   Column   |  Type  |                    Modifiers                    
------------+--------+-------------------------------------------------
 id         | bigint | not null default nextval('ip_id_seq'::regclass)
 ip_address | inet   | 
Indexes:
    "idx_1106167_primary" PRIMARY KEY, btree (id)
```

The example data set migrated correctly too.

**Comment by dimitri** [comment] 2015-08-24 14:43
Closing here, if necessary feel free to open again with more details.

**Closed by dimitri** 2015-08-24 14:43 UTC
Labels: Must Fix
