### ISSUE TITLE
Failed to find target table for source NIL."XXXXX" with name "\"XXXXX\"" in target catalog

### ISSUE THREAD

**Issue by jouir** [dimitri/pgloader#501] opened 2017-01-04 08:51 UTC
I have the following table in a `pgloader` MySQL database (source):
```
CREATE TABLE `_pgloader_test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `offer` varchar(32) NOT NULL,
  `todoDate` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  KEY `offer` (`offer`)
) ENGINE=MyISAM AUTO_INCREMENT=219040847 DEFAULT CHARSET=latin1
```

And the following table in the `dbpg` PostgreSQL database (destination):
```
CREATE TYPE "public"."_pgloader_test_offer_enum" AS ENUM('value1', 'value2');

CREATE TABLE "public"."_pgloader_test" (
    "id"            bigserial primary key,
    "offer"         _pgloader_test_offer_enum not null,
    "todoDate"      timestamptz
);
CREATE INDEX ON "public"."_pgloader_test" ("offer");
CREATE INDEX ON "public"."_pgloader_test" ("todoDate");
```
Definition:
```
# \d _pgloader_test
                                   Table "public._pgloader_test"
  Column  |           Type            |                          Modifiers                          
----------+---------------------------+-------------------------------------------------------------
 id       | bigint                    | not null default nextval('_pgloader_test_id_seq'::regclass)
 offer    | _pgloader_test_offer_enum | not null
 todoDate | timestamp with time zone  | 
Indexes:
    "_pgloader_test_pkey" PRIMARY KEY, btree (id)
    "_pgloader_test_offer_idx" btree (offer)
    "_pgloader_test_todoDate_idx" btree ("todoDate")
```

There are others tables in the source database so we are using the `INCLUDING ONLY TABLE NAMES MATCHING` filter.

Here is the pgloader file we use:
```
LOAD DATABASE
        from mysql://pgloader:XXXXX@10.XXX.XXX.XXX:XXXXX/pgloader
        into postgresql://pgloader:XXXXX@10.XXX.XXX.XXX:XXXXX/dbpg

WITH    include no drop,
        create no tables,
        create no indexes,
        reset sequences,
        quote identifiers,
        batch rows = 10000,
        batch concurrency = 1
 
SET     maintenance_work_mem to '1GB', work_mem to '16MB'

CAST    type varchar drop not null using empty-string-to-null

INCLUDING ONLY TABLE NAMES MATCHING
    '_pgloader_test'
;
```
This leads to the following error message:
```
$ pgloader test.load 
2017-01-04T08:26:44.078000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2017-01-04T08:26:44.087000Z LOG Data errors in '/tmp/pgloader/'
2017-01-04T08:26:44.087000Z LOG Parsing commands from file #P"/var/lib/postgresql/test.load"
2017-01-04T08:26:44.488000Z ERROR pgloader failed to find target table for source NIL."_pgloader_test" with name "\"_pgloader_test\"" in target catalog
2017-01-04T08:26:44.489000Z LOG Skipping "_pgloader_test"
             table name       read   imported     errors      total time       read      write
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
        fetch meta data          1          1          0          0.151s                     
      Drop Foreign Keys          0          0          0          0.000s                     
           Drop Indexes          0          0          0          0.000s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
COPY Threads Completion          0          0          0          0.000s                     
        Reset Sequences          0         21          0          0.032s                     
           Primary Keys          1          1          0          0.000s                     
    Create Foreign Keys          0          0          0          0.000s                     
       Install Comments          0          0          0          0.000s
```
The workaround is to rename the table with the same name:
```
...
INCLUDING ONLY TABLE NAMES MATCHING
    '_pgloader_test'

ALTER TABLE NAMES MATCHING '_pgloader_test' RENAME TO '_pgloader_test'
;
```
I don't know why pgloader doesn't seems to find the target table. Do I misconfigured something?

This leads to another error:
```
$ pgloader test.load 
2017-01-04T08:28:34.077000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2017-01-04T08:28:34.085000Z LOG Data errors in '/tmp/pgloader/'
2017-01-04T08:28:34.086000Z LOG Parsing commands from file #P"/var/lib/postgresql/test.load"
2017-01-04T08:28:34.487000Z WARNING Source column "public"."_pgloader_test"."\"offer\"" is casted to type "varchar" which is not the same as "_pgloader_test_offer_enum", the type of current target database column "\"public\""."\"_pgloader_test\""."offer".
2017-01-04T08:28:34.488000Z ERROR Database error 42704: index "_pgloader_test_tododate_idx" does not exist
QUERY: DROP INDEX "public"._pgloader_test_todoDate_idx;
2017-01-04T08:28:34.488000Z FATAL Failed to create the schema, see above.
       table name       read   imported     errors      total time       read      write
-----------------  ---------  ---------  ---------  --------------  ---------  ---------
  fetch meta data          1          1          0          0.168s                     
Drop Foreign Keys          0          0          0          0.000s                     
     Drop Indexes          0          0          0          0.000s                     
-----------------  ---------  ---------  ---------  --------------  ---------  ---------
```
I understand the first error where I'm trying to cast a varchar into an enum without casting option but the second error related to a missing index is disturbing. I'm using the `WITH quote identifiers` option that should surround the index name with quote. As you can see in the destination table definition, the index is there with a case sensitive name. Finaly, why pgloader is trying to drop this index with the `WITH include no drop` option? Adding a `WITH data only` option doesn't solve this problem.

Here are the debug messages :
```
$ pgloader -d test.load 
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2017-01-04T08:37:22.046000Z NOTICE Starting pgloader, log system is ready.
2017-01-04T08:37:22.078000Z INFO Starting monitor
2017-01-04T08:37:22.089000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2017-01-04T08:37:22.090000Z LOG Data errors in '/tmp/pgloader/'
2017-01-04T08:37:22.090000Z LOG Parsing commands from file #P"/var/lib/postgresql/test.load"
2017-01-04T08:37:22.090000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://pgloader@10.XXX.XXX.XXX:XXXXX/dbpg {10096D9853}>
2017-01-04T08:37:22.090000Z DEBUG SET client_encoding TO 'utf8'
2017-01-04T08:37:22.090000Z DEBUG SET maintenance_work_mem TO '1GB'
2017-01-04T08:37:22.091000Z DEBUG SET work_mem TO '16MB'
2017-01-04T08:37:22.091000Z DEBUG SET application_name TO 'pgloader'
2017-01-04T08:37:22.291000Z DEBUG CONNECTED TO #<MYSQL-CONNECTION mysql://pgloader@10.XXX.XXX.XXX:XXXXX/pgloader {10096D8173}>
2017-01-04T08:37:22.291000Z DEBUG MySQL: sending query: 
  select c.table_name, t.table_comment,
         c.column_name, c.column_comment,
         c.data_type, c.column_type, c.column_default,
         c.is_nullable, c.extra
    from information_schema.columns c
         join information_schema.tables t using(table_schema, table_name)
   where c.table_schema = 'pgloader' and t.table_type = 'BASE TABLE'
         
         and (table_name REGEXP '_pgloader_test')
         
order by table_name, ordinal_position
2017-01-04T08:37:22.292000Z DEBUG MySQL: sending query: 
SELECT s.table_name, s.constraint_name, s.ft, s.cols, s.fcols,
       rc.update_rule, rc.delete_rule

FROM
 (
  SELECT tc.table_schema, tc.table_name,
         tc.constraint_name, k.referenced_table_name ft,

             group_concat(         k.column_name
                          order by k.ordinal_position) as cols,

             group_concat(         k.referenced_column_name
                          order by k.position_in_unique_constraint) as fcols

        FROM information_schema.table_constraints tc

        LEFT JOIN information_schema.key_column_usage k
               ON k.table_schema = tc.table_schema
              AND k.table_name = tc.table_name
              AND k.constraint_name = tc.constraint_name

      WHERE     tc.table_schema = 'pgloader'
            AND k.referenced_table_schema = 'pgloader'
            AND tc.constraint_type = 'FOREIGN KEY'
           
           and (tc.table_name REGEXP '_pgloader_test')
           

   GROUP BY tc.table_schema, tc.table_name, tc.constraint_name, ft
 ) s
             JOIN information_schema.referential_constraints rc
               ON rc.constraint_schema = s.table_schema
              AND rc.constraint_name = s.constraint_name
              AND rc.table_name = s.table_name
2017-01-04T08:37:22.292000Z INFO CAST _pgloader_test.id int(10) unsigned [NIL, NOT NULL, auto_increment] TO "\"id\" bigserial not null"
2017-01-04T08:37:22.292000Z INFO CAST _pgloader_test.offer varchar(32) [NIL, NOT NULL] TO "\"offer\" varchar(32)" USING EMPTY-STRING-TO-NULL
2017-01-04T08:37:22.292000Z INFO CAST _pgloader_test.todoDate timestamp ["0000-00-00 00:00:00", NOT NULL] TO "\"todoDate\" timestamptz" USING ZERO-DATES-TO-NULL
2017-01-04T08:37:22.292000Z NOTICE CREATE TABLES
2017-01-04T08:37:22.292000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://pgloader@10.XXX.XXX.XXX:XXXXX/dbpg {10096D9853}>
2017-01-04T08:37:22.292000Z DEBUG SET client_encoding TO 'utf8'
2017-01-04T08:37:22.293000Z DEBUG SET maintenance_work_mem TO '1GB'
2017-01-04T08:37:22.293000Z DEBUG SET work_mem TO '16MB'
2017-01-04T08:37:22.293000Z DEBUG SET application_name TO 'pgloader'
2017-01-04T08:37:22.493000Z DEBUG BEGIN
2017-01-04T08:37:22.493000Z DEBUG fetch-pgsql-catalog: 1 tables, 3 indexes, 0+0 fkeys
2017-01-04T08:37:22.493000Z ERROR pgloader failed to find target table for source NIL."_pgloader_test" with name "\"_pgloader_test\"" in target catalog
2017-01-04T08:37:22.493000Z LOG Skipping "_pgloader_test"
2017-01-04T08:37:22.494000Z NOTICE Reset sequences
2017-01-04T08:37:22.494000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://pgloader@10.XXX.XXX.XXX:XXXXX/dbpg {100C8726D3}>
2017-01-04T08:37:22.494000Z DEBUG SET client_encoding TO 'utf8'
2017-01-04T08:37:22.494000Z DEBUG SET maintenance_work_mem TO '1GB'
2017-01-04T08:37:22.494000Z DEBUG SET work_mem TO '16MB'
2017-01-04T08:37:22.494000Z DEBUG SET application_name TO 'pgloader'
2017-01-04T08:37:22.495000Z DEBUG SET client_encoding TO 'utf8'
2017-01-04T08:37:22.495000Z DEBUG SET maintenance_work_mem TO '1GB'
2017-01-04T08:37:22.495000Z DEBUG SET work_mem TO '16MB'
2017-01-04T08:37:22.495000Z DEBUG SET application_name TO 'pgloader'
2017-01-04T08:37:22.495000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://pgloader@10.XXX.XXX.XXX:XXXXX/dbpg {100C8849C3}>
2017-01-04T08:37:22.495000Z DEBUG SET client_encoding TO 'utf8'
2017-01-04T08:37:22.495000Z DEBUG SET maintenance_work_mem TO '1GB'
2017-01-04T08:37:22.495000Z DEBUG SET work_mem TO '16MB'
2017-01-04T08:37:22.496000Z DEBUG SET application_name TO 'pgloader'
2017-01-04T08:37:22.496000Z INFO Stopping monitor
             table name       read   imported     errors      total time       read      write
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
        fetch meta data          1          1          0          0.152s                     
      Drop Foreign Keys          0          0          0          0.000s                     
           Drop Indexes          0          0          0          0.000s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
COPY Threads Completion          0          0          0          0.000s                     
        Reset Sequences          0         21          0          0.031s                     
           Primary Keys          1          1          0          0.000s                     
    Create Foreign Keys          0          0          0          0.000s                     
       Install Comments          0          0          0          0.000s
```

Second one:
```
$ pgloader -d test.load 
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2017-01-04T08:40:53.046000Z NOTICE Starting pgloader, log system is ready.
2017-01-04T08:40:53.077000Z INFO Starting monitor
2017-01-04T08:40:53.088000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2017-01-04T08:40:53.089000Z LOG Data errors in '/tmp/pgloader/'
2017-01-04T08:40:53.089000Z LOG Parsing commands from file #P"/var/lib/postgresql/test.load"
2017-01-04T08:40:53.089000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://pgloader@10.XXX.XXX.XXX:XXXXX/dbpg {10096DEE73}>
2017-01-04T08:40:53.089000Z DEBUG SET client_encoding TO 'utf8'
2017-01-04T08:40:53.089000Z DEBUG SET maintenance_work_mem TO '1GB'
2017-01-04T08:40:53.089000Z DEBUG SET work_mem TO '16MB'
2017-01-04T08:40:53.090000Z DEBUG SET application_name TO 'pgloader'
2017-01-04T08:40:53.290000Z DEBUG CONNECTED TO #<MYSQL-CONNECTION mysql://pgloader@10.XXX.XXX.XXX:XXXXX/pgloader {10096DD793}>
2017-01-04T08:40:53.290000Z DEBUG MySQL: sending query: 
  select c.table_name, t.table_comment,
         c.column_name, c.column_comment,
         c.data_type, c.column_type, c.column_default,
         c.is_nullable, c.extra
    from information_schema.columns c
         join information_schema.tables t using(table_schema, table_name)
   where c.table_schema = 'pgloader' and t.table_type = 'BASE TABLE'
         
         and (table_name REGEXP '_pgloader_test')
         
order by table_name, ordinal_position
2017-01-04T08:40:53.290000Z DEBUG MySQL: sending query: 
SELECT s.table_name, s.constraint_name, s.ft, s.cols, s.fcols,
       rc.update_rule, rc.delete_rule

FROM
 (
  SELECT tc.table_schema, tc.table_name,
         tc.constraint_name, k.referenced_table_name ft,

             group_concat(         k.column_name
                          order by k.ordinal_position) as cols,

             group_concat(         k.referenced_column_name
                          order by k.position_in_unique_constraint) as fcols

        FROM information_schema.table_constraints tc

        LEFT JOIN information_schema.key_column_usage k
               ON k.table_schema = tc.table_schema
              AND k.table_name = tc.table_name
              AND k.constraint_name = tc.constraint_name

      WHERE     tc.table_schema = 'pgloader'
            AND k.referenced_table_schema = 'pgloader'
            AND tc.constraint_type = 'FOREIGN KEY'
           
           and (tc.table_name REGEXP '_pgloader_test')
           

   GROUP BY tc.table_schema, tc.table_name, tc.constraint_name, ft
 ) s
             JOIN information_schema.referential_constraints rc
               ON rc.constraint_schema = s.table_schema
              AND rc.constraint_name = s.constraint_name
              AND rc.table_name = s.table_name
2017-01-04T08:40:53.290000Z INFO CAST _pgloader_test.id int(10) unsigned [NIL, NOT NULL, auto_increment] TO "\"id\" bigserial not null"
2017-01-04T08:40:53.291000Z INFO CAST _pgloader_test.offer varchar(32) [NIL, NOT NULL] TO "\"offer\" varchar(32)" USING EMPTY-STRING-TO-NULL
2017-01-04T08:40:53.291000Z INFO CAST _pgloader_test.todoDate timestamp ["0000-00-00 00:00:00", NOT NULL] TO "\"todoDate\" timestamptz" USING ZERO-DATES-TO-NULL
2017-01-04T08:40:53.491000Z NOTICE CREATE TABLES
2017-01-04T08:40:53.491000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://pgloader@10.XXX.XXX.XXX:XXXXX/dbpg {10096DEE73}>
2017-01-04T08:40:53.491000Z DEBUG SET client_encoding TO 'utf8'
2017-01-04T08:40:53.491000Z DEBUG SET maintenance_work_mem TO '1GB'
2017-01-04T08:40:53.491000Z DEBUG SET work_mem TO '16MB'
2017-01-04T08:40:53.492000Z DEBUG SET application_name TO 'pgloader'
2017-01-04T08:40:53.492000Z DEBUG BEGIN
2017-01-04T08:40:53.492000Z DEBUG fetch-pgsql-catalog: 1 tables, 3 indexes, 0+0 fkeys
2017-01-04T08:40:53.492000Z WARNING Source column "public"."_pgloader_test"."\"offer\"" is casted to type "varchar" which is not the same as "_pgloader_test_offer_enum", the type of current target database column "\"public\""."\"_pgloader_test\""."offer".
2017-01-04T08:40:53.492000Z NOTICE ALTER TABLE "public"."_pgloader_test" DROP CONSTRAINT "_pgloader_test_pkey";
2017-01-04T08:40:53.492000Z NOTICE DROP INDEX "public"._pgloader_test_offer_idx;
2017-01-04T08:40:53.492000Z NOTICE DROP INDEX "public"._pgloader_test_todoDate_idx;
2017-01-04T08:40:53.493000Z ERROR Database error 42704: index "_pgloader_test_tododate_idx" does not exist
QUERY: DROP INDEX "public"._pgloader_test_todoDate_idx;
2017-01-04T08:40:53.493000Z FATAL Failed to create the schema, see above.
2017-01-04T08:40:53.493000Z INFO Stopping monitor
       table name       read   imported     errors      total time       read      write
-----------------  ---------  ---------  ---------  --------------  ---------  ---------
  fetch meta data          1          1          0          0.161s                     
Drop Foreign Keys          0          0          0          0.000s                     
     Drop Indexes          0          0          0          0.000s                     
-----------------  ---------  ---------  ---------  --------------  ---------  ---------
```
Version (from pgdg for Debian 8):
```
$ pgloader --version
pgloader version "3.3.1"
compiled with SBCL 1.2.4.debian
```
I have not this problem with version `3.1.0` included in the debian repositories:
```
$ pgloader test.load 
2017-01-04T08:46:19.035000Z LOG Starting pgloader, log system is ready.
2017-01-04T08:46:19.068000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2017-01-04T08:46:19.079000Z LOG Data errors in '/tmp/pgloader/'
2017-01-04T08:46:19.079000Z LOG Parsing commands from file #P"/var/lib/postgresql/test.load"


                    table name       read   imported     errors            time

------------------------------  ---------  ---------  ---------  --------------
               fetch meta data          2          2          0          0.104s
------------------------------  ---------  ---------  ---------  --------------
              "_pgloader_test"          0          0          0          0.031s
------------------------------  ---------  ---------  ---------  --------------

               Reset Sequences          0          1          0          0.023s
------------------------------  ---------  ---------  ---------  --------------
             Total import time          0          0          0          0.158s
```
Version:
```
$ pgloader --version
pgloader version "3.1.0"
compiled with SBCL 1.2.3.debian
```
Some variables have been obfuscated but the main idea is there.

**Comment by jouir** [comment] 2017-04-20 08:41
After digging a bit, I've found that the regex used in `INCLUDING ONLY TABLE NAMES MATCHING` wasn't the exact string but a pattern matching eventually multiple tables. So I've changed the pattern like this:
```
INCLUDING ONLY TABLE NAMES MATCHING
    ~/^_pgloader_test$/
```
Using the latest version available on pgdg:
```
pgloader version "3.3.2"
compiled with SBCL 1.2.4.debian
```
There is no more error but the table is not imported:
```
$ pgloader --debug test.load 
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2017-04-20T08:19:33.042000Z NOTICE Starting pgloader, log system is ready.
2017-04-20T08:19:33.074000Z INFO Starting monitor
2017-04-20T08:19:33.084000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2017-04-20T08:19:33.084000Z LOG Data errors in '/tmp/pgloader/'
2017-04-20T08:19:33.084000Z LOG Parsing commands from file #P"/var/lib/postgresql/test.load"
2017-04-20T08:19:33.085000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://***@***:***/*** {1009B0FC23}>
2017-04-20T08:19:33.085000Z DEBUG SET client_encoding TO 'utf8'
2017-04-20T08:19:33.085000Z DEBUG SET maintenance_work_mem TO '1GB'
2017-04-20T08:19:33.085000Z DEBUG SET work_mem TO '16MB'
2017-04-20T08:19:33.085000Z DEBUG SET timezone TO 'Europe/Paris'
2017-04-20T08:19:33.085000Z DEBUG SET application_name TO 'pgloader'
2017-04-20T08:19:33.286000Z DEBUG CONNECTED TO #<MYSQL-CONNECTION mysql://***@***:***/*** {1009B0E563}>
2017-04-20T08:19:33.286000Z DEBUG MySQL: sending query: 
  select c.table_name, t.table_comment,
         c.column_name, c.column_comment,
         c.data_type, c.column_type, c.column_default,
         c.is_nullable, c.extra
    from information_schema.columns c
         join information_schema.tables t using(table_schema, table_name)
   where c.table_schema = 'dns' and t.table_type = 'BASE TABLE'
         
         and (table_name REGEXP '(REGEX ^_pgloader_test$)')
         
order by table_name, ordinal_position
2017-04-20T08:19:33.286000Z DEBUG MySQL: sending query: 
SELECT s.table_name, s.constraint_name, s.ft, s.cols, s.fcols,
       rc.update_rule, rc.delete_rule

FROM
 (
  SELECT tc.table_schema, tc.table_name,
         tc.constraint_name, k.referenced_table_name ft,

             group_concat(         k.column_name
                          order by k.ordinal_position) as cols,

             group_concat(         k.referenced_column_name
                          order by k.position_in_unique_constraint) as fcols

        FROM information_schema.table_constraints tc

        LEFT JOIN information_schema.key_column_usage k
               ON k.table_schema = tc.table_schema
              AND k.table_name = tc.table_name
              AND k.constraint_name = tc.constraint_name

      WHERE     tc.table_schema = 'dns'
            AND k.referenced_table_schema = 'dns'
            AND tc.constraint_type = 'FOREIGN KEY'
           
           and (tc.table_name REGEXP '(REGEX ^_pgloader_test$)')
           

   GROUP BY tc.table_schema, tc.table_name, tc.constraint_name, ft
 ) s
             JOIN information_schema.referential_constraints rc
               ON rc.constraint_schema = s.table_schema
              AND rc.constraint_name = s.constraint_name
              AND rc.table_name = s.table_name
2017-04-20T08:19:33.286000Z NOTICE CREATE TABLES
2017-04-20T08:19:33.286000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://***@***:***/*** {1009B0FC23}>
2017-04-20T08:19:33.286000Z DEBUG SET client_encoding TO 'utf8'
2017-04-20T08:19:33.286000Z DEBUG SET maintenance_work_mem TO '1GB'
2017-04-20T08:19:33.286000Z DEBUG SET work_mem TO '16MB'
2017-04-20T08:19:33.286000Z DEBUG SET timezone TO 'Europe/Paris'
2017-04-20T08:19:33.287000Z DEBUG SET application_name TO 'pgloader'
2017-04-20T08:19:33.287000Z DEBUG BEGIN
2017-04-20T08:19:33.487000Z DEBUG fetch-pgsql-catalog: 21 tables, 83 indexes, 0+0 fkeys
2017-04-20T08:19:33.488000Z NOTICE Reset sequences
2017-04-20T08:19:33.488000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://***@***:***/*** {100CA1A6D3}>
2017-04-20T08:19:33.488000Z DEBUG SET client_encoding TO 'utf8'
2017-04-20T08:19:33.488000Z DEBUG SET maintenance_work_mem TO '1GB'
2017-04-20T08:19:33.488000Z DEBUG SET work_mem TO '16MB'
2017-04-20T08:19:33.489000Z DEBUG SET timezone TO 'Europe/Paris'
2017-04-20T08:19:33.489000Z DEBUG SET application_name TO 'pgloader'
2017-04-20T08:19:33.489000Z DEBUG SET client_encoding TO 'utf8'
2017-04-20T08:19:33.489000Z DEBUG SET maintenance_work_mem TO '1GB'
2017-04-20T08:19:33.489000Z DEBUG SET work_mem TO '16MB'
2017-04-20T08:19:33.489000Z DEBUG SET timezone TO 'Europe/Paris'
2017-04-20T08:19:33.489000Z DEBUG SET application_name TO 'pgloader'
2017-04-20T08:19:33.489000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://***@***:***/*** {100CA2D3E3}>
2017-04-20T08:19:33.490000Z DEBUG SET client_encoding TO 'utf8'
2017-04-20T08:19:33.490000Z DEBUG SET maintenance_work_mem TO '1GB'
2017-04-20T08:19:33.490000Z DEBUG SET work_mem TO '16MB'
2017-04-20T08:19:33.490000Z DEBUG SET timezone TO 'Europe/Paris'
2017-04-20T08:19:33.490000Z DEBUG SET application_name TO 'pgloader'
             table name       read   imported     errors      total time       read      write
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
        fetch meta data          0          0          0          0.132s                     
      Drop Foreign Keys          0          0          0          0.000s                     
           Drop Indexes          0          0          0          0.000s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
COPY Threads Completion          0          0          0          0.001s                     
        Reset Sequences          0         21          0          0.030s                     
           Primary Keys          1          1          0          0.000s                     
    Create Foreign Keys          0          0          0          0.000s                     
       Install Comments          0          0          0          0.000s                     
2017-04-20T08:19:33.498000Z INFO Stopping monitor
```
This comes from the patten matching in the MySQL query:
```
and (table_name REGEXP '(REGEX ^_pgloader_test$)')
```
If we change it to:
```
and (table_name REGEXP '^_pgloader_test$')
```
This matches the table:
```
+----------------+---------------+-------------+----------------+-----------+------------------+---------------------+-------------+----------------+
| table_name     | table_comment | column_name | column_comment | data_type | column_type      | column_default      | is_nullable | extra          |
+----------------+---------------+-------------+----------------+-----------+------------------+---------------------+-------------+----------------+
| _pgloader_test |               | id          |                | int       | int(10) unsigned | NULL                | NO          | auto_increment |
| _pgloader_test |               | offer       |                | varchar   | varchar(32)      | NULL                | NO          |                |
| _pgloader_test |               | todoDate    |                | timestamp | timestamp        | 0000-00-00 00:00:00 | NO          |                |
+----------------+---------------+-------------+----------------+-----------+------------------+---------------------+-------------+----------------+
```

It's working with the docker version:
```
pgloader version "3.3.0.51~devel"
compiled with SBCL 1.2.4.debian
```
Result:
```
             table name       read   imported     errors      total time       read      write
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
        fetch meta data          1          1          0          0.135s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
       "_pgloader_test"         53         52          1          0.021s     0.047s    0.013s
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
COPY Threads Completion          3          3          0          0.054s                     
        Reset Sequences          0          1          0          0.014s                     
           Foreign Keys          0          0          0          0.000s                     
       Install comments          0          0          0          0.000s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
      Total import time         53         52          1          0.502s     0.047s    0.013s
```

**Comment by dimitri** [comment] 2017-04-20 12:49
Ok so the problem is fixed in the current code source, apparently. Closing the issue then. Consider re-opening if the issue is still present in current sources.

**Closed by dimitri** 2017-04-20 12:49 UTC
