### ISSUE TITLE
uppercase/lowercase problem auto-creating custom type from mysql 

### ISSUE THREAD

**Issue by rrva** [dimitri/pgloader#148] opened 2015-01-15 14:33 UTC
pgloader fails on auto-creating a table with a custom type, probably just because of a lower/uppercase issue with the type name?

If I have the following mysql table:

```sql
CREATE TABLE `DefaultAccount` (
  `uniq` enum('') NOT NULL DEFAULT '',
  `account_id` int(11) NOT NULL,
  PRIMARY KEY (`uniq`),
  KEY `account_fk` (`account_id`),
  CONSTRAINT `DefaultAccount_ibfk_1` FOREIGN KEY (`account_id`) REFERENCES `Account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

And get:

```
2015-01-15T14:30:07.788000Z INFO DROP TABLE IF EXISTS defaultaccount;
2015-01-15T14:30:07.788000Z WARNING Postgres warning: table "defaultaccount" does not exist, skipping
2015-01-15T14:30:07.788000Z INFO DROP TYPE IF EXISTS defaultaccount_uniq;
2015-01-15T14:30:07.788000Z WARNING Postgres warning: type "defaultaccount_uniq" does not exist, skipping
2015-01-15T14:30:07.788000Z INFO CREATE TYPE defaultaccount_uniq AS ENUM ('');
2015-01-15T14:30:07.789000Z INFO CREATE TABLE defaultaccount
(
  uniq                   "DefaultAccount_uniq" not null default '',
  account_id             bigint not null
);
2015-01-15T14:30:07.790000Z ERROR Database error 42704: type "DefaultAccount_uniq" does not exist
```

using the following load file:

```
load database
     from      mysql://root:secret@localhost/cfg
     into postgresql://postgres@localhost/cfg

 WITH include drop, create tables, no truncate,
      create indexes, reset sequences, foreign keys

  SET maintenance_work_mem to '128MB', work_mem to '12MB', search_path to 'cfg'

 BEFORE LOAD DO
 $$ create schema if not exists cfg; $$;
```

**Comment by dimitri** [comment] 2015-01-15 15:10
Works for me, can you tell me which version of pgloader you're using, and could you try with a current version of it compiled from git?

**Comment by el3ment** [comment] 2015-06-25 15:24
The issue here seems to be that the enum type is being created as lower case, but the type referenced in the  CREATE TABLE uses the case from the column name (upper case)

I have this same issue using 3.1.ed85387 - the packaged binary for windows.

**Comment by dimitri** [comment] 2015-06-25 18:00
There's a good chance it's been fixed in between already, is it possible for you to build pgloader from sources on windows? It was not so hard when I tried, but I got rid of the VM I had been using then...

**Comment by el3ment** [comment] 2015-06-26 15:47
I'll give it a shot and report back

**Comment by Piniol** [comment] 2015-10-13 08:30
Same problem here (3.2.2, debian):
In MySQL:
`NotificationsSettings` set('none','friends-request','friends-accepted','followers','pluses','phorum','phorum-reply') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'friends-request,friends-accepted,followers,pluses,phorum,phorum-reply',

debug:
2015-10-13T11:15:05.869000+03:00 WARNING Postgres warning: type "account_configuration_notificationssettings" does not exist, skipping
2015-10-13T11:15:05.870000+03:00 ERROR Database error 42704: type "Account_Configuration_NotificationsSettings[]" does not exist
QUERY: CREATE TABLE account_configuration
(
...
  notificationssettings   "Account_Configuration_NotificationsSettings"[] not null default '{friends-request,friends-accepted,followers,pluses,phorum,phorum-reply}',
..
);

**Comment by dimitri** [comment] 2015-11-08 20:43
Tried again, still failed to reproduce. Is it possible that you try with current git code?

**Comment by Marsiou** [comment] 2016-02-03 20:19
Hello,
I got the same issue. All my table are in lower case :(
I tried like you said with a git clone and compile pgloader. I got the issue.

**Comment by dimitri** [comment] 2016-03-26 23:15
Closing because it's an old issue now and this area has changed a lot. I believe it's been fixed until I see a self-contained test case proving me wrong in a way that I can easily reproduce the problem locally (and then fix it). Re-open with such if needed!

**Closed by dimitri** 2016-03-26 23:15 UTC
Labels: Corner case
