### ISSUE TITLE
debugger invoked on a DIVISION-BY-ZERO in thread

### ISSUE THREAD

**Issue by xbogdan** [dimitri/pgloader#480] opened 2016-11-11 16:15 UTC
After importing 65 000 000 records it crashed. 
Is there a way to start from the last record or specify where to start from ?

```
debugger invoked on a DIVISION-BY-ZERO in thread
debugger invoked on a DIVISION-BY-ZERO in thread
#<THREAD "lparallel" RUNNING {10079172C3}>:
#<THREAD "lparallel" RUNNING {10079172C3}>:
#<THREAD "lparallel" RUNNING {1007916E53}>:
  arithmetic error DIVISION-BY-ZERO signalled
  arithmetic error DIVISION-BY-ZERO signalled
```

**Comment by dimitri** [comment] 2016-11-13 21:24
Depends on the source type... what are you loading from?

**Comment by xbogdan** [comment] 2016-11-13 21:32
from MSSQL. Thats with debug mode.
```
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/var/folders/90/7mcqhw2d38q02trqgtvy6g8w0000gn/T/"
2016-11-11T15:09:05.091000+01:00 NOTICE Starting pgloader, log system is ready.
2016-11-11T15:09:05.099000+01:00 INFO Starting monitor
2016-11-11T15:09:05.102000+01:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2016-11-11T15:09:05.102000+01:00 LOG Data errors in '/private/tmp/pgloader/'
2016-11-11T15:09:05.102000+01:00 LOG Parsing commands from file #P"/Users/Tech1/mssql.load"
2016-11-11T15:09:05.102000+01:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@192.168.0.50:5432/postgres {1006B10573}>
Max connections reached, increase value of TDS_MAX_CONN
Max connections reached, increase value of TDS_MAX_CONN
2016-11-11T15:09:05.711000+01:00 DEBUG TARGET: dbo.illegallink
2016-11-11T15:09:05.711000+01:00 NOTICE COPY dbo.illegallink
2016-11-11T15:09:05.711000+01:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@192.168.0.50:5432/postgres {1006B10573}>
2016-11-11T15:09:05.711000+01:00 INFO pgsql:copy-from-queue: dbo.illegallink NIL
2016-11-11T15:09:05.914000+01:00 DEBUG SELECT [ID], ... FROM [dbo].[IllegalLink];
2016-11-11T15:09:07.527000+01:00 DEBUG BEGIN
2016-11-11T15:09:08.333000+01:00 DEBUG copy-batch dbo.illegallink 25000 rows
2016-11-11T15:09:10.344000+01:00 DEBUG BEGIN
2016-11-11T15:09:11.354000+01:00 DEBUG copy-batch dbo.illegallink 25000 rows
2016-11-11T15:09:12.767000+01:00 DEBUG BEGIN
2016-11-11T15:09:13.786000+01:00 DEBUG copy-batch dbo.illegallink 25000 rows
2016-11-11T15:09:14.588000+01:00 DEBUG BEGIN
2016-11-11T15:09:15.198000+01:00 DEBUG copy-batch dbo.illegallink 25000 rows
...
debugger invoked on a DIVISION-BY-ZERO in thread
debugger invoked on a DIVISION-BY-ZERO in thread
#<THREAD "lparallel" RUNNING {10079172C3}>:
#<THREAD "lparallel" RUNNING {10079172C3}>:
#<THREAD "lparallel" RUNNING {1007916E53}>:
  arithmetic error DIVISION-BY-ZERO signalled
  arithmetic error DIVISION-BY-ZERO signalled
```

**Comment by xbogdan** [comment] 2017-01-09 16:16
Any ideas regarding this ?

**Comment by dimitri** [comment] 2017-01-28 09:25
Still can't reproduce the bug. FYI I'm using CCL here, and fresh version from master's branch on github where I did fix some infelicities in the MS SQL support code. Nothing that strikes me as directly related to the `DIVISION-BY-ZERO` case tho, which usually has happened in the *retry batch* area of pgloader.

Can you try compiling pgloader from sources using the CCL compiler and runtime, and report your findings here?

**Comment by dimitri** [comment] 2017-07-06 08:40
Closing now. Lots of MS SQL fixing went into pgloader after that issue has been opened, and it should be good now. Of course I don't have a test case handy so it's up to users to tell me, please open this issue again if it's still relevant.

**Closed by dimitri** 2017-07-06 08:40 UTC
