### ISSUE TITLE
MySQL varbinary for strings

### ISSUE THREAD

**Issue by natmaka** [dimitri/pgloader#336] opened 2016-02-04 16:03 UTC
# My context
pgloader version "3.3.782561f"
compiled with SBCL 1.2.4.debian

MySQL 5.5 and PostgreSQL 9.4 from Debian amd64 stable

# Problem

Many aging MySQL tables store strings (esp. Unicode-encoded ones) in
VARBINARY columns. pgloader imports them into PG as BYTEA columns. This
is right but a way to handle this case would be useful, and I couldn't
find any.

# Case in point

On a MySQL empty DB 'tst1' do

 ```
CREATE TABLE tst4 (   foo varbinary(30) NOT NULL DEFAULT 'unknown' );

insert into tst4 () values ('toto');

select * from tst4; -- the result is OK
```

Then invoke

pgloader -d --verbose mysql://((your connection string))/tst1 postgresql:/((your connection string))//somedb

# Result
It runs successfully but the produced PG table contents is bytea

```
\d tst4
    Table "public.tst4"
 Column | Type  | Modifiers 
--------+-------+-----------
 foo    | bytea | not null

select * from tst4;
    foo     
------------
 \x746f746f
(1 row)

```
This is right as "select encode(foo, 'escape') from tst4;" returns
"toto", however at application level such a column is used as a string.
Therefore I need a way to obtain on PG a "text" column for each MySQL
"varbinary" column.

I searched for some 'cast type varbinary to bytea using
bytea-to-string;', to no avail.

**Comment by natmaka** [comment] 2016-02-04 17:02
According to Dimitri one may implement a transformation function in a file loaded thanks to --load-lisp-file, and it may be easy using the « babel » library which knows about many encodings.

```
  $ cat my-transforms.lisp
  (in-package :pgloader.transforms)
  (defun varbinary-to-string (string)
    (etypecase string
      (string string)
      (vector (babel:octets-to-string string))))

  $ pgloader -l my-transforms.lisp       \
             --cast "cast type varbinary to text drop typemod using varbinary-to-string" \
             mysql://…/dbname  
             pgsql://…/dbname  

```

Moreover Dimitri implemented the "varbinary-to-string" function in the commit c108b8529073b27af4bcbb6085b40eb80a96fa1e

Therefore we are now able to import MySQL varbinary type as PG text by using a "type varbinary to text drop typemod using varbinary-to-string" CAST.

**Comment by natmaka** [comment] 2016-03-13 11:44
# My context
pgloader version "3.3.c1fc4f0"
compiled with SBCL 1.2.4.debian

MySQL 5.5 and PostgreSQL 9.4 from Debian amd64 stable

# Problem

Weird behaviour

# Case in point

On a MySQL empty DB 'tst1' do

 ```
CREATE TABLE tst5 (str varbinary(255));
insert into tst5 values ('Géo');
select * from tst5; -- the result is OK
```

Then invoke

pgloader mysql://((your connection string))/tst1 postgresql:/((your connection string))//somedb

or

bin/pgloader --cast "type varbinary to text drop typemod using varbinary-to-string" mysql://((your connection string))/tst1 postgresql:/((your connection string))//somedb

# Result
Both forms run successfully but the produced table is empty

**Comment by dimitri** [comment] 2016-03-13 18:35
My guess is an encoding error, that is possible to fix using the `DECODING TABLE NAMES MATCHING` clause. That said there's something fishy about the lack of error reporting. In my local test cases covering that situation I can't reproduce the lack of error reporting. Can you tell me more about the encodings involved here?

**Comment by dimitri** [comment] 2016-03-27 00:34
The lack of error reporting should be fixed now (see https://github.com/dimitri/pgloader/commit/6f078daeb9deff8347722d0e816900bcada1b97a), so closing the issue (clean-up mode activated). Please re-open if necessary.

**Closed by dimitri** 2016-03-27 00:34 UTC

**Comment by jinyuanpeng** [comment] 2019-02-17 04:22
I have exactly the same issue, could you please share the solution? I am in 3.6.1 version

**Comment by dimitri** [comment] 2019-02-17 17:38
@jinyuanpeng see about using a casting rule such as the following:

    cast type varbinary to text drop typemod using varbinary-to-string

See https://pgloader.readthedocs.io/en/latest/ref/mysql.html#mysql-database-casting-rules for more about casting rules.

**Comment by jinyuanpeng** [comment] 2019-02-18 21:56
thanks, I applied the casting rule and changed the column from bytea to text in postgres, it works.
