### ISSUE TITLE
MsSql->PostgreSql quote identifiers don't affect expressions for FK

### ISSUE THREAD

**Issue by dmitriymudrak** [dimitri/pgloader#1038] opened 2019-10-15 13:03 UTC
--version
`pgloader version "3.6.1"
compiled with SBCL 1.4.16`

--script
`load database
 from mssql://test:12345@localhost:1433/Test
 into postgresql://test:12345@localhost:5432/Test
 WITH quote identifiers
ALTER SCHEMA 'dbo' RENAME TO 'public'
cast type datetimeoffset to timestamptz drop default;`

Error messages like

> ERROR PostgreSQL Database error 42703: column "userid" referenced in foreign key constraint does not exist

Since all data are with uppercase, scripts for FK still use old columns names.

Similar issue
[#659](https://github.com/dimitri/pgloader/issues/659)

**Comment by auspex** [comment] 2019-12-04 18:10
- [ ] pgloader --version
  
 ```
pgloader version "3.6.1"
compiled with SBCL 1.5.4.debian
```
  
  - [ ] did you test a fresh compile from the source tree?

No.    
    
  - [ ] did you search for other similar issues?

#679 — applies to MySQL

  - [ ] how can I reproduce the bug?

    Incude a self-contained pgloader command file.

    If you're loading from a database, consider attaching a database dump to
    your issue. For MySQL, use `mysqldump`. For SQLite, just send over your
    source file, that's easy. Maybe be the one with your production data, of
    course, the one with just the sample of data that allows me to reproduce
    your bug.
    
    When using a proprietary database system as a source, consider creating
    a sample database on some Cloud service or somewhere you can then give
    me access to, and see my email address on my GitHub profile to send me
    the credentials. Still open a public issue for tracking and as
    documentation for other users.

```
load database
     from mssql://geoserver@cpr/cpr_prod
     into postgresql://sahfos_dba@docker/cpr_prod

with quote identifiers

including only table names like '%' in schema 'dbo'

alter schema 'dbo' rename to 'public'
```

  - [ ] pgloader output you obtain
  
```
2019-12-04T18:06:15.468000Z ERROR PostgreSQL Database error 42703: column "currentanalyst" referenced in foreign key constraint does not exist
QUERY: ALTER TABLE public."data_entry_sample" ADD CONSTRAINT FK_data_entry_sample_currentAnalyst FOREIGN KEY(currentAnalyst) REFERENCES public."analyst"(analyst_id) ON UPDATE NO ACTION ON DELETE NO ACTION
```

  - [ ] data that is being loaded, if relevant
  

  - [ ] How the data is different from what you expected, if relevant

**Comment by auspex** [comment] 2019-12-04 18:11
So, it gets the names right, it just needs more quotes!

**Comment by vincentdesmares** [comment] 2019-12-17 15:41
I can also reproduce this issue on SQLite. It's a very blocking issue for us :(

**Comment by vincentdesmares** [comment] 2019-12-17 15:49
@dimitri Just so we know, is this repository still maintained or have you moving forward to other projects?

**Comment by dimitri** [comment] 2020-02-12 17:40
Hi guys. Still not a magician here, so if you want help then you need to provide a reproducible test case allowing me to, well, reproduce the problem locally, and then fix it. If you have the issue with SQLite then certainly preparing a SQLite schema and sharing a file makes it easy for me to then fix the bug. Please also provide full logs of the output you have with pgloader.

Closing for triaging, please re-open with a test-case if you still need help here.

**Closed by dimitri** 2020-02-12 17:40 UTC

**Comment by auspex** [comment] 2020-02-13 12:10
dmitri, the problem is in the line:

    QUERY: ALTER TABLE public."data_entry_sample" ADD CONSTRAINT FK_data_entry_sample_currentAnalyst FOREIGN KEY(currentAnalyst) REFERENCES public."analyst"(analyst_id) ON UPDATE NO ACTION ON DELETE NO ACTION

It should be ...`FOREIGN KEY("currentAnalyst")` …. It just needs some extra quotes. Possibly there should be quotes around `analyst_id`, too, but iirc you have logic to not use them where they're not absolutely required.

**Comment by dimitri** [comment] 2020-02-29 21:17
Well @auspex ; have you ever fixed a bug in a software before? You might realise that it is way more efficient for your time when you're provided with a nice test case, right? Help me help you there, or fix the bug yourself, after all you seem to have the test case I'm asking for. Your contributions (test cases or patch) are very welcome. My pgloader maintenance time is very limited.

**Comment by auspex** [comment] 2020-03-02 11:07
Whoa, that's totally uncalled for. I showed you exactly what the problem is. This **isn't** my issue! 

Still, I would have sent you a merge request if you hadn't decided to move the project from a readable code base to one written in a language I've only ever seen used in academia. I can't fix the code if I can't understand the code.

**Comment by phoe** [comment] 2020-03-02 11:21
@auspex I do not think you are entitled to support and maintenance for free software, unless you actually have a support contract with a pgloader maintainer. This is even more true if you do not help the maintainer by providing a minimal reproducible test case, since now you demand not only the time required for the bug to be fixed, but also the time required for the bug to be reproduced. It is not expected for you to understand all of the code, but it is expected of you to aid the maintainer by providing a minimal reproducible test case that shows the bug in the clear.

Please respect the maintainers' time, especially the time that's gifted to you by means of unpaid volunteering.

**Comment by auspex** [comment] 2020-03-02 12:00
@phoe Which part of "this isn't my issue" was unclear? I'm not asking for support! I don't have test cases, because it isn't my issue. I provided _help_, to the extent that I'm able, and got a condescending "have you ever fixed a bug in a software before?". Well, actually, yes I have, and have submitted **many** merge requests on GitHub.

**Comment by svantevonerichsen6906** [comment] 2020-03-02 12:04
@auspex Just to make it clear for the audience: to reproduce a bug, we need the complete input, the obtained output, and the expected output.  The input is the schema(s) and the load file, the output the resulting schema/data (if applicable) and the complete log.

You posted: the load file and some lines from the log.
Missing: the input schema and the complete log.

**Comment by phoe** [comment] 2020-03-02 12:10
@auspex OK, I totally misunderstood the context. Thanks for the help so far, and sorry for the big confusion.

You gave us a resulting line that is incorrectly formatted, but this is not enough to find the culprit. Ideally, we'd need a set of test files on which we could execute pgloader ourselves, in order to see the bug on our own machines, and then backtrack all the way to where that mis-quoted argument is generated, and then actually tell pgloader to put quotes in there.
