### ISSUE TITLE
Sqlite3 Decimals to Numeric: 

### ISSUE THREAD

**Issue by mikezter** [dimitri/pgloader#747] opened 2018-02-16 10:30 UTC
I get `Database error 22P02: invalid input syntax for type numeric` when trying to load a sqlite3 db with decimals. Follow these steps to reproduce

```
SQLite version 3.13.0 2016-05-18 10:57:30
Enter ".help" for usage hints.
sqlite> create table items (title varchar(20), price decimal(5,2));
sqlite> insert into items values ("Thingy", 1230.99);
sqlite>
```

Then, import:
```
mike-VirtualBox:~$ ./Downloads/pgloader-bundle-3.4.1/bin/pgloader test_decimals.sqlite3 postgresql://postgres:mysecretpassword@localhost/test_decimals
2018-02-16T10:52:18.493000+01:00 ERROR PostgreSQL ["items"] Database error 22P02: invalid input syntax for type numeric: "1230.99d0"
CONTEXT: COPY items, line 1, column price: "1230.99d0"
2018-02-16T10:52:18.493000+01:00 LOG report summary reset
             table name       read   imported     errors      total time
-----------------------  ---------  ---------  ---------  --------------
                  fetch          0          0          0          0.000s 
        fetch meta data          1          1          0          0.045s 
         Create Schemas          0          0          0          0.001s 
       Create SQL Types          0          0          0          0.013s 
          Create tables          2          2          0          0.024s 
         Set Table OIDs          1          1          0          0.022s 
-----------------------  ---------  ---------  ---------  --------------
                  items          1          0          1          0.020s 
-----------------------  ---------  ---------  ---------  --------------
COPY Threads Completion          4          4          0          0.020s 
 Index Build Completion          0          0          0          0.000s 
        Reset Sequences          0          0          0          0.020s 
           Primary Keys          0          0          0          0.000s 
    Create Foreign Keys          0          0          0          0.000s 
        Create Triggers          0          0          0          0.000s 
       Install Comments          0          0          0          0.000s 
-----------------------  ---------  ---------  ---------  --------------
      Total import time          1          0          1          0.499s 

```

**Comment by dimitri** [comment] 2018-02-16 10:45
I think your report is a duplicate of #739 (which has been fixed), so I'm closing here. In case I misread, please re-open, but before that build pgloader from sources and try again.

  https://github.com/dimitri/pgloader/issues/739

**Comment by mikezter** [comment] 2018-02-16 12:04
Hey Dimitri,
thanks for the quick response. However, when using current master i get a completely different error:

```
mike-VirtualBox:~$ ./code/pgloader/build/bin/pgloader test_decimals.sqlite3 postgresql://postgres:mysecretpassword@localhost/test_decimals
2018-02-16T12:58:37.112000+01:00 LOG Migrating from #<SQLITE-CONNECTION sqlite:///home/mike/test_decimals.sqlite3 {10094C99D3}>
2018-02-16T12:58:37.118000+01:00 LOG Migrating into #<PGSQL-CONNECTION pgsql://postgres@localhost:5432/test_decimals {10096F9D13}>
KABOOM!
FATAL error: Could not prepare an sqlite statement.
Code ERROR: unrecognized token: ""
".
Database: /home/mike/test_decimals.sqlite3
SQL: SELECT tbl_name
  FROM sqlite_master
 WHERE type='table'
       AND tbl_name <> 'sqlite_sequence'
       
       "

An unhandled error condition has been signalled:
   Could not prepare an sqlite statement.
Code ERROR: unrecognized token: ""
".
Database: /home/mike/test_decimals.sqlite3
SQL: SELECT tbl_name
  FROM sqlite_master
 WHERE type='table'
       AND tbl_name <> 'sqlite_sequence'
       
       "





What I am doing here?

Could not prepare an sqlite statement.
Code ERROR: unrecognized token: ""
".
Database: /home/mike/test_decimals.sqlite3
SQL: SELECT tbl_name
  FROM sqlite_master
 WHERE type='table'
       AND tbl_name <> 'sqlite_sequence'
       
       "
```

Also, when using the special casting rule, i am constrained in the absolute value of the number (?!):

```
mike-VirtualBox:~$ ~/Downloads/pgloader-bundle-3.4.1/bin/pgloader --cast 'type decimal to numeric using float-to-string' ~/test_decimals.sqlite3 postgresql://postgres:mysecretpassword@localhost/test_decimals
2018-02-16T13:01:53.488000+01:00 ERROR PostgreSQL ["items"] Database error 22003: numeric field overflow
DETAIL: A field with precision 5, scale 2 must round to an absolute value less than 10^3.
CONTEXT: COPY items, line 1, column price: "1230.99"
2018-02-16T13:01:53.489000+01:00 LOG report summary reset

[....leaving out the table...]
```

**Comment by mikezter** [comment] 2018-02-16 12:06
to be clear, i'm using commit `8e3ebd5f1ea45776867245a30936798add6051b5`
also, i get the same error with this commit, regardless of casting rules. probably a different problem?

**Comment by dimitri** [comment] 2018-02-16 16:48
Different problem yeah, working on it now.

**Closed** 2018-02-16 16:52 UTC
