### ISSUE TITLE
Unable to set workers = W, concurrency = C

### ISSUE THREAD

**Issue by Hoya** [dimitri/pgloader#505] opened 2017-01-19 11:55 UTC
I'm using the exact example given on the documentation:

```
load database
        from mysql://user:pass@server/db
        into postgresql://user:pass@server/db

WITH include drop, create tables, create indexes, reset sequences,
        workers = 8, concurrency = 1

SET search_path to 'public'

MATERIALIZE ALL VIEWS
BEFORE LOAD DO $$ create schema if not exists public; $$;
```

however I get a syntax error:
```
pgloader test.load 
An unhandled error condition has been signalled: At

  WITH include drop, create tables, create indexes, reset sequences,  
  	workers = 8, concurrency = 1
  
                ^ (Line 6, Column 14, Position 185)

In context ANOTHER-MYSQL-OPTION:

While parsing ANOTHER-MYSQL-OPTION. Expected:

     the character Tab
  or the character Newline
  or the character Space
  or the string "--"
  or the string "/*"
  or the string "batch"
  or the string "create"
  or the string "data"
  or the string "disable"
  or the string "downcase"
  or the string "foreign"
  or the string "include"
  or the string "no"
  or the string "preserve"
  or the string "quote"
  or the string "reset"
  or the string "schema"
  or the string "truncate"
  or the string "uniquify"
  or the string "workers"
```

works perfectly if I remove workers = 8, concurrency = 1.

```
pgloader --version
pgloader version "3.2.2"
compiled with SBCL 1.3.1.debian
```

**Comment by alasdairdc** [comment] 2017-01-19 18:37
Have you tried upgrading to 3.3.2?

**Comment by Hoya** [comment] 2017-01-19 19:15
Just tried that, same results

**Comment by dimitri** [comment] 2017-01-20 21:14
My guess is something strange in the database URIs, given that I can parse the file just fine here.

**Comment by lyonssp** [comment] 2017-03-10 15:54
I experience the exact same error when installing pgloader 3.2.2 on ubuntu 16.04 with apt.

If I use the exact sample provided above (without changing URIs), pgloader will still fail with a compilation error before attempting to hit the fake URIs.

**Comment by dimitri** [comment] 2017-03-15 08:46
Can you try with pgloader 3.3.2 please?

**Comment by dimitri** [comment] 2017-05-06 12:51
Closing the issue for lack of information to reproduce and fix the bug. Please open again with more information if you still have the problem with the current master's branch.

**Closed by dimitri** 2017-05-06 12:51 UTC

**Comment by splodingsocks** [comment] 2018-07-10 03:35
I was running into this while loading from CSV. It looks like the workers & concurrency options change depending on the source? I found in the tests that for the CSV file they use "batch concurrency".

https://github.com/dimitri/pgloader/blob/8fb542bc902c20fb20cda7ca4c8d0482015579c4/test/csv-districts-stdin.load#L33

@dimitri is this correct? When I just use `concurrency=N` in my loader file (when loading from CSV) I get the syntax error described above, except it's for the CSV context, and not the MySQL context.

Here's what my file looks like:

```
LOAD CSV
    FROM ALL FILENAMES MATCHING ~/.*/ IN DIRECTORY './foo' (key,flags,expiration,cas,doc,rev,vbid,dtype)
    INTO postgres://foo@foo:5432/foo?bar&sslmode=require
        TARGET COLUMNS
        (
            key,
            doc jsonb using (no-nulls doc) /* no-nulls is a function that removes the sequence \u0000 */
        )

    WITH
        truncate,
        drop indexes,
        disable triggers,
        skip header = 1,
        fields optionally enclosed by '"',
        fields escaped by double-quote,
        fields terminated by ',',
        batch concurrency = 8
    ;
```

regardless, when I set `batch concurrency`, I can't get more than 2 of my 4 available CPUs to be used at one time. I'd like to use them all up!

**Comment by alasdairdc** [comment] 2018-07-16 12:59
Previous suggestions are to check with 3.3.2 perhaps try adding the Postgresql repo as mentioned in #565 to get a more recent version.

**Comment by jdeferrari** [comment] 2018-09-21 14:36
The newest version with apt-get is 3.2.2

**Comment by alasdairdc** [comment] 2018-09-21 17:33
@jdeferrari `3.2.2` is the latest from the office debian repo.  if read the **whole** of the above comment `try adding the Postgresql repo ... to get a more recent version.` you can get `3.5.2`.

**Comment by fletcheaston** [comment] 2021-08-13 01:36
I'm having the same original issue, I can't wrangle pgloader into letting me specify workers, concurrency, multiple readers per thread, etc.

```
An unhandled error condition has been signalled: At

  WITH data only, quote identifiers,
       workers = 8, concurrency = 2
  
                    ^ (Line 6, Column 18, Position 237)

In context ANOTHER-MYSQL-OPTION:

While parsing ANOTHER-MYSQL-OPTION. Expected:

     the character Tab
  or the character Newline
  or the character Space
  or the string "--"
  or the string "/*"
  or the string "batch"
  or the string "create"
  or the string "data"
  or the string "disable"
  or the string "downcase"
  or the string "foreign"
  or the string "include"
  or the string "no"
  or the string "preserve"
  or the string "quote"
  or the string "reset"
  or the string "schema"
  or the string "truncate"
  or the string "uniquify"
  or the string "workers"

; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
```

Using these WITH options

```
WITH data only, quote identifiers,
     workers = 8, concurrency = 2
```

This is for MySQL -> Postgres
