### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by achelouah** [dimitri/pgloader#203] opened 2015-04-07 20:06 UTC
Hello Dimitri,

I'm trying to build the latest git version using sbcl 1.2.10. The build fails with the error message

**Symbol "*EXTERNAL-FORMAT*" not found in the DB3 package**

```
[chelouah@jonction pgloader-3.2.0-git8f57c9 (master)]$ sbcl --version
SBCL 1.2.10
```
```
[chelouah@jonction pgloader-3.2.0-git8f57c9 (master)]$ git log
commit 8f57c90809c04f9c7e353b8e77f66555936fef5a
Merge: 36eeb6f fe35487
Author: Dimitri Fontaine <dim@tapoueh.org>
Date:   Mon Mar 23 22:19:55 2015 +0100

    Merge pull request #196 from benesch/makefile-updates
    
    Match pgloader-standalone target to pgloader target
...
```
```
[chelouah@jonction pgloader-3.2.0-git8f57c9 (master)]$ make pgloader
....

; Loading "uuid"
..................................................
[package trivial-utf-8]...........................
[package uuid].
; Loading "pgloader"
..................................................
[package pgloader.params].........................
[package pgloader.transforms].....................
[package pgloader.logs]...........................
[package pgloader.monitor]........................
[package pgloader.utils]..........................
[package pgloader.archive]........................
[package pgloader.parse-date].....................
[package pgloader.connection].....................
[package pgloader.sources]........................
[package pgloader.pgsql]..........................
[package pgloader.queue]..........................
[package pgloader.ini]............................
[package pgloader.sql]............................
[package pgloader.csv]............................
[package pgloader.fixed]..........................
[package pgloader.copy]...........................
[package pgloader.ixf]............................
[package pgloader.db3]............................
[package pgloader.mysql]..........................
[package pgloader.sqlite].........................
[package pgloader.mssql]..........................
[package pgloader.syslog].........................
[package pgloader.parser].........................
[package pgloader]................................
..................................................
..................................................
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "*EXTERNAL-FORMAT*" not found in the DB3 package.
;   
;       Line: 37, Column: 32, File-Position: 1337
;   
;       Stream: #<SB-SYS:FD-STREAM
;                 for "file /ESA/build/pgloader-3.2.0-git8f57c9/src/sources/db3/db3.lisp"
;                 {100698C043}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {1002CDF0F3}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "db3" "db3">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "db3" "db3">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "db3" "db3">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "pgloader"
  5: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  6:                                 Skip rest of --eval and --load options.
  7:                                 Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "pgloader" "src" "sources" "db3" "db3">)))
0]
```

**Comment by dimitri** [comment] 2015-04-07 22:47
Can't reproduce here, with an older SBCL, will retry after upgrading later. Thanks for the report.

**Comment by achelouah** [comment] 2015-04-08 08:06
I don't know if it's matter, but I also tried with SBCL 1.2.4 with the same build error (under RHEL 6.2)

**Comment by dimitri** [comment] 2015-04-17 20:18
I just built using SBCL 1.2.10 without problem. Please try `make clean all` and report back?

**Comment by achelouah** [comment] 2015-04-17 20:52
I'm still getting the same error (last git under RHEL 6.2 or CentOS 6.6)

```
[package pgloader.syslog].........................
[package pgloader.parser].........................
[package pgloader]................................
..................................................
..................................................
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "*EXTERNAL-FORMAT*" not found in the DB3 package.
;   
;       Line: 37, Column: 32, File-Position: 1337
;   
;       Stream: #<SB-SYS:FD-STREAM
;                 for "file /ESA/build/pgloader-3.2.0-5ac3967/src/sources/db3/db3.lisp"
;                 {10059BCD73}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {1002CDF0F3}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "db3" "db3">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "db3" "db3">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "db3" "db3">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "pgloader"
  5: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  6:                                 Skip rest of --eval and --load options.
  7:                                 Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "pgloader" "src" "sources" "db3" "db3">)))
0]
```

**Comment by dimitri** [comment] 2015-04-17 21:48
The external-format support in cl-db3 was added with this commit: https://github.com/dimitri/cl-db3/commit/770cbe35261f55dbdcbf3681b9d9dbaea6ea216d

It looks like something is fishy on your install and you don't have the latest version of that source code, where the pgloader Makefile is supposed to ensure that after `make clean`. Can you see about that?

**Comment by achelouah** [comment] 2015-04-30 15:05
I cloned again the git repo, but the build still fails at the same point. What packages did you install under CentOS/RHEL 6 ?

**Comment by dimitri** [comment] 2015-04-30 15:45
See https://github.com/dimitri/pgloader/blob/master/bootstrap-centos.sh

Advanced debugging here might require fiddling with lisp to some extend, to run diagnostic commands. Try the bootstrap reference then tell me if you still have problems, we'll how to diagnose in depth.

**Comment by dimitri** [comment] 2015-05-22 21:55
Meanwhile the right version of cl-db3 has entered Quicklisp, I'm closing the issue here. Of course considering re-opening if needed.

**Closed by dimitri** 2015-05-22 21:55 UTC
