### ISSUE TITLE
Heap exhausted error loading csv file

### ISSUE THREAD

**Issue by randomee** [dimitri/pgloader#487] opened 2016-12-05 18:34 UTC
I'm trying to load a csv file, and getting this error.  I'm using `pgloader_3.3.2+dfsg-1_amd64.deb`.  

The files are dumps from a MSSQL db.  Until this week, I've had no problem loading the files.  The only possibly odd thing I'm doing is using ^G to separate fields.  

```
root@ip-172-31-0-231:~# pgloader foo.bcp.pgloader
2016-12-05T21:20:08.036000+03:00 LOG Main logs in '/tmp/pgloader/pgloader.log'
2016-12-05T21:20:08.040000+03:00 LOG Data errors in '/tmp/pgloader/'
2016-12-05T21:20:08.040000+03:00 LOG Parsing commands from file #P"foo.bcp.pgloader"
Heap exhausted during garbage collection: 0 bytes available, 48 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   1: 69137 109084     0     0  9712 26040     0     0    12 1170714848 806688 746439496    0   1  1.4027
   2: 125606 131071     0     0 19318 48457    76     0     8 2221957008 1384560 42949672 9662   0  0.5253
   3: 17493 52593     0     0  2650 20664   145     0    79 759883056 8821456  2000000 2711   0  0.4392
   4:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   6:     0     0     0     0  2850  1160     0     0     0 131399680     0  2000000 2726   0  0.0000
   Total bytes allocated    = 4283954592
   Dynamic-space-size bytes = 4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 8421(tid 140737039562496):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb>
```
```
LOAD CSV

   FROM 'foo.bcp.clean'
   WITH ENCODING UTF-8

   INTO postgresql://dbadmin:XXX@dbhost:5432/SWCRM?tablename=foo

   WITH
--      batch rows = 500,
        truncate,
--      csv header,
--      skip header=1,
        fields not enclosed,
        fields terminated by '^G'

    SET work_mem to '512 MB', maintenance_work_mem to '2048 MB';
```

**Comment by dimitri** [comment] 2016-12-05 20:03
Is the file much larger than usual? can you have a look at the content, maybe it's missing the field separator? maybe you can try with a direct connection form pgloader to MSSQL?

Also, did you try changing the parallelism options (workers, concurrency) and see how it affects the load?

**Comment by randomee** [comment] 2016-12-05 20:12
It's not much bigger than last week.  Maybe 2%.  It's a 2G file, so not so easy to look at manually for issues.  

I've tried direct mssql-postgres from pgloader, but have auth issues.  sqsh seems to work fine, but not pgloader (yes, I should look more at this too.)

I'm trying some worker/concurrency options now.

**Comment by dimitri** [comment] 2016-12-06 09:17
For concurrency, I don't have suggestions as it's still experimental in how to set it up...

**Comment by randomee** [comment] 2016-12-06 16:00
I tried workers 1, concurrency 1, hangs w/ no error, doing no work.  

I tried other pairs and i dies like above w/ a heap exhaustion message.  the size of requests & avail heap change, but that's the only difference.

I also re-dumped the mssql DB, in case there was an issue w/ the dump.  no change.

**Comment by mfn** [comment] 2016-12-28 15:38
I experienced this problem also a few times today but I really wasn't able to pin where it came from.

### Here's an example

Minimal config file
```
load database
 from mysql://...
 into postgresql://...

CAST
 type varchar to varchar,
 type bigint with extra auto_increment to bigserial drop typemod,
 type bigint to bigint drop typemod
;
```
Version of pgloader (yes, this was with an older ...)
```
$  pgloader --version
pgloader version "3.3.1"
compiled with SBCL 1.2.4.debian
```
The actual failure output:
```
Heap exhausted during garbage collection: 64 bytes available, 96 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   1:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   2: 105851 120318     0     0  3060 28342     0     0     0 1017909648 11071088 42949672    0   0  0.9889
   3: 115262 118073     0     0  6749 59588   249    20    94 2158991712 23553696 42949672 6845   0  0.7454
   4: 34030 34079     0     0  1240  6434    90     0    79 251771072 2639680  2000000 1236   0  0.0000
   5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   6:     0     0     0     0  3537  1150     0     0     0 153583616     0  2000000 3355   0  0.0000
   Total bytes allocated    = 4246809088
   Dynamic-space-size bytes = 4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 19153(tid 140737308686080):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> exit
Argh! lossage_handler() returned, total confusion..
```
Other times I was running the same thing (more or less; I didn't record all the changes to the config/parameters to pgloader) and it didn't have this problem.

**Comment by mfn** [comment] 2016-12-29 13:40
In https://github.com/dimitri/pgloader/issues/496#issuecomment-269596697 I reported how long it took me to import a single, big table using `batch rows  = 1000`.

Being determined to increase this number to hopefully increase performance and knowing that the default of `25000` already fails me, I was determined to find the right batch rows for me.

After a few hours I found my sweet spot which is `batch rows = 7500`.

I tried these batch rows and *always* had "Heap exhausted..." errors:
- unspecified, aborted after 1m37s, imported 1.348.899 rows
- 25000, aborted after 1m9s, imported 1.422.124 rows
- 20000, aborted after 1m14s, imported 1.503.636 rows
- 15000, aborted after 2m27s, imported 3.239.656 rows
- 12500, aborted after 4m7s, imported 5.368.816 rows
- 10000, aborted after 12m2s, imported 15.831.350 rows

With 7500 it finally worked, importing all 63.712.487 rows in 47m40s (sans creating indices and foreign keys).

In http://pgloader.io/howto/pgloader.1.html I read upon the `batch size` but it simply didn't matter (I tried to get `batch rows=25000` working). Whether I provided `batch size=1MB` or `batch size=100MB`, it always aborted roughly after 1m.

This is currently absolutely reproducible for me, so if there's anything else I can try to assist finding the cause, please let me know. I should have access to the machine with the dataset for the next month or so.

<details>
<summary>Not sure if all the individual heap errors are useful? Just in case, here they are</summary>

- unspecified batch rows, aborted after 1m37s, imported 1.348.899 rows:
```
Heap exhausted during garbage collection: 256 bytes available, 320 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   1:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   2: 90306 92844     0     0  2944 27458     0     0     0 984413728 11799008 42949672    0   0  0.9613
   3: 115998 126901     0     0  6846 61081   190    10   118 2204917744 27467792  2000000 6860   0  0.6692
   4:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   6:     0     0     0     0  3639  1160     0     0     0 157253632     0  2000000 3460   0  0.0000
   Total bytes allocated    = 4241079056
   Dynamic-space-size bytes = 4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 2580(tid 140737304131328):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> exit
Argh! lossage_handler() returned, total confusion..
```

- 25000, aborted after 1m9s, imported 1.422.124 rows
```
Heap exhausted during garbage collection: 208 bytes available, 448 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   1:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   2: 85138 120030     0     0  4699 43937    24     0     0 1577519184 16971696 989779576    0   1  1.4012
   3: 130831 131071     0     0  9071 68247   265    30   138 2520507552 22715232  2000000 6457   0  1.3675
   4:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   6:     0     0     0     0  3639  1160     0     0     0 157253632     0  2000000 3459   0  0.0000
   Total bytes allocated    = 4255280368
   Dynamic-space-size bytes = 4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 2615(tid 140737304131328):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> exit
Argh! lossage_handler() returned, total confusion..
```

- 20000, aborted after 1m14s, imported 1.503.636 rows
```
Heap exhausted during garbage collection: 16 bytes available, 48 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   1:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   2: 124101 125926     0     0  5002 46521    44     0     0 1674580880 15166576 973045160    0   1  1.3475
   3: 127320 131071     0     0  8514 65963   199    30   140 2424376880 23589328  2000000 5914   0  1.3339
   4:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   6:     0     0     0     0  3639  1160     0     0     0 157253632     0  2000000 3459   0  0.0000
   Total bytes allocated    = 4256211392
   Dynamic-space-size bytes = 4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 2646(tid 140737295087360):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> exit
Argh! lossage_handler() returned, total confusion..
```

- 15000, aborted after 2m27s, imported 3.239.656 rows
```
Heap exhausted during garbage collection: 80 bytes available, 96 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   1:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   2: 122179 124020     0     0  4218 39451    10    10     0 1416986992 14614160 754745272    0   1  1.2240
   3: 130132 131071     0     0  6457 58304    75     0    64 2105516832 19029216 42949672 4269   0  1.0518
   4: 53378 59284     0     0  1865 15858    25     0    64 571188624 10377840  2000000 1782   0  0.0000
   5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   6:     0     0     0     0  3639  1160     0     0     0 157253632     0  2000000 3457   0  0.0000
   Total bytes allocated    = 4250946080
   Dynamic-space-size bytes = 4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 2680(tid 140737308686080):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> exit
Argh! lossage_handler() returned, total confusion..
```

- 12500, aborted after 4m7s, imported 5.368.816 rows
```
Heap exhausted during garbage collection: 80 bytes available, 96 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   1: 120892 121937     0     0  1208 11010     0     0     0 396463056 3896368 277659160    0   1  1.3880
   2: 130204 131071     0     0  4114 37046     0     0    43 1335749376 12981504 606165672 2862   1  1.1371
   3: 115924 117317     0     0  3646 34036     0    20    43 1220491344 14927792 42949672 3569   0  0.5004
   4: 40294 75130     0     0  3517 31637     0    39    88 1135099216 18105008  2000000 3395   0  0.4588
   5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   6:     0     0     0     0  3639  1160     0     0     0 157253632     0  2000000 3459   0  0.0000
   Total bytes allocated    = 4245056624
   Dynamic-space-size bytes = 4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 2730(tid 140737299609344):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> exit
Argh! lossage_handler() returned, total confusion..
```

- 10000, aborted after 12m2s, imported 15.831.350 rows
```
Heap exhausted during garbage collection: 16 bytes available, 32 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   1:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   2: 121021 128846     0     0  3564 34133     0     0     0 1221322112 13933184 545250520    0   1  1.1170
   3: 72262 131071     0     0  4291 40119     0     0    59 1440500592 14726288 42949672 2854   0  1.0378
   4: 74930 77706     0     0  3037 28724     0     0    36 1028230912 12513536 42949672 2973   0  0.5053
   5: 39678 39674     0     0  1374 11031     0     0    63 399644016 6843024  2000000 1280   0  0.0000
   6:     0     0     0     0  3639  1160     0     0     0 157253632     0  2000000 3459   0  0.0000
   Total bytes allocated    = 4246951264
   Dynamic-space-size bytes = 4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 2777(tid 140737295087360):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> exit
Argh! lossage_handler() returned, total confusion..
```
</details>

**Comment by kaivi** [comment] 2017-05-07 18:25
Had the same issue with heap exhaustion, it occured on importing COPY dumps including 1%-5% invalid rows (*retrieved from a corrupted database*). Solved by using a CCL-compiled binary from [this Docker container](https://hub.docker.com/r/dimitri/pgloader/~/dockerfile/).
Why not build with CCL by default?

**Comment by dimitri** [comment] 2017-05-07 19:06
Because CCL has yet to make it to Debian :/

**Comment by kaivi** [comment] 2017-06-15 20:31
I've used a CCL-built binary for a month now, but it's a whole nother can of worms:

- Using identical settings, dumping the same data took 38 days with CCL vs 6 days with SBCL
- Attempted to dump another table with CCL when this happened:

![CCL](http://i.imgur.com/j31CrQE.gif)

Had to use SBCL version again with a tiny batch size to avoid heap exhaustion.

Strange how this is not the most popular issue, because I am getting exhausted heap with any table larger than a couple of gigabytes with some invalid rows.

**Comment by dimitri** [comment] 2017-06-16 06:42
It might then be all about invalid rows management, because I've seen reports of success with very large data sets. Is it possible for you to share a source file for me to reproduce the problem locally?

**Comment by dimitri** [comment] 2017-06-28 14:40
I think you should try again with a fresh build, given recent work on pgloader, and in particular the following commit: https://github.com/dimitri/pgloader/commit/6d66280fa58c93ea6b00679568477dce1d0ddd68

**Comment by dimitri** [comment] 2017-07-06 08:39
Closing in an attempt to clean-up the issue list. The mentioned commit should help. If that's not the case, please re-open the issue.

**Closed by dimitri** 2017-07-06 08:39 UTC
