### ISSUE TITLE
Hang "Non-retryable error" on import to PgSQL

### ISSUE THREAD

**Issue by ErikZigo** [dimitri/pgloader#546] opened 2017-05-04 20:36 UTC
I have problem with importing data from local CSV file into remote PgSQL server.

Trying with `--on-error-stop` enabled.

When server restarts, or there is an issue with network connection, import fails with error:

Sample debug output:
```
2017-05-04T18:41:34.200533Z ERROR Non-retryable error Database error: Unexpected end of file on #<BASIC-TCP-STREAM :CLOSED #x3020010B902D>
2017-05-04T18:41:34.200790Z ERROR Database error: Connection to database server lost.
2017-05-04T18:41:34.200975Z ERROR Database error: Connection to database server lost.
2017-05-04T18:41:34.201146Z ERROR A thread failed with error: Database error: Connection to database server lost.
```
but pgloader does not stop and is running infinitely

Mabe there is problem with calling `ROLLBACK` query after log `Non-retryable` error?
https://github.com/dimitri/pgloader/blob/8254d63453d4100c00b9a3c6f4b2eda48b80976b/src/pgsql/copy-from-queue.lisp#L94

**Comment by dimitri** [comment] 2017-05-05 19:19
I can't quite reproduce the error here, and the error message seems to come from the postmodern CL driver rather than from the database server itself, so I am not even sure the code you point to is the one at fault here. Do you want to try some fixes? you could begin with the following one:

```diff
modified   src/pgsql/copy-from-queue.lisp
@@ -88,6 +88,14 @@
                 (log-message :error "~a" condition)
                 (retry-batch table columns batch batch-rows condition))))
 
+        ((or
+          cl-postgres-error::database-connection-error
+          cl-postgres-error::database-connection-lost
+          cl-postgres-error::database-socket-error) (condition)
+          ;; we lost the connection
+          ;; FIXME: handle the :reconnect restart
+          (log-message :error "~a" condition))
+
         (condition (c)
           ;; non retryable failures
           (log-message :error "Non-retryable error ~a" c)
```

**Comment by ErikZigo** [comment] 2017-05-30 15:08
I found other way to reproduce my problem:

I have tested it on two machines
```
# pgloader --version
pgloader version "3.3.3c4e64e"
compiled with Clozure Common Lisp Version 1.11-r16635  (LinuxX8664)
```
```
# pgloader --version
pgloader version "3.3.2120898"
compiled with SBCL 1.3.17
```




Lets have an PgSQL table
```
CREATE TABLE "sample" ("id" VARCHAR(4) NOT NULL);
```

And input csv file `sample.csv`
```
"id"
"test"
"test value"
```

When I run this command:

```
pgloader --debug \
                --client-min-messages debug \
                --on-error-stop \
                --type csv \
                --field "id" \
                --with "skip header = 1" \
                --with "quote identifiers" \
                --with "fields terminated by ','" \
                --with "batch rows = 500" \
                ./sample.csv postgres://user:password@server:5432/dbname?tablename="sample"
```


Pgloader write this output an hang

```
2017-05-30T17:01:09.010000+02:00 NOTICE Starting pgloader, log system is ready.
2017-05-30T17:01:09.020000+02:00 INFO Starting monitor
2017-05-30T17:01:09.023000+02:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2017-05-30T17:01:09.024000+02:00 LOG Data errors in '/private/tmp/pgloader/'
2017-05-30T17:01:09.024000+02:00 INFO SOURCE: "./sample.csv"
2017-05-30T17:01:09.024000+02:00 INFO TARGET: "postgres://user:password@server:5432/dbname?tablename=sample"
2017-05-30T17:01:09.024000+02:00 DEBUG LOAD DATA FROM #<PGLOADER.CSV:CSV-CONNECTION csv://FILENAME: {10058ABB03}>
2017-05-30T17:01:09.024000+02:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://user:password@server:5432/dbname {10059E54D3}>
2017-05-30T17:01:09.024000+02:00 DEBUG SET client_encoding TO 'utf8'
2017-05-30T17:01:09.024000+02:00 DEBUG SET application_name TO 'pgloader'
2017-05-30T17:01:09.226000+02:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://user:password@server:5432/dbname {10059E54D3}>
2017-05-30T17:01:09.226000+02:00 DEBUG SET client_encoding TO 'utf8'
2017-05-30T17:01:09.428000+02:00 DEBUG SET application_name TO 'pgloader'
2017-05-30T17:01:09.428000+02:00 SQL 
    select nspname, relname, c.oid, attname,
           t.oid::regtype as type,
           case when atttypmod > 0 then atttypmod - 4 else null end as typmod,
           attnotnull,
           case when atthasdef then def.adsrc end as default
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid and attnum > 0
           left join pg_attrdef def on a.attrelid = def.adrelid
                                   and a.attnum = def.adnum

     where nspname !~ '^pg_' and n.nspname <> 'information_schema'
           and relkind = 'r'
           and ((n.nspname = 'public' and c.relname ~ '^sample$'))
           

  order by nspname, relname, attnum
2017-05-30T17:01:09.630000+02:00 SQL 
  select n.nspname,
         i.relname,
         i.oid,
         rn.nspname,
         r.relname,
         indisprimary,
         indisunique,
         pg_get_indexdef(indexrelid),
         c.conname,
         pg_get_constraintdef(c.oid)
    from pg_index x
         join pg_class i ON i.oid = x.indexrelid
         join pg_class r ON r.oid = x.indrelid
         join pg_namespace n ON n.oid = i.relnamespace
         join pg_namespace rn ON rn.oid = r.relnamespace
         left join pg_constraint c ON c.conindid = i.oid
                                  and c.conrelid = r.oid
                                  -- filter out self-fkeys
                                  and c.confrelid <> r.oid
   where n.nspname !~ '^pg_' and n.nspname <> 'information_schema'
         and ((rn.nspname = 'public' and r.relname ~ '^sample$'))
         
order by n.nspname, r.relname
2017-05-30T17:01:09.630000+02:00 SQL 
 select n.nspname, c.relname, nf.nspname, cf.relname as frelname,
        r.oid, conname,
        pg_catalog.pg_get_constraintdef(r.oid, true) as condef,
        (select string_agg(attname, ',')
           from pg_attribute
          where attrelid = r.conrelid
            and array[attnum::integer] <@ conkey::integer[]
        ) as conkey,
        (select string_agg(attname, ',')
           from pg_attribute
          where attrelid = r.confrelid
            and array[attnum::integer] <@ confkey::integer[]
        ) as confkey,
        confupdtype, confdeltype, confmatchtype,
        condeferrable, condeferred
   from pg_catalog.pg_constraint r
        JOIN pg_class c on r.conrelid = c.oid
        JOIN pg_namespace n on c.relnamespace = n.oid
        JOIN pg_class cf on r.confrelid = cf.oid
        JOIN pg_namespace nf on cf.relnamespace = nf.oid
   where r.contype = 'f'
         AND c.relkind = 'r' and cf.relkind = 'r'
         AND n.nspname !~ '^pg_' and n.nspname <> 'information_schema'
         AND nf.nspname !~ '^pg_' and nf.nspname <> 'information_schema'
         and ((n.nspname = 'public' and c.relname ~ '^sample$'))
         
         and ((nf.nspname = 'public' and cf.relname ~ '^sample$'))
         
2017-05-30T17:01:09.630000+02:00 DEBUG fetch-pgsql-catalog: 1 tables, 0 indexes, 0+0 fkeys
2017-05-30T17:01:09.631000+02:00 NOTICE COPY "\"sample\""
2017-05-30T17:01:09.632000+02:00 DEBUG Transformer 2 in action for "sample"!
2017-05-30T17:01:09.632000+02:00 DEBUG Reader started for "sample"
2017-05-30T17:01:09.641000+02:00 NOTICE Opening #P"/Users/erik/sample.csv"
2017-05-30T17:01:09.641000+02:00 DEBUG finish-batch[3] 3 rows in 0.007000s
2017-05-30T17:01:09.641000+02:00 DEBUG Reader for "sample" is done in 0.007000s
2017-05-30T17:01:09.641000+02:00 DEBUG Finished processing READER for "\"sample\""       0.007000s
2017-05-30T17:01:09.641000+02:00 DEBUG format-data-to-copy[2] 3 row in 0.000000s
2017-05-30T17:01:09.641000+02:00 INFO Transformer[2] for "sample" is done in 0.008000s
2017-05-30T17:01:09.641000+02:00 DEBUG Finished processing WORKER for "\"sample\""       0.008000s
2017-05-30T17:01:09.641000+02:00 DEBUG start "sample"                 784
2017-05-30T17:01:09.845000+02:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://user:password@server:5432/dbname {1007B03E13}>
2017-05-30T17:01:09.845000+02:00 DEBUG SET client_encoding TO 'utf8'
2017-05-30T17:01:09.846000+02:00 DEBUG SET application_name TO 'pgloader'
2017-05-30T17:01:09.846000+02:00 INFO pgsql:copy-from-queue[0]: "sample" ("id")

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "lparallel" RUNNING {1007543163}>:
  Stop loading data for table "\"sample\"" on first error.
2017-05-30T17:01:10.051000+02:00 FATAL Database error 22001: value too long for type character varying(4)
CONTEXT: COPY sample, line 2, column id: "test value"
2017-05-30T17:01:10.052000+02:00 ERROR A thread failed with error: Stop loading data for table "\"sample\"" on first error.
```

Then I have to press `Ctrl + C` to stop pgloader


```
2017-05-30T17:04:22.460000+02:00 FATAL Interactive interrupt at #x7FFF99B54276.
2017-05-30T17:04:22.461000+02:00 LOG report summary reset
             table name       read   imported     errors      total time       read      write
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
                  fetch          0          0          0          0.008s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
               "sample"          3          0          0          0.008s     0.008s          
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
        Files Processed          1          1          0          0.024s                     
COPY Threads Completion          3          3          0       1m24.511s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
      Total import time          3          0          0       1m25.466s     0.008s    0.000s
2017-05-30T17:04:22.465000+02:00 INFO Stopping monitor
```

**Comment by dimitri** [comment] 2017-05-31 10:48
This example is very different from the first one. In case of data error when using *on-error-stop* and only when log verbosity is either `data` or `debug` then pgloader is supposed to print a backtrace before handling the error. That's the bug you're now reaching. Try again in verbose mode rather than debug mode and the error won't happen again.

That said, this bug too needs fixing...

**Comment by ErikZigo** [comment] 2017-06-01 01:13
Hi dimitri

I am using `debug` instead of `verbose`, because I need have info about processed batches.


But I have tried `verbose` mode with this result:

It look that it works, but only if there is only 10 batches or less.
If more, it freeze as in `debug` mode.

I took 100 line CSV and modified `batch rows` value to simulate this.

**Comment by ErikZigo** [comment] 2017-06-01 01:16
It does not matter which line in the csv has a error data. It can be first, or last.

**Comment by dimitri** [comment] 2017-06-01 12:08
When I try to reproduce the error locally, using one of the pgloader test files, it's all good. Can you provide me a self-contained test case for me to reproduce your error easily? You can base your work on the following file I prepared, with which I could reproduce the *on-error-stop* behaviour that I still need to find a fix for... (there's code to handle it properly, but it's not working as intended)

```
LOAD CSV
     FROM INLINE with encoding 'ascii'
     INTO postgresql:///pgloader?t546

     WITH skip header = 1,
          batch rows = 500,
          quote identifiers,
          fields terminated by ','

   BEFORE LOAD DO
    $$ drop table if exists t546; $$,
    $$ CREATE TABLE t546 ("id" VARCHAR(4) NOT NULL); $$;


"id"
"test"
"test value"
```

Here the error handling with the test case that just works:

```
~/dev/pgloader LANG=en_US.UTF-8 ./build/bin/pgloader --debug ./test/csv-error.load 
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/var/folders/hp/qpznhnq566s9k9hz8pbgqsp40000gn/T/"
2017-06-01T14:05:55.009000+02:00 NOTICE Starting pgloader, log system is ready.
2017-06-01T14:05:55.017000+02:00 INFO Starting monitor
2017-06-01T14:05:55.019000+02:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2017-06-01T14:05:55.019000+02:00 LOG Data errors in '/private/tmp/pgloader/'
2017-06-01T14:05:55.019000+02:00 LOG Parsing commands from file #P"/Users/dim/dev/pgloader/test/csv-error.load"
2017-06-01T14:05:55.222000+02:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dim@UNIX:5432/pgloader {100599BE63}>
2017-06-01T14:05:55.222000+02:00 DEBUG SET client_encoding TO 'utf8'
2017-06-01T14:05:55.222000+02:00 DEBUG SET work_mem TO '128MB'
2017-06-01T14:05:55.222000+02:00 DEBUG SET standard_conforming_strings TO 'on'
2017-06-01T14:05:55.222000+02:00 DEBUG SET application_name TO 'pgloader'
2017-06-01T14:05:55.223000+02:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dim@UNIX:5432/pgloader {100599BE63}>
2017-06-01T14:05:55.223000+02:00 DEBUG SET client_encoding TO 'utf8'
2017-06-01T14:05:55.223000+02:00 DEBUG SET work_mem TO '128MB'
2017-06-01T14:05:55.223000+02:00 DEBUG SET standard_conforming_strings TO 'on'
2017-06-01T14:05:55.223000+02:00 DEBUG SET application_name TO 'pgloader'
2017-06-01T14:05:55.223000+02:00 DEBUG BEGIN
2017-06-01T14:05:55.223000+02:00 NOTICE drop table if exists jordane;
2017-06-01T14:05:55.223000+02:00 NOTICE CREATE TABLE jordane
       (
         "NOM" character(20),
         "PRENOM" character(20)
       )
2017-06-01T14:05:55.224000+02:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dim@UNIX:5432/pgloader {100599BE63}>
2017-06-01T14:05:55.224000+02:00 DEBUG SET client_encoding TO 'utf8'
2017-06-01T14:05:55.224000+02:00 DEBUG SET work_mem TO '128MB'
2017-06-01T14:05:55.224000+02:00 DEBUG SET standard_conforming_strings TO 'on'
2017-06-01T14:05:55.224000+02:00 DEBUG SET application_name TO 'pgloader'
2017-06-01T14:05:55.224000+02:00 SQL 
    select nspname, relname, c.oid, attname,
           t.oid::regtype as type,
           case when atttypmod > 0 then atttypmod - 4 else null end as typmod,
           attnotnull,
           case when atthasdef then def.adsrc end as default
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid and attnum > 0
           left join pg_attrdef def on a.attrelid = def.adrelid
                                   and a.attnum = def.adnum

     where nspname !~ '^pg_' and n.nspname <> 'information_schema'
           and relkind = 'r'
           and ((n.nspname = 'public' and c.relname ~ '^jordane$'))
           

  order by nspname, relname, attnum
2017-06-01T14:05:55.225000+02:00 SQL 
  select n.nspname,
         i.relname,
         i.oid,
         rn.nspname,
         r.relname,
         indisprimary,
         indisunique,
         pg_get_indexdef(indexrelid),
         c.conname,
         pg_get_constraintdef(c.oid)
    from pg_index x
         join pg_class i ON i.oid = x.indexrelid
         join pg_class r ON r.oid = x.indrelid
         join pg_namespace n ON n.oid = i.relnamespace
         join pg_namespace rn ON rn.oid = r.relnamespace
         left join pg_constraint c ON c.conindid = i.oid
                                  and c.conrelid = r.oid
                                  -- filter out self-fkeys
                                  and c.confrelid <> r.oid
   where n.nspname !~ '^pg_' and n.nspname <> 'information_schema'
         and ((rn.nspname = 'public' and r.relname ~ '^jordane$'))
         
order by n.nspname, r.relname
2017-06-01T14:05:55.225000+02:00 SQL 
 select n.nspname, c.relname, nf.nspname, cf.relname as frelname,
        r.oid, conname,
        pg_catalog.pg_get_constraintdef(r.oid, true) as condef,
        (select string_agg(attname, ',')
           from pg_attribute
          where attrelid = r.conrelid
            and array[attnum::integer] <@ conkey::integer[]
        ) as conkey,
        (select string_agg(attname, ',')
           from pg_attribute
          where attrelid = r.confrelid
            and array[attnum::integer] <@ confkey::integer[]
        ) as confkey,
        confupdtype, confdeltype, confmatchtype,
        condeferrable, condeferred
   from pg_catalog.pg_constraint r
        JOIN pg_class c on r.conrelid = c.oid
        JOIN pg_namespace n on c.relnamespace = n.oid
        JOIN pg_class cf on r.confrelid = cf.oid
        JOIN pg_namespace nf on cf.relnamespace = nf.oid
   where r.contype = 'f'
         AND c.relkind = 'r' and cf.relkind = 'r'
         AND n.nspname !~ '^pg_' and n.nspname <> 'information_schema'
         AND nf.nspname !~ '^pg_' and nf.nspname <> 'information_schema'
         and ((n.nspname = 'public' and c.relname ~ '^jordane$'))
         
         and ((nf.nspname = 'public' and cf.relname ~ '^jordane$'))
         
2017-06-01T14:05:55.225000+02:00 DEBUG fetch-pgsql-catalog: 1 tables, 0 indexes, 0+0 fkeys
2017-06-01T14:05:55.227000+02:00 NOTICE TRUNCATE public.jordane;
2017-06-01T14:05:55.227000+02:00 NOTICE COPY "jordane"
2017-06-01T14:05:55.227000+02:00 DEBUG Reader started for jordane
2017-06-01T14:05:55.227000+02:00 DEBUG Transformer 2 in action for jordane!
2017-06-01T14:05:55.233000+02:00 NOTICE Opening (:INLINE (#P"/Users/dim/dev/pgloader/test/csv-error.load" . 476))
2017-06-01T14:05:55.234000+02:00 FATAL :ASCII stream decoding error on
#<SB-SYS:FD-STREAM for "file /Users/dim/dev/pgloader/test/csv-error.load" {100791B813}>:

  the octet sequence #(195) cannot be decoded.
2017-06-01T14:05:55.234000+02:00 DEBUG finish-batch[3] 4 rows in 0.007000s
2017-06-01T14:05:55.234000+02:00 DEBUG Reader for jordane is done in 0.007000s
2017-06-01T14:05:55.234000+02:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dim@UNIX:5432/pgloader {100776B9D3}>
2017-06-01T14:05:55.234000+02:00 DEBUG SET client_encoding TO 'utf8'
2017-06-01T14:05:55.234000+02:00 DEBUG SET work_mem TO '128MB'
2017-06-01T14:05:55.234000+02:00 DEBUG SET standard_conforming_strings TO 'on'
2017-06-01T14:05:55.234000+02:00 DEBUG SET application_name TO 'pgloader'
2017-06-01T14:05:55.234000+02:00 INFO pgsql:copy-from-queue[0]: jordane ("NOM" "PRENOM")
2017-06-01T14:05:55.235000+02:00 DEBUG start jordane                  225
2017-06-01T14:05:55.440000+02:00 DEBUG Finished processing READER for "jordane"          0.007000s
2017-06-01T14:05:55.440000+02:00 DEBUG format-data-to-copy[2] 4 row in 0.000000s
2017-06-01T14:05:55.441000+02:00 INFO Transformer[2] for jordane is done in 0.022000s
2017-06-01T14:05:55.441000+02:00 DEBUG Finished processing WORKER for "jordane"          0.022000s
2017-06-01T14:05:55.442000+02:00 ERROR Database error 22001: value too long for type character(20)
CONTEXT: COPY jordane, line 4, column PRENOM: "testprenombe~aucouptroplong"
2017-06-01T14:05:55.442000+02:00 INFO Entering error recovery.
2017-06-01T14:05:55.442000+02:00 DEBUG BEGIN
2017-06-01T14:05:55.442000+02:00 INFO error recovery at 0/4, next error at 4, loading 3 rows
2017-06-01T14:05:55.442000+02:00 INFO error recovery at 4/4, processing bad row
2017-06-01T14:05:55.443000+02:00 INFO Recovery found 1 errors in 4 rows
2017-06-01T14:05:55.443000+02:00 DEBUG copy-batch[0] jordane 3 rows in 0.009000s
2017-06-01T14:05:55.443000+02:00 DEBUG Writer[0] for jordane is done in 0.009000s
2017-06-01T14:05:55.443000+02:00 DEBUG Finished processing WRITER for "jordane"          0.009000s
2017-06-01T14:05:55.444000+02:00 LOG report summary reset
             table name       read   imported     errors      total time       read      write
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
                  fetch          0          0          0          0.008s                     
            before load          2          2          0          0.015s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
                jordane          4          3          2          0.036s     0.007s    0.009s
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
        Files Processed          1          1          0          0.021s                     
COPY Threads Completion          3          3          0          0.062s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
      Total import time          4          3          2          0.448s     0.007s    0.009s
2017-06-01T14:05:55.449000+02:00 INFO Stopping monitor
```

**Comment by dimitri** [comment] 2017-06-01 14:47
The self-contained test case can be even more self-contained now, but I still fail to reproduce your error in lower-than-debug settings, the following error being gracefully handled.

```
2017-06-01T16:45:11.208656+02:00 FATAL Database error 22001: value too long for type character varying(4)
CONTEXT: COPY t546, line 2, column id: "test value"
2017-06-01T16:45:11.208942+02:00 ERROR A thread failed with error: Stop loading data for table "\"t546\"" on first error.
2017-06-01T16:45:11.209292+02:00 FATAL Stop loading data for table "\"t546\"" on first error.
```

I still have to understand what happens from the built binary, as my testing environment as a different code base. You can see that at https://github.com/dimitri/pgloader/blob/master/src/sources/common/methods.lisp#L156 and following.

```
LOAD CSV
     FROM INLINE with encoding 'ascii'
     INTO postgresql:///pgloader?t546

     WITH on error stop,
          skip header = 1,
          batch rows = 500,
          quote identifiers,
          fields terminated by ','

   BEFORE LOAD DO
    $$ drop table if exists t546; $$,
    $$ CREATE TABLE t546 ("id" VARCHAR(4) NOT NULL); $$;


"id"
"test"
"test value"
```

**Comment by dimitri** [comment] 2017-06-17 17:04
It should be fixed now, please try again from current sources. I can't reproduce your test case anymore, all I have is the following expected behaviour with no user action required:

```
2017-06-17T19:01:01.278000+02:00 ERROR Database error 22001: value too long for type character varying(4)
CONTEXT: COPY t546, line 2, column id: "test value"
2017-06-17T19:01:01.278000+02:00 FATAL On Error Stop: Database error 22001: value too long for type character varying(4)
CONTEXT: COPY t546, line 2, column id: "test value"
2017-06-17T19:01:01.278000+02:00 LOG report summary reset
             table name       read   imported     errors      total time       read      write
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
                  fetch          0          0          0          0.010s                     
            before load          2          2          0          0.014s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
                 "t546"          4          0          0          0.008s     0.008s          
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
        Files Processed          1          1          0          0.022s                     
COPY Threads Completion          3          3          0          0.042s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
      Total import time          4          0          0          0.282s     0.008s    0.000s
2017-06-17T19:01:01.281000+02:00 INFO Stopping monitor
```

**Closed** 2017-06-17 17:04 UTC
