### ISSUE TITLE
Failing to handle MySQL FULLTEXT indexes

### ISSUE THREAD

**Issue by Hoya** [dimitri/pgloader#569] opened 2017-06-07 07:05 UTC
I'm getting this error:

```
2017-06-07T06:56:42.744000Z ERROR Database error 54000: index row size 2872 exceeds maximum 2712 for index "idx_5199509_search"
HINT: Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
QUERY: CREATE INDEX "idx_5199509_search" ON "fcm_batches" ("raw_payload");
```

The index in question is a FULLTEXT index on a MEDIUMTEXT type column on MySQL.
Is there a work around for this?

**Comment by dimitri** [comment] 2017-06-07 11:30
Yes, ignore the error in the migration script then create a Full Text Index in PostgreSQL (in the `AFTER LOAD` section of the command, maybe). This will use the GIN indexing rather than the classic BTree one and this limit will not apply: you will be indexing words (lexems) from the documents rather than the whole document at once.

See https://www.postgresql.org/docs/current/static/textsearch-tables.html#TEXTSEARCH-TABLES-INDEX for more details.

**Closed by dimitri** 2017-06-07 11:30 UTC

**Comment by Hoya** [comment] 2017-09-14 05:38
Sorry I left this hanging. How can I "ignore" the error? pgloader just dies when I hit this issue.

**Comment by dimitri** [comment] 2017-09-14 09:43
Can you give me the table definition so that I can reproduce the bug locally? then I will provide a fix, either with an *ignore* capability or with the proper transformation if possible. Thanks.

**Comment by Hoya** [comment] 2017-09-14 09:46
Sure,

CREATE TABLE `fcm_batches` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `raw_payload` mediumtext COLLATE utf8_unicode_ci,
  `success` int(10) unsigned NOT NULL DEFAULT '0',
  `failed` int(10) unsigned NOT NULL DEFAULT '0',
  `modified` int(10) unsigned NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fcm_batches_created_at_index` (`created_at`),
  FULLTEXT KEY `search` (`raw_payload`)
) ENGINE=InnoDB AUTO_INCREMENT=2501855 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


I'm using MariaDB 10.2.
Try inserting some long text into the 'raw_payload' field.

**Comment by dimitri** [comment] 2017-09-14 09:54
I get the following error, what should I do?

```
Server version: 5.5.35-MariaDB Homebrew

ERROR 1214 (HY000): The used table type doesn't support FULLTEXT indexes
```

**Comment by dimitri** [comment] 2017-09-14 13:51
I could reproduce the `create index` error locally, and pgloader doesn't stop on it: it continues with the other tables and indexes just fine. So please consider upgrading to current git version (build locally)! I'm surprised tho, because it should have been almost always the case that pgloader would handle CREATE INDEX errors gracefully. Which version are you using?

Also, I added support for FULLTEXT indexes in MySQL, porting them to a GIN index over a PostgreSQL Full Text *simple* configuration. I guess most application won't be happy with this setup, but it allows the porting to be fully automated, and a production grade Full Text Setup in PostgreSQL might incur per-column or per-document dictionary choice, among other subtleties. See https://www.postgresql.org/docs/current/static/textsearch-tables.html#TEXTSEARCH-TABLES-INDEX

**Comment by Hoya** [comment] 2017-09-15 03:57
That's strange.

This is the error I get and stops:

```
2017-09-14T03:24:54.110517Z ERROR PostgreSQL Database error 54000: index row size 2872 exceeds maximum 2712 for index "idx_21920523_search"
HINT: Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
QUERY: CREATE INDEX idx_21920523_search ON sgkit_load.fcm_batches (raw_payload);
```

And the version I'm using:

```
pgloader-ccl -V
pgloader version "3.4.e7f6505"
compiled with Clozure Common Lisp Version 1.11-r16635  (LinuxX8664)
```
