### ISSUE TITLE
pgloader not starting the migration process and only Starting and Stopping Monitor, But nothing in logs

### ISSUE THREAD

**Issue by harsharm6** [dimitri/pgloader#1044] opened 2019-11-20 14:42 UTC
I am trying to convert mysql database into pgsql, and i have restored the mysql dump on UBUNTU MACHINE. On this ubuntu server i have installed Pgloader, mysql.5.6 and pgsql.v.10.
Initially i used Pgsql.v.10 but i read somewhere its incompatible with Pgloader, so tried whole process with PostgreSQL 9.4.25, but no luck.
 
I have compiled Pgloader from source.
Ubuntu Version: 16.04.6 LTS
 

# pgloader --version
pgloader version "3.6.1"
compiled with SBCL 1.3.1.debian

  - [x] pgloader output you obtain
  
```
# pgloader --debug mysql://root:password@localhost/sonardb postgresql://jira:password@localhost/sonardb
pgloader version 3.6.1
compiled with SBCL 1.3.1.debian
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2019-11-20T20:18:05.027000+05:30 NOTICE Starting pgloader, log system is ready.
2019-11-20T20:18:05.043000+05:30 INFO Starting monitor
2019-11-20T20:18:05.048000+05:30 LOG pgloader version "3.6.1"
2019-11-20T20:18:05.049000+05:30 INFO Stopping monitor
```

My DB size in Mysql is of 9.768 GB.

Anyone have any thoughts or suggestions as to what may be going wrong?

Thanks!
Harsh

**Comment by SerhiyRomanov** [comment] 2019-11-27 13:25
I am confirm that I've encountered the same issue
```
pgloader --verbose --debug  mysql://user:password@localhost/db postgresql://user:password@127.0.0.1/db
pgloader version 3.6.1
compiled with SBCL 1.4.5.debian
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2019-11-27T15:18:30.009000+02:00 NOTICE Starting pgloader, log system is ready.
2019-11-27T15:18:30.022000+02:00 INFO Starting monitor
2019-11-27T15:18:30.024000+02:00 LOG pgloader version "3.6.1"
2019-11-27T15:18:30.024000+02:00 INFO Stopping monitor
```
My system: Ubuntu 18.04.3 LTS, kernel 4.15.0-70-generic
I'm trying to migrate from MariaDB 10.1.43 to Postgres 12. 
Which additional info are needed?

**Comment by SerhiyRomanov** [comment] 2019-11-28 10:42
Finally, i found out that problem was that "pgloader quietly fails when mysql connection errors occurs even with debug enabled" (here is issue for it https://github.com/dimitri/pgloader/issues/1022)
In my case, I use dots for database name in database connection url, so pgloader detect it as sqlite instead of mysql (see related issues https://github.com/dimitri/pgloader/issues/1048 and https://github.com/dimitri/pgloader/issues/534)

**Comment by dimitri** [comment] 2020-02-12 17:31
Can't reproduce, I get a clean ERROR message. Closing for triaging, please re-open with information on how to reproduce if you still have the problem.

```
$ ./build/bin/pgloader mysql://root@127.0.0.1:3307/f1db?useSSL=false  pgsql:///plop
2020-02-12T18:30:26.015000+01:00 LOG pgloader version "3.6.e551099"
2020-02-12T18:30:26.028000+01:00 LOG Data errors in '/private/tmp/pgloader/'
2020-02-12T18:30:26.097000+01:00 LOG Migrating from #<MYSQL-CONNECTION mysql://root@127.0.0.1:3307/f1db {100596CF53}>
2020-02-12T18:30:26.098000+01:00 LOG Migrating into #<PGSQL-CONNECTION pgsql://dim@UNIX:5432/plop {1005AAF323}>
2020-02-12T18:30:26.100000+01:00 ERROR mysql: Failed to connect to mysql at "127.0.0.1" (port 3307) as user "root": Condition USOCKET:CONNECTION-REFUSED-ERROR was signalled.
2020-02-12T18:30:26.100000+01:00 LOG report summary reset
       table name     errors       rows      bytes      total time
-----------------  ---------  ---------  ---------  --------------
  fetch meta data          0          0                     0.000s
-----------------  ---------  ---------  ---------  --------------
-----------------  ---------  ---------  ---------  --------------
```

**Closed by dimitri** 2020-02-12 17:31 UTC
