### ISSUE TITLE
type error crashes pgloader to debugger

### ISSUE THREAD

**Issue by slotrans** [dimitri/pgloader#243] opened 2015-06-02 21:31 UTC
Simplified example to illustrate the problem...

/* table */
```
=> create table pgloader_test ( id serial primary key, somefield int not null ) ;
```

/* conf file */
```
LOAD CSV
FROM STDIN
WITH ENCODING utf-8
HAVING FIELDS ( somefield )
INTO postgresql://nyetter:PASSWORD@myhost.mydomain.net:5432/mydb?tablename=nyetter.pgloader_test&sslmode=require
TARGET COLUMNS ( somefield )
WITH skip header = 1, batch rows = 1
SET client_encoding to 'utf-8'
;
```

/* data file */
```
"somefield"
"1"
"2"
"three"
"4"
"5"
```

/* result */
```
$ cat pgloader_test_data.txt | ~/apps/pgloader/build/bin/pgloader --verbose pgloader3_test.conf
2015-06-02T15:22:43.009000-06:00 NOTICE Starting pgloader, log system is ready.
2015-06-02T15:22:43.017000-06:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2015-06-02T15:22:43.020000-06:00 LOG Data errors in '/private/tmp/pgloader/'
2015-06-02T15:22:43.020000-06:00 LOG Parsing commands from file #P"/Users/noah.yetter/temp/pgloader3_test.conf"
2015-06-02T15:22:43.220000-06:00 NOTICE COPY (nyetter . pgloader_test)
2015-06-02T15:22:43.421000-06:00 NOTICE SET search_path TO nyetter;
2015-06-02T15:22:43.422000-06:00 ERROR Database error 22P02: invalid input syntax for integer: "three"
CONTEXT: COPY pgloader_test, line 1, column somefield: "three"

debugger invoked on a TYPE-ERROR in thread
#<THREAD "lparallel" RUNNING {10093D8B63}>:
  The value NIL is not of type PGLOADER.UTILS::PGTABLE.
```
...and it just hangs there until I ^C it.

Obviously the input data is bad but that's the whole point of using pgloader.  I get data with errors from a third party and rely on pgloader to throw away the bad rows.  The old pgloader 2.x does that quite well, but 3.x seems to choke on it and crash.

The second problem is that unhandled errors invoke the debugger.  This is fine for development builds but production builds should simply exit with an error code.  There should be a way to disable the debugger, even if it involves editing the Makefile.

**Comment by dimitri** [comment] 2015-06-04 13:38
I can't reproduce your failure here. Can you tell me which version of pgloader you are using?

Here's my self-contained test case and the result:

```
LOAD CSV
  FROM INLINE WITH ENCODING utf-8 HAVING FIELDS (somefield)
  INTO postgresql:///pgloader?tablename=t243 TARGET COLUMNS (somefield)

  WITH skip header = 1,
       batch rows = 1

  BEFORE LOAD DO
    $$ drop table if exists t243; $$,
    $$ create table t243(somefield integer); $$;

"somefield"
"1"
"2"
"three"
"4"
"5"
```

The version:
``
./build/bin/pgloader --version
pgloader version "3.2.c3b5d60"
compiled with SBCL 1.2.10
```

Test with full debug information:
```
~/dev/pgloader ./build/bin/pgloader --verbose --debug ~/dev/temp/243.load 
./build/bin/pgloader --verbose --debug ~/dev/temp/243.load 
sb-impl::*default-external-format* :US-ASCII
tmpdir: #P"/var/folders/w7/9n8v8pw54t1gngfff0lj16040000gn/T/"
2015-06-04T15:36:36.017000+02:00 NOTICE Starting pgloader, log system is ready.
2015-06-04T15:36:36.078000+02:00 INFO Starting monitor
2015-06-04T15:36:36.086000+02:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2015-06-04T15:36:36.086000+02:00 LOG Data errors in '/private/tmp/pgloader/'
2015-06-04T15:36:36.086000+02:00 LOG Parsing commands from file #P"/Users/dim/dev/temp/243.load"
       table name       read   imported     errors            time
-----------------  ---------  ---------  ---------  --------------
            fetch          0          0          0          0.014s
      before load          2          2          0          0.019s
-----------------  ---------  ---------  ---------  --------------
             t243          5          4          1          0.037s
-----------------  ---------  ---------  ---------  --------------
Total import time          5          4          1          0.070s
2015-06-04T15:36:36.287000+02:00 DEBUG CONNECT #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dim@UNIX:54393/pgloader {1007C2B7A3}>
2015-06-04T15:36:36.287000+02:00 DEBUG CONNECT #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dim@UNIX:54393/pgloader {1007C2B7A3}>
2015-06-04T15:36:36.287000+02:00 DEBUG BEGIN
2015-06-04T15:36:36.287000+02:00 NOTICE drop table if exists t243;
2015-06-04T15:36:36.287000+02:00 NOTICE create table t243(somefield integer);
2015-06-04T15:36:36.287000+02:00 NOTICE COPY t243
2015-06-04T15:36:36.287000+02:00 DEBUG CONNECT #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dim@UNIX:54393/pgloader {1007C2B7A3}>
2015-06-04T15:36:36.317000+02:00 INFO pgsql:copy-from-queue: t243 ("somefield")
2015-06-04T15:36:36.317000+02:00 INFO COPY FROM #P"/Users/dim/dev/temp/243.load"
2015-06-04T15:36:36.317000+02:00 DATA < #("1")
2015-06-04T15:36:36.317000+02:00 DATA < #("2")
2015-06-04T15:36:36.317000+02:00 DATA < #("three")
2015-06-04T15:36:36.317000+02:00 DATA < #("4")
2015-06-04T15:36:36.317000+02:00 DATA < #("5")
2015-06-04T15:36:36.317000+02:00 DEBUG Sending last batch (1 rows)
2015-06-04T15:36:36.318000+02:00 DEBUG End of data.
2015-06-04T15:36:36.318000+02:00 DEBUG BEGIN
2015-06-04T15:36:36.318000+02:00 DATA > "1
"
2015-06-04T15:36:36.318000+02:00 DEBUG copy-batch t243 1 row
2015-06-04T15:36:36.318000+02:00 DEBUG BEGIN
2015-06-04T15:36:36.318000+02:00 DATA > "2
"
2015-06-04T15:36:36.318000+02:00 DEBUG copy-batch t243 1 row
2015-06-04T15:36:36.318000+02:00 DEBUG BEGIN
2015-06-04T15:36:36.318000+02:00 DATA > "three
"
2015-06-04T15:36:36.318000+02:00 ERROR Database error 22P02: invalid input syntax for integer: "three"
CONTEXT: COPY t243, line 1, column somefield: "three"
2015-06-04T15:36:36.395000+02:00 INFO Entering error recovery.
2015-06-04T15:36:36.395000+02:00 INFO error recovery at 1/1, processing bad row
2015-06-04T15:36:36.396000+02:00 INFO Recovery found 1 errors in 1 row
2015-06-04T15:36:36.396000+02:00 DEBUG copy-batch t243 0 rows
2015-06-04T15:36:36.396000+02:00 DEBUG BEGIN
2015-06-04T15:36:36.396000+02:00 DATA > "4
"
2015-06-04T15:36:36.396000+02:00 DEBUG copy-batch t243 1 row
2015-06-04T15:36:36.396000+02:00 DEBUG BEGIN
2015-06-04T15:36:36.396000+02:00 DATA > "5
"
2015-06-04T15:36:36.396000+02:00 DEBUG copy-batch t243 1 row
2015-06-04T15:36:36.396000+02:00 INFO Stopping monitor
```

**Comment by slotrans** [comment] 2015-06-09 23:01
built from commit ff5b596219594bd2578ce097b0dd9ce92c3e3681

$ build/bin/pgloader --version
pgloader version "3.2.ff5b596"
compiled with SBCL 1.2.11

**Comment by dimitri** [comment] 2015-06-10 13:39
Can you reproduce the bug with the test-case I've been working from? Just in case it would not be completely equivalent to what you were doing, which I seriously doubt (but some details are easy to miss).

**Comment by dimitri** [comment] 2016-01-08 21:48
Closing the issue in an attempt to clean-up, please re-open as you see fit!

**Closed by dimitri** 2016-01-08 21:48 UTC
Labels: Must Fix, Needs more testing / information
