### ISSUE TITLE
MySQL Default Dates not Properly Converted

### ISSUE THREAD

**Issue by wdarosh** [dimitri/pgloader#252] opened 2015-06-27 17:57 UTC
I have been working on migrating a MySQL database into PostgreSQL and there has been an issue with the conversion of zero dates. I have followed all the documentation for the configuration and it has not properly converted the column where the date is stored as 0000-00-00 00:00:00 however the zero dates conversion is working correctly.

**Comment by dimitri** [comment] 2015-06-27 18:39
Can I have more details please? Is it a default value or a value in the table, what is the table definition, the error messages you have, the loading setup, etc etc?

**Comment by wdarosh** [comment] 2015-06-29 16:19
Certainly:

It is a value in the table that stores the following:

ip | datestamp - Neither of these fields have a default value the code populates these values and there are no database triggers.  

What I am receiving is OUT OF RANGE errors when doing the transposition. We have been able to clear updating the MySQL dates so we could move forward.

Here is the file being utilized for loading:

-- Snippet from Loader:
WITH include drop, create tables, no truncate,
      create indexes, reset sequences, foreign keys

CAST
     type datetime to timestamptz using zero-dates-to-null,
     type datetime when default '0000-00-00 00:00:00' to timestamp using zero-dates-to-null,
     type datetime to timestamp drop default drop not null using zero-dates-to-null,

     type date when default '0000-00-00' to date using zero-dates-to-null,
     type date to date drop not null drop default using zero-dates-to-null;

**Comment by dimitri** [comment] 2015-06-29 19:50
I would need the full exact error message to have an opinion on how to consider and fix that bug... do you still have that?

**Comment by wdarosh** [comment] 2015-06-29 20:23
CONTEXT: COPY ip_blocks, line 1, column creationdt: "0000-00-00 00:00:00"
2015-06-26T19:54:56.641000+03:00 ERROR Database error 22008: date/time field value out of range: "0000-00-00 00:00:00"

**Comment by dimitri** [comment] 2015-06-29 20:48
This is quite surprising indeed. Can you tell me the datatype of the column `creationdt` in MySQL, just in case something obvious shows up, and then I think I'll close the issue as you managed to get away from this situation. Thanks for providing me with the details!

**Comment by wdarosh** [comment] 2015-06-29 23:13
Certainly - Also I apologize for the sporadic and somewhat incomplete answers. I am on a bit of a sprint to get a massive migration done.

Table Definition:
  `ip_domain` varchar(100) NOT NULL DEFAULT '',
  `list_type` varchar(20) NOT NULL DEFAULT '',
  `creationdt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

I was migrating to PostgreSQL 9.4.4 if that helps at all.

**Comment by dimitri** [comment] 2015-06-30 08:49
I have the following in https://github.com/dimitri/pgloader/blob/master/src/sources/mysql/mysql-cast-rules.lisp:

```
    ;; date types without strange defaults
    (:source (:type "date")      :target (:type "date"))
    (:source (:type "datetime")  :target (:type "timestamptz"))
    (:source (:type "timestamp") :target (:type "timestamptz"))
    (:source (:type "year")      :target (:type "integer" :drop-typemod t))
```

So I think we just need to add *timestamp* in the default list of casts. Or add a type case in the load file.

**Comment by Jamim** [comment] 2015-07-10 10:18
I can confirm this issue.
In my case *pgloader* was used without additional options and command looked like
```
pgloader SOURCE TARGET 
```
###### Error message:
```
CONTEXT: COPY accounts_calllog, line 19, column created_time: "0000-00-00 00:00:00"
2015-07-09T15:02:17.338000Z ERROR Database error 22008: date/time field value out of range: "0000-00-00 00:00:00"
```
###### Field description:
```
+--------------------+--------------+------+-----+---------+----------------+
| Field              | Type         | Null | Key | Default | Extra          |
+--------------------+--------------+------+-----+---------+----------------+
…
| created_time       | datetime     | YES  |     | NULL    |                |
…
```

**Comment by dimitri** [comment] 2015-07-10 20:13
I believe we can now close this issue. As usual, if that assumption turns out wrong, feel free to reopen.

**Closed by dimitri** 2015-07-10 20:13 UTC
