### ISSUE TITLE
PgLoader does not support MySQL Authentication Switch protocol.

### ISSUE THREAD

**Issue by xiangyhu** [dimitri/pgloader#917] opened 2019-02-27 08:35 UTC
ERROR mysql: Failed to connect to mysql at "XXX" (port 3306) as user "XXX": The value of SEQUENCE is "/d*w+D7Lu_w3`G-i", which is not of type IRONCLAD::SIMPLE-OCTET-VECTOR

  - [ ] pgloader --version
  
    ```
    pgloader version "3.6.1"
compiled with SBCL 1.4.0-1.el7
    ```
  
  - [ ] did you test a fresh compile from the source tree?
    
    Yes
    
  - [ ] did you search for other similar issues?
    Yes
    
  - [ ] how can I reproduce the bug?

    Incude a self-contained pgloader command file.

    Microsoft Azure's MySQL service is using MySQL's authentication switch protocol and pgLoader does not support that. You can actually expect this behavior by looking at pgLoader's code or create and try an Azure MySQL server to test with.

```
pgloader --debug --verbose script.load

script.load contents:

load database
FROM  mysql://XXX
 INTO  postgresql://XXX
WITH include drop, create tables, no truncate,
create indexes, reset sequences, foreign keys
--SET maintenance_work_mem to '128MB', work_mem to '12MB', search_path to 'sakila'
CAST type datetime to timestamptz
drop default drop not null using zero-dates-to-null,
type date drop not null drop default using zero-dates-to-null
MATERIALIZE VIEWS film_list, staff_list
-- INCLUDING ONLY TABLE NAMES MATCHING ~/film/, 'actor'
-- EXCLUDING TABLE NAMES MATCHING ~<ory>
BEFORE LOAD DO
$$ create schema if not exists testdb; $$;
```

  - [ ] How the data is different from what you expected, if relevant

**Comment by dimitri** [comment] 2019-03-01 10:12
I believe this issue is a duplicate of https://github.com/dimitri/pgloader/issues/782 ; can you confirm that? thanks

**Comment by twocode** [comment] 2019-03-08 14:57
Hi @dimitri , yes. Basically this is some kind of MySQL's authentication switch protocol.

**Comment by dimitri** [comment] 2019-03-14 17:26
I'll close the issue here then, let's keep track of any progress we manage to make on the other one.

**Closed by dimitri** 2019-03-14 17:26 UTC
