### ISSUE TITLE
Compiling Commit 7af6c7a  with Clozure cl 1.11 causes the following errors

### ISSUE THREAD

**Issue by wand3r3r** [dimitri/pgloader#392] opened 2016-04-25 14:10 UTC
I am trying to compile pgloader with Clozure CL after reading issues regarding heap exhaustion errors.
```
==================================================
240,107 bytes in 3.10 seconds (75.71KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/cl-mssql/2013-10-03/cl-mssql-20131003-git.tgz">
; 15.04KB
==================================================
15,398 bytes in 0.59 seconds (25.49KB/sec)
; Loading "mssql"
> Error: Error while trying to load definition for system cffi from pathname <home/dir>/pgloader/build/quicklisp/dists/quicklisp/software/cffi_0.17.1/cffi.asd: (OPERATE 'TEST-OP :CFFI-TESTS) can't be destructured against the lambda list (O C), because it contains 3 elements, and exactly 2 are expected.
> While executing: (:INTERNAL LOAD-SYSDEF), in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip evaluation of (ql:quickload "pgloader")
> Type :? for other options.
```

As the build progresses I get more errors:
```
==================================================
24,658 bytes in 0.52 seconds (46.31KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/local-time/2016-04-21/local-time-20160421-git.tgz">
; 290.39KB
==================================================
297,360 bytes in 4.77 seconds (60.90KB/sec)
; Loading "local-time"
> Error: Error while trying to load definition for system bordeaux-threads from pathname <home/dir>/pgloader/build/quicklisp/dists/quicklisp/software/bordeaux-threads-v0.8.5/bordeaux-threads.asd: You need ASDF >= 3.1 to load this system correctly.
> While executing: (:INTERNAL ASDF::LOAD-SYSDEF), in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip evaluation of (ql:quickload "pgloader")
> Type :? for other options.
```
AND

```
cl --no-init --load build/quicklisp/setup.lisp               \
             --eval '(ql:quickload "buildapp")'                   \
             --eval '(buildapp:build-buildapp "build/bin/buildapp.ccl")'              \
             --eval '(quit)'
To load "buildapp":
  Install 1 Quicklisp release:
    buildapp
; Fetching #<URL "http://beta.quicklisp.org/archive/buildapp/2015-12-18/buildapp-1.5.6.tgz">
; 16.00KB
==================================================
16,389 bytes in 0.14 seconds (115.98KB/sec)
; Loading "buildapp"
[package buildapp]...........
Fatal SIMPLE-ERROR:
  Module ASDF was not provided by any function on CCL:*MODULE-PROVIDER-FUNCTIONS*.
> Error: Error #<SILENT-EXIT-ERROR #x5DD3AD06>
> While executing: (:INTERNAL MAIN), in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip evaluation of (buildapp:build-buildapp "build/bin/buildapp.ccl")
> Type :? for other options.

```

**Comment by dimitri** [comment] 2016-04-27 19:39
I can't reproduce your error here, sorry... Can you test the docker image at docker hub?

    docker pull dimitri/pgloader:ccl.latest

Other than that, can you tell us more about your system?

**Comment by dimitri** [comment] 2016-08-07 17:18
Closing for lack of information.

**Closed by dimitri** 2016-08-07 17:18 UTC
Labels: Build System
